### ISSUE TITLE
Basic Authentication is missing when using a private registry

### ISSUE THREAD

**Issue by jmmartins** [raineorshine/npm-check-updates#1017]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 12`

---------------------------

## Steps to Reproduce
1. Configure a private registry that requires authentication in the project's .npmrc (JFrog Artifactory in my case)
2. Run `ncu`
3. The following message is shown: **Unable to authenticate, need: Basic realm="Artifactory Realm"**

## Current Behavior
Authentication into a private registry fails.

## Expected Behavior
Authentication into a private registry is successful.

**Comment by raineorshine** [comment]
Basic Authentication is notoriously tricky with npm-check-updates because the package fetcher doesn't handle auth the same way as npm itself without configuration. I believe all actual auth bugs in npm-check-updates were fixed though, so it's likely a problem with your auth config. Unfortunately it's not my specialty, but you might be able to glean some ideas from #556.

**Comment by jmmartins** [comment]
You were right, I got it to work.
It was an issue with my user .npmrc file.

**Comment by raineorshine** [comment]
Thanks! What was the issue btw? It might help other users who experience this issue know what to look for.

**Comment by tsimbalar** [comment]
I stumbled into a similar issue ... and here is some extra info in case that useful for anyone finding the same issues ... or if that can help improving the tool 😇 

For what it's worth, in my company, we also use jFrog Artifactory, and use the following process to configure our local `npm` on our dev machines : https://www.jfrog.com/confluence/display/JFROG/npm+Registry#npmRegistry-AuthenticatingthenpmClient (the little frame about "Getting .npmrc entries directly from Artifactory")

> Run the following command to retrieve these strings directly from Artifactory:
> `$ curl -uadmin:<CREDENTIAL> http://<ARTIFACTORY_SERVER_DOMAIN>:8081/artifactory/api/npm/auth`
> 
> Where `<CREDENTIAL>` is your Artifactory password or APIKey.
> 
> Here is an example of the response:
> ```
> _auth = YWRtaW46e0RFU2VkZX1uOFRaaXh1Y0t3bHN4c2RCTVIwNjF3PT0=
> email = myemail@email.com
> always-auth = true
> ```
> 

When following this process, I ended up with the following in my `.npmrc` file in my HOME directory : 

```
registry=https://<companyregistry>.jfrog.io/<companyregistry>/api/npm/health-npm/
_auth = dGhpYmF1......snipped......5aW9xckxw
always-auth = true
email = thibaud.desodt@<company>.com
```

In addition, in our projects we also have a `.npmrc` file that looks like this : 

```
registry="https://<companyregistry>.jfrog.io/<companyregistry>/api/npm/health-npm/"
```

to enforce using the private registry.

With that setup, indeed I got the authentication issue about the Realm.

If I run `npm config list` from my project's root, I get this : 

```
>npm config list      
; "user" config from /Users/tdesodt/.npmrc

//<companyregistry>.jfrog.io/<companyregistry>/api/npm/health-npm/:_password = (protected) 
//<companyregistry>.jfrog.io/<companyregistry>/api/npm/health-npm/:username = "thibaud.desodt@<company>.com" 
always-auth = true 
email = "thibaud.desodt@<company>.com" 
; registry = "https://<companyregistry>.jfrog.io/<companyregistry>/api/npm/health-npm/" ; overridden by project

; "project" config from /Users/tdesodt/dev/core-team/customer-service/.npmrc

registry = "https://<companyregistry>.jfrog.io/<companyregistry>/api/npm/health-npm/" 

; node bin location = /Users/tdesodt/.nvm/versions/node/v16.13.0/bin/node
; cwd = /Users/tdesodt/dev/core-team/customer-service
; HOME = /Users/tdesodt
; Run `npm config ls -l` to show all defaults.
```

this gives "some cue" about the expected config format ... 


I could fix it by adding the following in the `.npmrc` of my project

```
//<companyregistry>.jfrog.io/<companyregistry>/api/npm/health-npm/:_auth=dGhpYmF1......snipped......5aW9xckxw
//<companyregistry>.jfrog.io/<companyregistry>/api/npm/health-npm/:email=thibaud.desodt@<company>.com
//<companyregistry>.jfrog.io/<companyregistry>/api/npm/health-npm/:always-auth=true
```

After this, `npx npm-check-updates` works fine 🌈
