### ISSUE TITLE
Feature proposal: custom test command for doctor mode

### ISSUE THREAD

**Issue by pdemarino** [raineorshine/npm-check-updates#1019]
Hi all -

I am using this package to try out updates to a monorepo -- one thought.

The package currently runs `npm test` as a way to ensure that the package builds after the updates. This won't catch issues in e.g., the build process.

Would there be a way to specify a custom `npm` command to run when it comes to validating the build? That way I could have it run the equivalent of `npm test && npm build`, ensuring that the proposed updates don't break the production process, without bloating my day-to-day test suite.

**Comment by raineorshine** [comment]
That's a great suggestion! It has previously been suggested in #777, so I will close this as a duplicate. Feel free to continue discussion there, or create a PR!
