### ISSUE TITLE
Private registries configured in Yarn 404ing.

### ISSUE THREAD

**Issue by phyllisstein** [raineorshine/npm-check-updates#1036]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 12`

—————————————

👋 Hi there. I’ve noticed that `npm-check-upates` has been unable to access private NPM registries configured in `.yarnrc.yml`. The issue seems to resemble #556. However, I know it was working up until recently. I created a reproduction case here: https://github.com/phyllisstein/ncu-private-repo. Thanks for taking a look!

## Steps to Reproduce
1. Configure a private NPM registry in `.yarnrc.yml`. ✅ 
2. Run `yarn` to install dependencies. ✅ 
3. Run `npm-check-updates`. 💥 

## Current Behavior
The command succeeds with a `0` exit status, but `404`s when checking the private package. According to the logs, it’s searching the public NPM registry in spite of the configuration.

## Expected Behavior
I would expect `npm-check-updates` to use the registry set in Yarn’s config file.

**Comment by raineorshine** [comment]
Thanks for the thorough bug report!

Unfortunately, npm-check-updates does not read `.yarnrc.yml` at all! Yarn support was added later to npm-check-updates and so it does have some holes.

One solution is to move the auth token to your `.npmrc` as described in https://github.com/yarnpkg/yarn/issues/606#issuecomment-253104310:

.npmrc:

```
@fortawesome:registry=https://npm.fontawesome.com
//npm.fontawesome.com/:_authToken=1AD3881A-119F-46DC-812D-83204A2B7176
```

.yarnrc.yml

```
npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com
```

This worked when I tested it on your ncu-private-repo.

However, it would be nice if npm-check-updates supported `npmScopes` in the `.yarnrc.yml`. I took a stab at it in v12.2.2-0. Will you try installing `npm-check-updates@next` and let me know if that works?

**Comment by mlegenhausen** [comment]
Does not work for me. Still uses `https://registry.npmjs.org`.

**Comment by mlegenhausen** [comment]
Yes with the `.npmrc` workaround does it work.

**Comment by raineorshine** [comment]
@mlegenhausen Are you using `npmScopes` the same way that  @phyllisstein is? If you could post an anonymized copy of your `.npmrc` and `yarnrc.yml` files I could try to reproduce. Otherwise, I'll need more exact steps to reproduce the issue you're experiencing.

I'm curious if the workaround and the `next` tag worked for @phyllisstein.

**Comment by phyllisstein** [comment]
Thank you for coming up with a solution so quickly! `v12.2.2-0` works a lot better: if a token is hard-coded into `.yarnrc.yml`, `npm-check-updates` detects it and adds the authorization header.

It chokes on the environment variable syntax normally supported by Yarn:

```yml
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: "${FONT_AWESOME_NPM_TOKEN:-}"
    npmRegistryServer: "https://npm.fontawesome.com"
```

That said, I completely forgot about `.npmrc`, somehow, just having become so used to Yarn. If I add my auth details there, I can check for updates without any difficulty, even with the token in the environment:

```
@fortawesome:registry=https://npm.fontawesome.com
//npm.fontawesome.com/:_authToken="${FONT_AWESOME_NPM_TOKEN}"
```

That works fine in `v12.2.1`, and has the additional benefit of keeping Yarn-specific concerns out of your codebase. Thanks for walking me through my facepalm moment, and for your work on this utility in general. 😬

**Comment by mlegenhausen** [comment]
@raineorshine yes my `npmScopes` look like this.

```yml
npmScopes:
  myscope:
    npmRegistryServer: "https://npm.pkg.github.com"
```

The `npmAuthToken` is not included here due to per user login to the github package registry. The `authToken` is stored in the `~/.yarnrc.yml` file.

The content of my `.npmrc` file that gets `ncu` working is as follows:

```
@myscope:registry=https://npm.pkg.github.com
```

For completion this is my `.ncurc.json` as you can see I use `ncu` in a monrepo setup.

```
{
  "packageFile": [
    "./package.json",
    "./packages/*/package.json"
  ],
  "packageManager": "yarn"
}
```

Everything was tested with `npm-check-updates@next`.

For completion, here the error message without the `.npmrc` workaround.

```
404 Not Found - GET https://registry.npmjs.org/@myscope%2fmypackage - Not found.
```

**Comment by raineorshine** [comment]
@phyllisstein 

> It chokes on the environment variable syntax normally supported by Yarn:

I wasn't aware of this feature, but looks helpful. I added support in `npm-check-updates@next` if you'd like to try it out.

> That said, I completely forgot about `.npmrc`, somehow, just having become so used to Yarn. If I add my auth details there, I can check for updates without any difficulty, even with the token in the environment...
> That works fine in `v12.2.1`, and has the additional benefit of keeping Yarn-specific concerns out of your codebase

Yes, I agree, it's beneficial to use `.npmrc` when possible for better compatibility.

@mlegenhausen 

If I'm understanding you correctly, it looks like you just need support for `~/.yarnrc`. I was only looking for `.yarnrc` in the project directory before. I added support for `~/.yarnrc` in `npm-check-updates@next` if you'd like to try it out. Let me know if I'm missing something!

**Comment by mlegenhausen** [comment]
Ok I found the problem the `yarnrcUser` isn't that important for the problem.

The `setNpmScope` function expects `npmAuthToken` AND `npmRegistryServer` which is not always the case.

You need to change:

```ts
/** Reads an NpmScope from a yarn config, interpolates it, and sets it on the npm config. */
    const setNpmScope = ([dep, scopedConfig]) => {
        if (scopedConfig.npmAuthToken && scopedConfig.npmRegistryServer) {
            npmConfig[`@${dep}:registry`] = scopedConfig.npmRegistryServer;
            // interpolate environment variable fallback
            // https://yarnpkg.com/configuration/yarnrc
            npmConfig[`${scopedConfig.npmRegistryServer.replace(/^https?:/, '')}/:_authToken`] = interpolate(scopedConfig.npmAuthToken, process.env);
        }
    }
```

to

```ts
/** Reads an NpmScope from a yarn config, interpolates it, and sets it on the npm config. */
    const setNpmScope = ([dep, scopedConfig]) => {
        if (scopedConfig.npmRegistryServer) {
            npmConfig[`@${dep}:registry`] = scopedConfig.npmRegistryServer;

        }
        if (scopedConfig.npmAuthToken) {
          // interpolate environment variable fallback
          // https://yarnpkg.com/configuration/yarnrc
          npmConfig[`${scopedConfig.npmRegistryServer.replace(/^https?:/, '')}/:_authToken`] = interpolate(scopedConfig.npmAuthToken, process.env);
        }
    };
```

**Comment by raineorshine** [comment]
@mlegenhausen Really appreciate you taking that extra step.

I added a little more logic to properly retrieve `npmRegistryServer` from either the local or user config when setting the auth token config variable. Hopefully that does the job!

Published to `v12.3.0`

**Comment by mlegenhausen** [comment]
@raineorshine Seems to work. Thanks!

**Comment by phyllisstein** [comment]
Thank you again for giving this so much of your attention. I’d probably still be using React 0.12 if not for `ncu`. 🙃
