### ISSUE TITLE
Should allow package manager other than npm and yarn

### ISSUE THREAD

**Issue by garrychnca** [raineorshine/npm-check-updates#1068]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [ ] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 12`

---------------------------

## Steps to Reproduce
1. execute `ncu --packageManager=<some non-npm-yarn manager>`
2. error in console `Error: Invalid package manager: <some non-npm-yarn manager>`

## Current Behavior
An error is thrown indicating non-npm-yarn manager cannot be used.

## Expected Behavior
Should not assume the package manager used by user.

## Justification
A lot of companies develop their own in-house package manager that is compatible with npm.

Lifting the checks in `getPackageManager` for "supported" package manager allows users to use this package with their in-house package manager.

**Comment by garrychnca** [comment]
For example, `lerna` allows package manager other than `npm` and `yarn` for its `bootstrap` command:

```
lerna bootstrap --npm-client=<some non-npm-yarn manager>
```

**Comment by raineorshine** [comment]
Is lerna a drop-in replacement for npm? If so, we can do as you suggest. Otherwise, we need to parse and normalize the response from the custom package manager.

**Comment by garrychnca** [comment]
Yes, a drop-in replacement of npm.

**Comment by garrychnca** [comment]
And probably, when a non-npm-yarn package manager is specified, we can log a info saying using a package manager that is not compatible with npm (ie. not a drop-in npm replacement) can cause unexpected behaviour.

**Comment by raineorshine** [comment]
Thinking about this more...

In normal usage, `npm-check-updates` doesn't actually use `npm`. It uses https://github.com/npm/pacote to access the npm registry directly. You can change the registry with `--registry`. Is this your use case?

In global mode, `npm-check-updates` does have a dependency on `npm list`, which could be universalized to allow npm replacements.

**Comment by garrychnca** [comment]
Interesting, so I should use `--registry` to override to use internal drop-in registry replacement instead.

I will close this issue then. Thanks!

**Comment by chj-damon** [comment]
is there any way I can do to specifiy packageManager? like I use pnpm in my project

**Comment by raineorshine** [comment]
@chj-damon npm-check-updates works with pnpm without any special options. npm-check-updates reads and modifies your package.json and makes requests to the npm registry. pnpm uses the same package.json and registry as npm.
