### ISSUE TITLE
Wrong NPM package is checked (NPM is installed using Volta)

### ISSUE THREAD

**Issue by Ky6uk** [raineorshine/npm-check-updates#1072]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 12`

---------------------------

> Not sure it's really a bug, can be also a feature request. Because Volta is using a kind of shims/executable proxy for managing installed tools.

In case Node.js/NPM are managing using [Volta](https://volta.sh/), `ncu -g` is checking the wrong NPM package.

## Steps to Reproduce
```
~$ volta install npm

~$ npm -v
8.5.5

~$ ncu -g
npm  8.3.1  →  8.5.5

~$ npm -g install npm@8.5.5

~$ npm -v
8.5.5

~$ ncu -g
npm  8.3.1  →  8.5.5
```

## Current Behavior

`ncu -g` checks an incorrect version of the NPM package. I guess it's system installed version of NPM.

## Expected Behavior

`ncu -g` checks the correct NPM package.

**Comment by ivancuric** [comment]
Similar issue here:

```
➜ npm -g prefix
/Users/ivan/.volta/tools/image/node/16.15.0
```

```
➜ npm -v
8.10.0
```
```
➜ which npm
/Users/ivan/.volta/bin/npm
```

```
➜ volta list
⚡️ Currently active tools:

    Node: v16.15.0 (default)
    npm: v8.10.0 (default)
    Tool binaries available:
        npkill (default)
        npm-check-updates, ncu (default)
        serve (default)
```

```
➜ volta list npm
⚡️ Custom npm versions in your toolchain:

    v8.10.0 (default)
```

```
➜ ncu -g
[====================] 2/2 100%

 npm  8.5.5  →  8.10.0

ncu itself cannot upgrade global packages. Run the following to upgrade all global packages:

npm -g install npm@8.10.0
```

**Comment by srmagura** [comment]
Taking a look at this and will try to fix it!

**Comment by raineorshine** [comment]
#1117:

> I discovered that Volta has its own fancy system for installing global packages, and that this results in `npm ls -g` returning inaccurate / incomplete results. In particular, `npm ls -g` will typically show a different version of npm than what has been installed by Volta.
> 
> I don't think npm-check-updates should be expected to work in cases where even npm itself does not know what packages are installed. So I've added a check that aborts the program if Volta is installed. Volta has its own CLI for managing globally-installed tools, so Volta users can just use that rather than npm-check-updates.
