### ISSUE TITLE
`Unknown option` due to parsed `.ncurc`

### ISSUE THREAD

**Issue by GeoffreyBooth** [raineorshine/npm-check-updates#1085]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 12`

---------------------------

## Steps to Reproduce

1. Create a file `~/.ncurc` with contents:

```
{
  "username": "me",
  "token": "secret",
  "jenkins_token": "secret"
}
```

2. Run `npm-check-updates`

## Current Behavior

`error: unknown option '--username'`

## Expected Behavior

Runs without error.

## Explanation

I use the global command-line tool https://github.com/nodejs/node-core-utils, which stores its configuration in `~/.ncurc`—the same path that `npm-check-updates` stores _its_ configuration. The above snippet is a sanitized version of my `node-core-utils` configuration. It’s unfortunate that both projects have chosen the same filename to store configuration information in 😄 

Per https://github.com/raineorshine/npm-check-updates/blob/c74dff8bb1946056cdafd611de506d4eb7d74f5f/src/bin/cli.ts#L71, as a workaround I can run via `NCU_TESTS=1 npm-check-updates` and `npm-check-updates` will skip trying to load its configuration file.

I’m not sure what the best long-term solution is. Perhaps just ignore unknown config file settings rather than erroring on them? At the very least, the error message should explain that the `username` option it’s erroring on came from `~/.ncurc`; since I didn’t pass any arguments at all, an error complaining about `--username` feels like a bug.

Possibly related: https://github.com/raineorshine/npm-check-updates/issues/960

**Comment by raineorshine** [comment]
Thanks for the thorough explanation.

> I use the global command-line tool [nodejs/node-core-utils](https://github.com/nodejs/node-core-utils), which stores its configuration in `~/.ncurc`—the same path that `npm-check-updates` stores _its_ configuration.

As far as I know, npm-check-updates doesn't check for a config file in the home directory. Are you running `ncu` in your home directory? Just trying to understand how it's reading that file. I briefly looked through the code in npm-check-updates and https://github.com/azu/rc-config-loader, and didn't see anything that was reading from the home directory explicitly.

If you haven't already, try setting `--configFileName` or `--configFilePath` so that npm-check-updates looks for a different file. You may have to provide a dummy config file.

> At the very least, the error message should explain that the `username` option it’s erroring on came from `~/.ncurc`; since I didn’t pass any arguments at all, an error complaining about `--username` feels like a bug.

I agree that's confusing. I'll improve the error messaging.

**Comment by GeoffreyBooth** [comment]
> As far as I know, npm-check-updates doesn’t check for a config file in the home directory. Rather, it checks in the project directory where `ncu` is executed.

It apparently checks the current folder and then searches upward:

```shell
~ ▶ cd ~/Sites
~/Sites ▶ mkdir test-ncu
~/Sites ▶ cd test-ncu
~/Sites/test-ncu ▶ npm init -y
Wrote to /Users/Geoffrey/Sites/test-ncu/package.json:

{
  "name": "test-ncu",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


~/Sites/test-ncu ▶ ncu
error: unknown option '--username'
~/Sites/test-ncu ▶ cd ..
~/Sites ▶ mv test-ncu /tmp
~/Sites ▶ cd /tmp/test-ncu
/tmp/test-ncu ▶ ncu
Checking /private/tmp/test-ncu/package.json

No dependencies.
```

Since I have all my projects under `~/Sites`, which is under my home folder, my home folder gets searched while going up the tree to the root of the volume.

**Comment by raineorshine** [comment]
> It apparently checks the current folder and then searches upward:

Thanks, I somehow missed that. 

> If you haven't already, try setting --configFileName or --configFilePath so that npm-check-updates looks for a different file. You may have to provide a dummy config file.

How did this work out?

**Comment by GeoffreyBooth** [comment]
> How did this work out?

`ncu --configFilePath /` works, as I guess it starts at the root and has nowhere else upward to search.

```shell

~/Sites/test ▶ ncu
Unknown options found in rc file: username, token, jenkins_token
error: unknown option '--username'

~/Sites/test ▶ ncu --configFileName
error: option '--configFileName <filename>' argument missing

~/Sites/test ▶ ncu --configFileName ''
Unknown options found in rc file: username, token, jenkins_token
error: unknown option '--username'

~/Sites/test ▶ touch .ncurc

~/Sites/test ▶ ncu --configFileName ./.ncurc
Checking /Users/Geoffrey/Sites/test/package.json
[====================] 11/11 100%

All dependencies match the latest package versions :)

~/Sites/test ▶ ncu --configFilePath .
Unknown options found in rc file: username, token, jenkins_token
error: unknown option '--username'

~/Sites/test ▶ ncu --configFilePath /
Checking /Users/Geoffrey/Sites/test/package.json
[====================] 11/11 100%

All dependencies match the latest package versions :)
```

**Comment by raineorshine** [comment]
Great! Maybe the simplest solution would be to alias `ncu` to `ncu --configFilePath /`.

**Comment by GeoffreyBooth** [comment]
> Great! Maybe the simplest solution would be to alias `ncu` to `ncu --configFilePath /`.

Well that could solve it for my machine, but it wouldn’t help anyone else with this issue.

Perhaps npm-check-updates could simply ignore any options it doesn’t recognize? Then as long as npm-check-updates and node-core-utils never choose the same name for an option, they won’t conflict.

If that’s too risky for you, perhaps a command-line option like `--ignoreConfigFile` that would tell npm-check-updates to not try to load any rc file, and then the `Unknown options found in rc file` error could be followed by text like `Run with --ignoreConfigFile to skip trying to load this file`.

**Comment by raineorshine** [comment]
I don't really see a better solution at the moment.

> Perhaps npm-check-updates could simply ignore any options it doesn’t recognize? Then as long as npm-check-updates and node-core-utils never choose the same name for an option, they won’t conflict.

If a user misspells an option, I think it's important to let them know. Silent errors are usually not a good idea. Also I think the risk of overlap on future options is a bit too fragile.

> If that’s too risky for you, perhaps a command-line option like `--ignoreConfigFile` that would tell npm-check-updates to not try to load any rc file, and then the `Unknown options found in rc file` error could be followed by text like `Run with --ignoreConfigFile to skip trying to load this file`.

Isn't that the same as `--configFilePath /`?

**Comment by GeoffreyBooth** [comment]
> Isn’t that the same as `--configFilePath /`?

If the user doesn’t have a `/.ncurc` file, yes. The more important part (to me) was that we’re telling the user how to solve their problem, other than by deleting or editing the config file and breaking the other tool.

**Comment by raineorshine** [comment]
Fair enough. My personal preference is to avoid extending the surface area of the API unnecessarily for a conflict that a small number of users will experience. `--configFilePath /` or `--configFilePath /dev/null` seems reasonable to me. I agree the most important thing is that users have a workaround for the issue. Thanks!
