### ISSUE TITLE
pinned versions shouldn't be updated

### ISSUE THREAD

**Issue by eng-dibo** [raineorshine/npm-check-updates#1102]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 12`

for the following dependency example
```
 "dependencies": {
    "strip-json-comments": "3.1.1",
  },
```

`strip-json-comments` is pinned to `v3.1.1`, upgrading it to `v4.x.x` breaks the application as it migraded to ESM without back-compatibility for commonjs modules

**Comment by raineorshine** [comment]
This is intentional, and is indeed the primary purpose of `npm-check-updates`. From the first line of the README:

> **npm-check-updates upgrades your package.json dependencies to the latest versions, ignoring specified versions.**

For updates that respect the version in your package, use `npm update`.

**Comment by ath0mas** [comment]
Maybe use `--target minor` with correct `--filter` or `--reject`, to stay at a _minor_ level, and not _major_, for specific dependencies.

**Comment by raineorshine** [comment]
> Maybe use `--target minor` with correct `--filter` or `--reject`, to stay at a _minor_ level, and not _major_, for specific dependencies.

Exactly :). You can also do this in a `.ncurc.json` file in your project:

```json
{
  reject: 'strip-json-comments'
}
```

Or even define a custom `target` function in a `.ncurc.js` file:

```js
module.exports = {

  /** Custom target.
    @param dependencyName The name of the dependency.
    @param parsedVersion A parsed Semver object from semver-utils.
      (See https://git.coolaj86.com/coolaj86/semver-utils.js#semverutils-parse-semverstring)
    @returns One of the valid target values (specified in the table above).
  */
  target: (dependencyName, [{ operator }]) => {
    if (!operator) return 'minor'
    return 'latest'
  }
}

```

**Comment by eng-dibo** [comment]
> Maybe use `--target minor` with correct `--filter` or `--reject`, to stay at a _minor_ level, and not _major_, for specific dependencies.

how to target specific packages to minor, and other to patch?

**Comment by ath0mas** [comment]
> > Maybe use `--target minor` with correct `--filter` or `--reject`, to stay at a _minor_ level, and not _major_, for specific dependencies.
> 
> how to target specific packages to minor, and other to patch?

It depends how you use _ncu_, cli or script, configuration file, unique or multiple "settings", ...

> Or even define a custom target function in a .ncurc.js file:
Solution from @raineorshine seems nice to start

**Comment by ath0mas** [comment]
(@raineorshine `defining a custom target function` should be documented please)

**Comment by raineorshine** [comment]
It's documented in the help: `ncu --help --target`.
