### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by memelet** [raineorshine/npm-check-updates#1121]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 12`

---------------------------

## Steps to Reproduce
```
$ nvm use 
Now using node v12.16.1 (npm v6.14.8)

$ npm-check-updates
 npm-check-updates
~/.nvm/versions/node/v12.16.1/lib/node_modules/npm-check-updates/node_modules/yaml/dist/compose/composer.js:33
                if (prelude[i + 1]?.[0] !== '#')
                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/bkaplan/.nvm/versions/node/v12.16.1/lib/node_modules/npm-check-updates/node_modules/yaml/dist/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

## Expected Behavior

It was running correctly until I updated to the latest version. (Not sure what the old version was). 

I have 
- deleted package-lock.json
- delete node_modules
- commented out all dependencies from package.json

But its failing on all our projects, not just this one.

Not sure what else I can try.

**Comment by memelet** [comment]
I bumped node to 14.15.4 and how I get a completely different error
```
❯ npm-check-updates          
Using config file /Users/bkaplan/si/eslint-config-vi-node/.ncurc.json
Checking /Users/bkaplan/si/eslint-config-vi-node/package.json
[--------------------] 0/18 0%
FetchError: Request babel-eslint info failed[1 of 3]: 
Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager".

FetchError: Request babel-preset-vi-node info failed[1 of 3]: 
Unable to authenticate, need: BASIC realm="Sonatype Nexus Repository Manager".
...
```

I don't have problems accessing nexus via `npm i`

**Comment by memelet** [comment]
And now I went back to node 12.16.1 and I still have the auth error, not the `Unexpected token`. So this is not even repeatable...

**Comment by raineorshine** [comment]
`npm-check-updates` requires node `v14` or greater. Note that node `v12` is [no longer in LTS](https://nodejs.org/en/about/releases/).

As for the auth error, make sure that your auth is specified correctly in your .npmrc. Some older formats no longer work:

```
registry=https://example.jfrog.io/example/api/npm/
//example.jfrog.io/example/api/npm/:_auth=example
//example.jfrog.io/example/api/npm/:email=example@example.com
//example.jfrog.io/example/api/npm/:always-auth=true
```

See: https://github.com/raineorshine/npm-check-updates/issues/1022#issuecomment-1003723285

**Comment by memelet** [comment]
Thanks @raineorshine. I see your comments about this in other issues, but I think I don't quite follow. 

I changed the .npmrc format to what you showed. `npm i` with node 16.5.0 works, but `npm-check-updates` still gives the same auth errors from my above.

**Comment by memelet** [comment]
Hmm, I used `npm login`, it updated the .npmrc a bit (added `_authToken`). Now npm-check-upgrades works. 

I'll have to check to see if that token will expire...

**Comment by memelet** [comment]
Not an npm-check-updates issue

**Comment by raineorshine** [comment]
Glad you figured it out!
