### ISSUE TITLE
Upgrade major only

### ISSUE THREAD

**Issue by ilyub** [raineorshine/npm-check-updates#1123]
---

## Steps to Reproduce

1. Try to upgrade "npm-check-updates^13.0.0" with "--minimal" option. Ncu will leave it as is (current ncu version is 13.0.3). So, the end result is v13.0.0.
2. Now try to upgrade "npm-check-updates^12.0.0" with "--minimal" option. Ncu will upgrade it to 13.0.3. So, the end result is v13.0.3.

## Current Behavior

The end result is different depending on the initial state. You can get either ^13.0.0 or ^13.0.3.

## Expected Behavior

I would expect that NCU would upgrade ^12.0.0 to ^13.0.0, because "^13.0.0" is the minimal version for package.json that would allow to have latest version (13.0.3) to be installed inside node_modules.

If changing --minimal behavior is not desired then is it possible to at least add additional option that would allow what I described:
Upgrade to ^13.0.0 instead of ^13.0.3?

**Comment by raineorshine** [comment]
Thanks for reporting. The `--minimal` option is a little different than your expected case. From the help:

```
Usage: ncu --minimal
       ncu -m

Do not upgrade newer versions that are already satisfied by the version range according to semver.
```

In other words, when `--minimal` is set, it does not change the target version, but rather it skips the upgrade if it is already satisfied by the semver version range.

> If changing --minimal behavior is not desired then is it possible to at least add additional option that would allow what I described:
> Upgrade to ^13.0.0 instead of ^13.0.3?

What is the motivating use case for this? They would both resolve to `13.03` after an `npm install`.

**Comment by ilyub** [comment]
Thx for response.

> What is the motivating use case for this?

When I have a library (i.e. a package that is being by another package or a project) I prefer to have ^13.0.0 dependency instead of ^13.0.3 or ^13.3.0 because it makes my library more compatible with other libraries = it helps in avoiding dependency resolution conflicts:

Parent project:
  Library A (my library):
    npm-check-updates: "^13.3.0"
  Library B (not my library): 
    npm-check-updates: "~13.2.0"
This creates dependency resolution conflict.

Parent project:
  Library A (my library):
    npm-check-updates: "^13.0.0"
  Library B (not my library): 
    npm-check-updates: "~13.2.0"
This is OK.

So, I do want ncu to upgrade from ^12.x.x to ^13.x.x because I want to use latest version.
But I prefer it to upgrade to ^13.0.0 instead of ^13.0.3 or 13.3.0 to avoid possible conflicts.

This is my use case.

**Comment by raineorshine** [comment]
I would have assumed that npm would install the appropriate version for each dependency. But if it only installs one version, that would be a problem.

I am not actively adding new features myself, but I am open to PR's.

**Comment by ilyub** [comment]
I found simpler solution: just use "^3" instead of "^3.2.1".
So, closing  this issue.
