### ISSUE TITLE
Feature Request - Add support for Pnpm

### ISSUE THREAD

**Issue by Alex289** [raineorshine/npm-check-updates#1124]
# Feature Request - Add support for Pnpm

I use ncu everyday and wanted to switch to [Pnpm](https://pnpm.io/). I would love to get it supported.

**Comment by raineorshine** [comment]
As far as I know, `npm-check-updates` is fully compatible with pnpm. `ncu` only interacts with `package.json` and the npm registry, not the npm lock file or node_modules.

**Comment by Alex289** [comment]
Oh yes? I never checked what ncu changed 😅. Well then thanks a lot. Ncu is awesome
