### ISSUE TITLE
Feature Request: Print all updates available first option together with interactive mode

### ISSUE THREAD

**Issue by fix-me** [raineorshine/npm-check-updates#1131]
It would be nice to have the same output in **interactive mode** as it is in normal mode. So one could first see a list of all updates available before being asked for each package to update. I am thinking of an **aditional print option that works together with interactive mode**. This would make it easier to overview @types/\<dep\> and \<dep\> and identify other side effects before the agreements.

**Comment by raineorshine** [comment]
That's a great suggestion, and I imagine you're not the only one to want all the information up front.

Given that all the latest versions have already been fetched by the time the prompts begin, there's no reason not to show the list of upgrades first.

I have made the change as the new default and published it in `v13.1.2`.

**Comment by fix-me** [comment]
thank you! <3
