### ISSUE TITLE
When running ncu inside a package from npm-scripts .yarnrc / .npmrc, false boolean values are treated as ""

### ISSUE THREAD

**Issue by IMalyugin** [raineorshine/npm-check-updates#1132]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14`

---

## Steps to Reproduce
1. `yarn install npm-check-updates -D` to install package locally
2. Create .yarnrc with the following options:
2.1. `"strict-ssl" false`
2.2. registry "path-to-registry-with-self-signed-cert" (typical scenario for companies behind corporate proxy)
3. Add npm-script `"updates": "ncu"` to package.json
4. Call `yarn updates` 

## Current Behavior
Unable to verify first certificate in chain

## Expected Behavior
Working properly

Instead of steps 2.2, it is enough to just read npmConfig contents within src/package-managers/npm.ts.
It says "strict-ssl" ""

Wrapping false in quotes inside .yarnrc:
`"strict-ssl" "false"`
Fixes the bug, but that is incorrect syntax and every other tool stops working.

When calling globally - everything works fine. Version matches, tried rolling back to ^12.x.x - the result is the same.

Could try putting out a PR for this

**Comment by IMalyugin** [comment]
Guess the reason lies within the way process.env contains boolean flags (could be yarn related).
```
| .yarnrc              | npm_config_strict_ssl |
| "strict-ssl" "false" | "false"               |
| "strict-ssl" false   | ""                    |
| "strict-ssl" true    | "true"                |
```

Basically true is parsed properly, but false is converted to "", which is what we should crutch-support within ncu.

**Comment by raineorshine** [comment]
Thanks for reporting! Would love a PR for this. npm config and registry settings are read in https://github.com/raineorshine/npm-check-updates/blob/main/src/package-managers/npm.ts.

**Comment by IMalyugin** [comment]
It is actually 2 symbol fix, got PR up and ready :)
