### ISSUE TITLE
Exit code when global package has updates

### ISSUE THREAD

**Issue by igorepst** [raineorshine/npm-check-updates#1135]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X] I am using the latest version of `npm-check-updates`
- [X] I am using `node >= 14`
---
## Steps to Reproduce
On Ubuntu 20.04, node v16.15.1, npm-check-updates 13.1.1 +  ArchLinux, node v18-something..., same npm-check-updates
## Current Behavior
    ncu -gs -e 2 npm-check-updates
    echo $? # 0
    npm i -g npm-check-updates # updates from 13.1.1 to 13.1.3
## Expected Behavior
I would expect the `ncu` to return non zero exit code as described in the docs, given that there is an update, to be able to automate the updates.
Thank you

**Comment by raineorshine** [comment]
Thanks for reporting! I'm not sure how that slipped through.

Fixed and published in `v13.1.4`.

**Comment by igorepst** [comment]
Thank you :) Works properly
