### ISSUE TITLE
Feature Request: Updates based on static manifest

### ISSUE THREAD

**Issue by agrouse** [raineorshine/npm-check-updates#1139]
Would it be possible to run NCU against a list of dependencies with their specified versions in place of a registry? I'm working on a frameworks team that could use NCU to govern our client team's applications. Here is an example of a specific use case: our framework can only guarantee pkg@1.6.3 without breaking their application. If a a team that uses our framework has their pkg at version 1.5.9, for example, we'd like them to be able to update to 1.6.3. However, if the latest in the registry is pkg@1.7.0, NCU updates pkg to a version that surpasses what we recommend. If there was a static manifest file of dependencies with their recommended version, we'd ideally like to run NCU against this list instead of what would be the latest in the registry. If this is a viable feature request, I'm open to doing some open source work.

**Comment by raineorshine** [comment]
This is an interesting use case, thanks for posting. 

Actually, this would be quite easy with a small PR. 

The [PackageManager](https://github.com/raineorshine/npm-check-updates/blob/main/src/types/PackageManager.ts) interface defines the API for interacting with the npm registry. Currently it supports npm and yarn, but a custom "package manager" could be defined that returns versions from a static list. In fact, `latest` is the only method that is strictly required. 

Here is a simple `PackageManager` implementation that returns versions from a static list. It only accept the default target of `latest`, but it works. npm-check-updates will handle all comparisons and output formatting. 

```ts
const registry = {
  'package-a': '2.1.0',
  'package-b': '4.0.6',
  'package-c': '0.1.0'
}

export const staticRegistry = {
  latest: (packageName: string, currentVersion: Version, options?: Options) => Promise.resolve(registry[packageName] || null)
}
``` 

And to run:

``` 
ncu --packageManager staticRegistry
``` 

You could also easily fetch the static list of versions from a server or URL.

**Comment by raineorshine** [comment]
This is an interesting use case, thanks for posting. 

Actually, this would be quite easy with a small PR. 

The [PackageManager](https://github.com/raineorshine/npm-check-updates/blob/main/src/types/PackageManager.ts) interface defines the API for interacting with the npm registry. Currently it supports npm and yarn, but a custom "package manager" could be defined that returns versions from a static list. In fact, `latest` is the only method that is strictly required. 

Here is a simple `PackageManager` implementation that returns versions from a static list. It only accept the default target of `latest`, but it works. npm-check-updates will handle all comparisons and output formatting. 

```ts
const registry = {
  'package-a': '2.1.0',
  'package-b': '4.0.6',
  'package-c': '0.1.0'
}

export const staticRegistry = {
  latest: (packageName: string, currentVersion: Version, options?: Options) => Promise.resolve(registry[packageName] || null)
}
``` 

And to run:

``` 
ncu --packageManager staticRegistry
``` 

You could also easily fetch the static list of versions from a server or URL.

**Comment by agrouse** [comment]
This is great to hear! I'll go ahead, fork your repo and make a PR.

**Comment by raineorshine** [comment]
Yes, that seems like a good place for it.
