### ISSUE TITLE
Error: EACCES: permission denied in version 14.1.0

### ISSUE THREAD

**Issue by LabEG** [raineorshine/npm-check-updates#1146]
- [+] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [+] I am using the latest version of `npm-check-updates`
- [+] I am using `node >= 14`

---

## Steps to Reproduce
Install ncu in docker container:
As here: https://github.com/LabEG/devpc/blob/master/Dockerfile#L21

Log result is here:
```
#5 89.77 npm notice 
#5 89.77 npm notice New minor version of npm available! 8.12.1 -> 8.13.0
#5 89.77 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.13.0>
#5 89.77 npm notice Run `npm install -g npm@8.13.0` to update!
#5 89.77 npm notice 
#5 89.77 npm ERR! code 243
#5 89.78 npm ERR! git dep preparation failed
#5 89.78 npm ERR! command /usr/bin/node /usr/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/headless/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
#5 89.78 npm ERR! npm WARN using --force Recommended protections disabled.
#5 89.78 npm ERR! npm ERR! code EACCES
#5 89.78 npm ERR! npm ERR! syscall symlink
#5 89.78 npm ERR! npm ERR! path ../../../../home/headless/.npm/_cacache/tmp/git-cloneu5Cd60
#5 89.78 npm ERR! npm ERR! dest /usr/local/lib/node_modules/prompts
#5 89.78 npm ERR! npm ERR! errno -13
#5 89.78 npm ERR! npm ERR! Error: EACCES: permission denied, symlink '../../../../home/headless/.npm/_cacache/tmp/git-cloneu5Cd60' -> '/usr/local/lib/node_modules/prompts'
#5 89.78 npm ERR! npm ERR!  [Error: EACCES: permission denied, symlink '../../../../home/headless/.npm/_cacache/tmp/git-cloneu5Cd60' -> '/usr/local/lib/node_modules/prompts'] {
#5 89.78 npm ERR! npm ERR!   errno: -13,
#5 89.78 npm ERR! npm ERR!   code: 'EACCES',
#5 89.78 npm ERR! npm ERR!   syscall: 'symlink',
#5 89.78 npm ERR! npm ERR!   path: '../../../../home/headless/.npm/_cacache/tmp/git-cloneu5Cd60',
#5 89.78 npm ERR! npm ERR!   dest: '/usr/local/lib/node_modules/prompts'
#5 89.78 npm ERR! npm ERR! }
#5 89.78 npm ERR! npm ERR! 
#5 89.78 npm ERR! npm ERR! The operation was rejected by your operating system.
#5 89.78 npm ERR! npm ERR! It is likely you do not have the permissions to access this file as the current user
#5 89.78 npm ERR! npm ERR! 
#5 89.78 npm ERR! npm ERR! If you believe this might be a permissions issue, please double-check the
#5 89.78 npm ERR! npm ERR! permissions of the file and its containing directories, or try running
#5 89.78 npm ERR! npm ERR! the command again as root/Administrator.
#5 89.78 npm ERR! 
#5 89.78 npm ERR! npm ERR! A complete log of this run can be found in:
#5 89.78 npm ERR! npm ERR!     /home/headless/.npm/_logs/2022-06-23T19_24_23_811Z-debug-0.log
#5 89.78 
#5 89.78 npm ERR! A complete log of this run can be found in:
#5 89.78 npm ERR!     /home/headless/.npm/_logs/2022-06-23T19_24_13_825Z-debug-0.log
```

Problem in: https://github.com/raineorshine/npm-check-updates/blob/main/package.json#L76

Linux security system block this type of dependecies.

## Current Behavior
Global install in docker - fatal error.

## Expected Behavior
Global install in docker correctly.

**Comment by raineorshine** [comment]
Hi, thanks for reporting.

As you've seen, npm-check-updates `v14.1.0` uses a custom version of `prompts` which is located at https://github.com/raineorshine/prompts/tree/ncu

I'm not sure why Docker fails to load the dependency from github, as it appears to [work across multiple platforms](https://github.com/raineorshine/npm-check-updates/actions/runs/2550518266). Linux security system is not blocking this dependency in the tests.

That said, there's no reason I can't publish the custom `prompts` to npm if that is easier on the security policy of your machine.

**Comment by LabEG** [comment]
Yeз, I think publishing `prompts` artifact in npm would be the best way. More stable and secure than linking to a dynamic repository.

I think the Linux security system is blocking because the installation is from root. But this is standard practice when preparing a dockerfile. You can try it yourself if you build the dockerfile from the first link.

**Comment by raineorshine** [comment]
Try `v14.1.1`

**Comment by Jason3S** [comment]
@raineorshine,

v14.1.0 would silently fail using `npx`:
`npx npm-check-updates@14.1.0 -t minor -u || echo error`
`error`

v14.1.1 seems to have fixed it.
