### ISSUE TITLE
package-json dependency need to be updated due to moderate severity vulnerabilities warnings

### ISSUE THREAD

**Issue by deejaybill** [raineorshine/npm-check-updates#1149]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X] I am using the latest version of `npm-check-updates`
- [X] I am using `node >= 14`

---

## Steps to Reproduce

npm i -D npm-check-updates
npm audit

`5 moderate severity vulnerabilities`

Steps:

### npm audit report

got  <11.8.5
Severity: moderate
Got allows a redirect to a UNIX socket - https://github.com/advisories/GHSA-pfrx-2q88-qq97
**fix available via `npm audit fix --force`**
**Will install npm-check-updates@2.2.3, which is a breaking change**
node_modules/package-json/node_modules/got
  package-json  <=6.5.0
  Depends on vulnerable versions of got
  node_modules/package-json
    latest-version  0.2.0 - 5.1.0
    Depends on vulnerable versions of package-json
    node_modules/latest-version
      update-notifier  0.2.0 - 5.1.0
      Depends on vulnerable versions of latest-version
      node_modules/update-notifier
        npm-check-updates  >=2.2.4
        Depends on vulnerable versions of update-notifier
        node_modules/npm-check-updates

**Comment by raineorshine** [comment]
Hi, thanks for reporting.

This issue has been analyzed and determined not to be a vulnerability in npm-check-updates. We can't update to `update-notifier` v6 anyway because it forces pure ESM. See the full explanation in #1145.
