### ISSUE TITLE
Feature Request: Configure list of non-semver packages

### ISSUE THREAD

**Issue by CreativeTechGuy** [raineorshine/npm-check-updates#1152]
As you probably know, there's some major packages which don't follow semver. (TypeScript being the most notable.) With the new `--format group` option, it seems like it'd be very useful to be able to customize via the `.ncurc.js` file a list of packages which don't follow semver.

Proposals:

* Easy: A list of packages and any time any version change is done to those packages, it is considered breaking by default. Probably overly aggressive but simplest to configure and implement.
* Advanced: A map of package names to semver patterns. So for TypeScript it could be `"typescript": "X.X.Z"` Unsure of the format pattern, but some way to indicate the pattern that the particular library uses for Major (X), Minor (Y), Patch (Z) which then ncu can use to categorize it correctly. This seems like a much bigger task so I'm not advocating for it, but just throwing it out for completeness.

A side benefit to this is that this feature can be used to highlight important packages. I know some libraries I really want to know whenever they update regardless of semver. If we want this feature to be usable for this purpose, we can rebrand it to "flagPackages" (name pending) so it can be used for any reason that someone might want to highlight when a package has been updated (either because it doesn't use semver, or because they just want to not miss an update). This would require no extra work, just renaming.

If accepted, I'm happy to contribute this feature.

**Comment by raineorshine** [comment]
Hi, thanks for the suggestion. Sounds like it could be useful. 

How would you know if a package followed semver or not? For example, all of `typescript`'s published tags appear to follow semver:

```js
{
  latest: '4.7.4',
  next: '4.8.0-dev.20220630',
  beta: '4.8.0-beta',
  rc: '4.7.1-rc',
  insiders: '4.6.2-insiders.20220225',
  'tag-for-publishing-older-releases': '4.1.6',
  dev: '3.9.4'
}
```

**Comment by CreativeTechGuy** [comment]
It's just something you kind of have to "know". There's not a way to tell from looking at their tags.

Here's the lead of TypeScript's development comment on the matter: https://github.com/microsoft/TypeScript/issues/14116#issuecomment-280592571

But you can also tell because of how they announce new releases. It's always 3.9 -> 4.0 -> 4.1 and each of those have breaking changes. They are just incrementing a two digit number.

It's weird, but some libraries come up with their own versioning system which is non-standard but are widely used enough that it'd be nice to have a way to handle them.

**Comment by raineorshine** [comment]
> It's just something you kind of have to "know". There's not a way to tell from looking at their tags.

That is unfortunate. If it can't be autodetected, it has to be user configurable.

> But you can also tell because of how they announce new releases. It's always 3.9 -> 4.0 -> 4.1 and each of those have breaking changes. They are just incrementing a two digit number.

Yes, we really should be including Typescript minor updates in the "Breaking" category. Or least allow users to opt-in to that behavior. It would be hard to explain in the UI why one package is following a different rule than all the others without breaking ncu's minimalist design principle.

> It's weird, but some libraries come up with their own versioning system which is non-standard but are widely used enough that it'd be nice to have a way to handle them.

Can you provide some additional examples? I don't want to generalize the feature based on one data point (Typescript).

Or we can only implement a fix for Typescript and then expand support later if there is demand.

> A side benefit to this is that this feature can be used to highlight important packages. I know some libraries I really want to know whenever they update regardless of semver. If we want this feature to be usable for this purpose, we can rebrand it to "flagPackages" (name pending) so it can be used for any reason that someone might want to highlight when a package has been updated (either because it doesn't use semver, or because they just want to not miss an update). This would require no extra work, just renaming.

I think the way I would do it is add a `group` option that allows users to specify a categorizing function in their .ncurc:

```js
module.exports = {
  group: (name, currentVersion, upgradedVersion, defaultGroup) =>
    name === 'some_important_lib' ? 'IMPORTANT' : defaultGroup
}
```

I should mention two other ways to achieve this:

1. Create your own groups with shell:
  
  ```sh
  echo "\nIMPORTANT\n" ; ncu typescript ; echo "\nOTHER\n" ; ncu -x typescript
  ```

2. Use ncu's well-supported API to parse the output and produce your own results table.

Sometimes the best solution is to build a wrapper and avoid adding complexity to the main library.

**Comment by CreativeTechGuy** [comment]
Oh in case it wasn't clear, I am not suggesting that NCU does anything special for TypeScript. Just to give a new config option for users to add whatever packages they happen to use that don't follow semver. (Or that they want special handling for some other reason)

I cannot remember the name of it right now, but I've seen libraries which are extensions/plugins match major versions with that main library and therefore not follow semver. (eg: Jest extensions will match Jest's major). It's not common, but does happen.

I like the `group` config you mention, it's possibly more power than most people would need, but would definitely handle a ton of cases that we haven't even considered. If we are voting, I'd vote for that! :)

**Comment by CreativeTechGuy** [comment]
Sure!

As I was just going through and doing a dependency update at work, I realized there's many packages which I don't care about ever because they are always tied to something else. For example, a `@types` package will be upgraded in tandem with the functional package it goes along with. Odds are you don't care about new versions of type packages. And other packages are peers which always need to be updated but the changes to that one don't affect the end user (eg: `@typescript-eslint/parser` with `@typescript-eslint/eslint-plugin`). Do you think this `group` config should enable you to return `null` or something to indicate that the package should be excluded from the output but still be updated?

Do you see a problem with a function as a config value? That'll mean that it'll have to be a `.ncurc.js` file (no other file type and no CLI)

**Comment by raineorshine** [comment]
> Do you think this `group` config should enable you to return `null` or something to indicate that the package should be excluded from the output but still be updated?

A better approach would be to run `ncu` twice: Once for the visible packages, and once with `--silent` for the packages you want to hide. I would prefer not to build into npm-check-updates the functionality to update but hide packages from the output. That is a basic design invariant. What You See Is What Is Upgraded.

> Do you see a problem with a function as a config value? That'll mean that it'll have to be a `.ncurc.js` file (no other file type and no CLI)

We already use functions as config values for the `target`, `filter`, and `reject` options. It is slightly more complex and less declarative than a simple string or array of values. However it is much more flexible. In addition to the `.ncurc.js`, a config function can also be provided programmatically through the module API.

The reason I prefer a config function here is that a simple declarative scheme that covers many cases is not obvious to me. The `X.X.Y` format you proposed works for Typescript, but without more data points (i.e. packages that don't follow semver), it is not clear how well it generalizes. Also, it is a custom pattern that people need to learn, and it is hard to debug. A function provides an explicit relationship between input and output that is highly customizable and observable.

**Comment by CreativeTechGuy** [comment]
I think we might be close. Just published a PR based on the conversation above and it seems pretty good. I really wanted to send the function SemVer objects instead of strings but I couldn't find a reliable way to parse version ranges into SemVer without either losing some data (like prerelease tags) or failing entirely and returning null. I think if this is treated as a power-user feature, making them parse it themselves isn't too bad.
