### ISSUE TITLE
pnpm + suggestion

### ISSUE THREAD

**Issue by dougg0k** [raineorshine/npm-check-updates#1159]
Hi, 

Even though I am using pnpm in the project, when I use the command to upgrade versions `ncu -u --removeRange`, what it suggests are the command to `npm install`, maybe it should be `pnpm install` instead.

A nice feature would be, if an additional flag would make it run the install command together, meaning the one that is being used based on the lock file.

Thanks

**Comment by raineorshine** [comment]
I implemented the first suggestion about suggesting `pnpm install` and published in `v15.1.0`.

**Comment by dougg0k** [comment]
nice
