### ISSUE TITLE
Feature request: reusable list to stdout, other messages to stderr

### ISSUE THREAD

**Issue by heavywatal** [raineorshine/npm-check-updates#1169]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14`

---

## Steps to Reproduce

`ncu -g 2>/dev/null`

## Current Behavior

```

 http-server  14.1.0  →  14.1.1
 npm          8.14.0  →  8.15.0

ncu itself cannot upgrade global packages. Run the following to upgrade all global packages:

npm -g install http-server@14.1.1 npm@8.15.0

```

Users have to copy and paste`npm -g install ...` command manually or execute `ncu -g | tail -n2 | sh` to upgrade the suggested packages.

## Expected Behavior

It would be nice if `ncu -g` writes (only) a list of upgradable packages to stdout:
```sh
http-server@14.1.1
npm@8.15.0
```

so that users can reuse it, e.g.,
```sh
npm -g install $(ncu -g)
```
or in two steps for safety:
```sh
ncu -g | pbcopy
# or
packages="$(ncu -g)"
```

Users can still see messages written to stderr unless it is redirected somewhere else.
Adding a new format like `--format list` may be a safer option to prevent potential breaking changes.

**Comment by raineorshine** [comment]
Hi, thanks for the suggestion.

Given that the small addition of `tail -2` provides a complete solution, I am not inclined to add this to npm-check-updates itself. The shell works well for basic line operations such as this. If the shell implementation was more complex, I would consider adding the feature.
