### ISSUE TITLE
Doctor should treat install errors like test errors

### ISSUE THREAD

**Issue by kayahr** [raineorshine/npm-check-updates#1170]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X]  I am using the latest version of `npm-check-updates`
- [X] I am using `node >= 14`

---

The doctor iteration doesn't work for any project which does some kind of compilation/transpilation (Typescript, native stuff, ...) in the prepare stage because in this case after upgrading a dependency the `npm install` step will most likely fail because this triggers the compilation and TypeScript for example throws a compilation error when the compiled code is not compatible with the new dependency. But when `npm install` fails then the doctor immediately aborts.

It would be nice if the doctor could treat `npm install` errors the same as when errors occurred during `npm test` instead of aborting. Otherwise TypeScript projects and other similar projects which performs compilation in the prepare stage can't be doctored by ncu.

**Comment by raineorshine** [comment]
Thanks for the thorough explanation. I totally agree.

I have attempted a fix and published it to `v16.0.1`. Try it and let me know if it works as expected.

**Comment by raineorshine** [comment]
Ah, I see. I didn't know that `npm prepare` was not executed when `--no-edit` is specified. 

Do you have a repo where I can reproduce the issue?

I think I will add `npm prepare` after each individual install. To clarify, is it the prepare script in your project, or in the dependency that needs to be run?

**Comment by kayahr** [comment]
Here is an example for reproduction:

https://github.com/kayahr/ncu-1170

The prepare script is in my project, not in the dependency.

**Comment by raineorshine** [comment]
Thanks so much! That's super helpful. I was also able to turn it into an automated test.

I added the logic to manually run the prepare script when it is present.

Published to `v16.0.4`

**Comment by kayahr** [comment]
Works great now. Thank you for the fast response and fix and thanks for this wonderful tool!
