### ISSUE TITLE
option --su/--sudo

### ISSUE THREAD

**Issue by VanoDevium** [raineorshine/npm-check-updates#1171]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14`

---

When I run 
```sh
ncu -g
[==================--] 19/21 90%
 npm-check-updates  16.0.0  →  16.0.1

ncu itself cannot upgrade global packages. Run the following to upgrade all global packages: 

npm -g install npm-check-updates@16.0.1
```

I see `npm -g install npm-check-updates@16.0.1`

But for my environment this string requires **sudo**
So, it will be nice to have extra option _--su_ (or _--sudo_) for prepend **sudo**.

This is super lazy option for super lazy people :) 

## Expected Behavior
```sh
ncu -g --sudo
[==================--] 19/21 90%
 npm-check-updates  16.0.0  →  16.0.1

ncu itself cannot upgrade global packages. Run the following to upgrade all global packages: 

sudo npm -g install npm-check-updates@16.0.1
```

**Comment by raineorshine** [comment]
While the value provided does not quite justify the addition of a CLI option, as a fellow lazy person I appreciate the intention :).

I would suggest making a shell alias for this purpose:

```
alias ncug="ncu -g | tail -2 | sed -E 's/^(.*[\n])/sudo \1/g' | bash"
```
