### ISSUE TITLE
Disable .ncurc for CLI

### ISSUE THREAD

**Issue by TrumanRu** [raineorshine/npm-check-updates#1179]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X] I am using the latest version of `npm-check-updates`
- [X] I am using `node >= 14`

---
## Current Behavior
`.ncurc` file in current or upper directory forces `ncu` configuration
## Expected Behavior
Disable .ncurc configuration for one CLI command.
I.e.
```bash
ncu --configFileIgnore [options]
```
`[options]` - could use for set paths (with wildcards or /regexps/) for choose ignored `.ncurc` files.
It is convenient to check possible dependencies upgrades outside of any `.ncurc` influence.

All command line parameters limitations (i.e. `--filter`, `--reject` or `--target`) still work.

**Comment by raineorshine** [comment]
Hi. The recommended approach is to point the `configFilePath` to a non-existent directory:

```
ncu --configFilePath /dev/null [options]
```
