### ISSUE TITLE
`ncu` Doesn't show latest versions for `multer` package

### ISSUE THREAD

**Issue by eugef** [raineorshine/npm-check-updates#1180]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14`

---

## Steps to Reproduce

.ncurc: empty

Dependencies:

```json
"dependencies": {
    "multer": "^1.4.1"
  }
```

Steps:

Just run `ncu`

## Current Behavior

Doesn't show that `multer` package has a newer version, while `npm outdated` returns correct data

```
Package  Current  Wanted       Latest  Location             Depended by
multer     1.4.1   1.4.4  1.4.5-lts.1  node_modules/multer  test
```

## Expected Behavior

`ncu` shows that the latest version for `multer` is `1.4.5-lts.1`

My assumption is that issue can be caused by the extra suffix `lts.1` in the package version.

**Comment by eugef** [comment]
I just realised that `ncu --target newest` gives the correct output
```
multer  ^1.4.1  →  ^1.4.5-lts.1
```

Looks like `ncu` detects `1.4.5-lts.1` as a pre-release version and excludes it by default.

**Comment by raineorshine** [comment]
That is correct. Pre-release versions are ignored by default. This is to prevent upgrades if a package author accidentally published a pre-release version to `latest`. ncu takes a conservative approach with these things.

Solution: Add `--pre` to include prerelease versions. It will still only pull from `latest` (unless you change `--target`).

Note that `multer` publishing a pre-release to the `latest` tag is **incorrect**, or at best unconventional. They should at least bump to a patch before publishing to `latest`. You might consider opening an issue with them.

Even `node-semver` requires a flag to opt-in to handling pre-release versions as normal:

> Note that this behavior can be suppressed (treating all prerelease versions as if they were normal versions, for the purpose of range matching) by setting the includePrerelease flag on the options object to any functions that do range matching.

https://github.com/npm/node-semver#prerelease-tags

**Comment by raineorshine** [comment]
> I just realised that `ncu --target newest` gives the correct output

This works, but use with caution. It will upgrade to the most recently published version, including to non-`latest` tags.

**Comment by eugef** [comment]
Thanks for clarification.

So using `ncu --pre 1` is safer than `ncu --target newest` ?

**Comment by raineorshine** [comment]
Yes. Use `ncu --pre 1` to include pre-releases that are published to `latest`.

`ncu --target newest` is appropriate if you want bleeding-edge upgrades.

You could also limit this to `multer` by adding a custom `--target` function to your ncurc config:

```js
target: name => name === 'multer' ? 'newest' : 'latest'
```

Run `ncu --help --target` for details.
