### ISSUE TITLE
--ignorePackagesWithoutVersionPrefix flag

### ISSUE THREAD

**Issue by Zamiell** [raineorshine/npm-check-updates#1183]
Hello and thanks for the excellent free software. :)

<br>

## What is This

This is a feature request for a new flag called `--ignorePackagesWithoutVersionPrefix`. Obviously, I just want the functionality, I don't actually care what the name is, so feel free to tell me that this proposed name is stupid. :)

<br>

## The Problem - Part 1

Imagine that we have a JavaScript or TypeScript project. A new version of a dependency just came out, and it breaks our project. Unfortunately, for whatever reason, we can't fix the problem in our code. So, instead, we will just "freeze" the package at the last known working version in our dependencies.

In order to do this, there are two steps:

1) Remove the prefix in the "package.json" file. For example:

```
"dependencies": {
  "someLibrary": "^4.7.4"
}
```

-->

```
"dependencies": {
  "someLibrary": "4.7.4"
}
```

2) Add a new entry for the "--reject" flag in our "update" script. (This is a script that invokes `npm-check-updates` for us.)

```
"scripts": {
  "update": "npm-check-updates --upgrade --reject somePreviouslyIgnoredLibrary"
},
```

-->

```
"scripts": {
  "update": "npm-check-updates --upgrade --reject somePreviouslyIgnoredLibrary,someLibrary"
},
```

(Note that instead of having an npm script in "package.json", we could also have this logic be an "update.sh" Bash script, or anything really.)

<br>

## The Problem - Part 2

As the number of frozen dependencies in our project grows, the string passed to the `--reject` command also grows.

This is brittle: whenever we freeze or unfreeze a dependency, we also have to remember to make a change to the other place, or else the two will get out of sync.

This violates DRY. Ideally, we want to manage our frozen packages in one place, not two.

<br>

## The Solution

In Node/npm land, it is best-practice to use the `^` prefix in your dependencies to indicate that patch semver versions should automatically be downloaded.

A consequence of this is that a "package.json" file with 1 frozen dependency will often look like this:

```
"dependencies": {
  "foo": "^2.4.1",
  "bar": "^8.4.2",
  "baz": "^4.10.1",
  "someFrozenDep": "1.0.0"
}
```

Thus, if `npm-check-updates` had a `--ignorePackagesWithoutVersionPrefix`, then we could tell it to update all of our deps, and this would do exactly what we wanted without us having to manage a separate explicit blacklist of all of the packages to ignore/reject.

Additionally, I think that it might make sense for `npm-check-updates` to *automatically* do this without any flag, as it seems more sane to me. On the other hand, I anticipate that you might not want to change the default functionality of the tool in such a large way, which is why I am proposing this as a flag.

**Comment by raineorshine** [comment]
Hi, thanks for reporting.

This is actually quite simple with the `--filterVersion` option:

```
--ncu --filterVersion "^*"
```

`--filterVersion` and `--rejectVersion` support all the same formats that `--filter` and `--reject` support. You can read more in the [Usage](https://github.com/raineorshine/npm-check-updates#usage) section of the README.

**Comment by Zamiell** [comment]
Ah, I see, thank you.
