### ISSUE TITLE
Dependencies not lexicographically sorted

### ISSUE THREAD

**Issue by rchl** [raineorshine/npm-check-updates#1186]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14`

---

## Steps to Reproduce

1. Have a NPM package with many outdated dependencies
2. Run `ncu` or `ncu --interactive --format group`

## Current Behavior

Printed list of dependencies is not in a sorted order.

## Expected Behavior

The list is sorted lexicographically. Same as is the case in `package.json` already.

**Comment by raineorshine** [comment]
Hi, thanks for reporting. I am not seeing this behavior on my end. Can you provide a package.json to reproduce? Then I can tests it directly. 

Updates should be sorted in the same order as in the package file.

**Comment by rchl** [comment]
I've noticed this issue initially on a private project but I can also reproduce on https://github.com/rchl/lsp-log-parser for example.

```
❯ ncu
Using yarn
Checking /usr/local/workspace/lsp/lsp-log-parser/package.json
[====================] 24/24 100%

 nuxt                               ^2.15.3  →   ^2.15.8
 vue-json-pretty                      1.8.3  →     2.2.2
 @nuxt/types                        ^2.15.4  →   ^2.15.8
 @nuxt/typescript-build              ^2.0.3  →    ^2.1.0
 @nuxtjs/stylelint-module            ^4.0.0  →    ^4.1.0
 @typescript-eslint/eslint-plugin   ^5.31.0  →   ^5.36.2
 @typescript-eslint/parser          ^5.31.0  →   ^5.36.2
 eslint                             ^8.22.0  →   ^8.23.0
 eslint-plugin-vue                   ^9.3.0  →    ^9.4.0
 husky                               ^4.3.0  →    ^8.0.1
 stylelint                          ^14.5.3  →  ^14.11.0
 stylelint-config-recommended-scss   ^6.0.0  →    ^7.0.0
 stylelint-config-standard          ^25.0.0  →   ^28.0.0
 vscode-languageserver-protocol     ^3.16.0  →   ^3.17.2
 vuex                                     3  →         4

Run ncu -u to upgrade package.json
```

I suppose it's because there are both dev and non-dev dependencies mixed in the list and the production show up first.

**Comment by raineorshine** [comment]
Yes, that makes sense. 

The challenge is in how to stay consistent. If we sort lexicographically, then a package file with a single dependency section will get reordered for no reason. If we follow the sorting of the package file, then each section matches the order in the package file, but we get a slightly disorienting effect when they are juxtaposed in the output. I'm not sure what is ideal.

**Comment by raineorshine** [comment]
I don't see an obvious behavior that would make a better default. The best approach might be to have opt-in lexicographic sorting.

**Comment by rchl** [comment]
> * If we sort lexicographically, then a package file with a single dependency section will get reordered for no reason.

When saying "lexicographically" I meant the order that matches npm. I don't know what code it uses for sorting but it does sort when using `npm` commands rather than adding stuff manually. So in typical cases the sorting should match `package.json`.

**Comment by rchl** [comment]
Since there is no distinction between production and dev-dependencies in the output of ncu, I think we could sort by default and treat it as a bug fix. I don't think that people expect the current behavior to be honest.

It's even more confusing in `--format group` mode.

**Comment by raineorshine** [comment]
Ah, I see. So it really isn't possible for a user to maintain a custom dependency order, as npm will reorder it as soon as the package file is rewritten. 

In that case lexicographic sort across the board seems correct!

**Comment by raineorshine** [comment]
Fixed and published in `v16.1.1`

**Comment by rchl** [comment]
Hi, I've checked new version and it appears to work while running `ncu` but not with `--interactive` and/or `--format group`.

**Comment by raineorshine** [comment]
@rchl eAh, good catch. I forgot those are printed in a different place.

Try `v16.1.2`!

**Comment by rchl** [comment]
Looks good now. Thank you!
