### ISSUE TITLE
Package dependancy breaking typescript 

### ISSUE THREAD

**Issue by efbenson** [raineorshine/npm-check-updates#1190]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14`

---

## Steps to Reproduce
running a tsc on your codebase when ncu is a dev dependancy will break with the most recent version of ncu
with a error(s)

``` 
node_modules/@types/cacheable-request/index.d.ts:26:42 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

26         cb?: (response: ServerResponse | ResponseLike) => void
                                            ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:77:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

77             listener: (response: ServerResponse | ResponseLike) => void
                                                     ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:81:69 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

81         on(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
                                                                       ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:84:71 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

84         once(event: 'response', listener: (response: ServerResponse | ResponseLike) => void): this;
                                                                         ~~~~~~~~~~~~

node_modules/@types/cacheable-request/index.d.ts:89:51 - error TS2709: Cannot use namespace 'ResponseLike' as a type.

89             listener: (response: ServerResponse | ResponseLike) => void
                                                     ~~~~~~~~~~~~
...
```

A npm ls shows
```
└─┬ npm-check-updates@16.1.2
  └─┬ update-notifier@6.0.2
    └─┬ latest-version@7.0.0
      └─┬ package-json@8.1.0
        └─┬ got@12.4.1
          └── cacheable-request@7.0.2
```

It seems the bump here:
https://github.com/raineorshine/npm-check-updates/commit/c98156da940f35d6015eea32ba487b1fe5548dd8

Introduced it.  Rolling back to the version right before that works fine.

Here is some background on that issue: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/62099

**Comment by raineorshine** [comment]
Thanks for reporting!

I looked at the related issue. Any idea what the solution is?

**Comment by jerone** [comment]
Try (with your path to TSConfig):
```shell
tsc -p tsconfig.json
```

**Comment by raineorshine** [comment]
I set up a simple project that imports and executes npm-check-updates. It compiles without error.

https://github.com/raineorshine/ncu-test-import-as-module

If you provide a sample repo where the issues can be reproduced I would be happy to investigate more.

**Comment by efbenson** [comment]
It looks like the dependancies worked it out, with the most recent version I can't reproduce it.  Next time I run into something like this I will create a repo for reproducing.
