### ISSUE TITLE
Error when installing new versions using pnpm

### ISSUE THREAD

**Issue by andrei-zgirvaci** [raineorshine/npm-check-updates#1191]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14`

---

## Steps to Reproduce

.ncurc:

```js

```

Dependencies:

```json

```

Steps:

1. Run: `ncu --upgrade --interactive --format group`
2. Select packages (doesn't matter which or how many)
3. When asked if you would like to install new versions using pnpm, type Yes

## Current Behavior

An error is thrown:

```cli
/Users/andrei/Library/pnpm/global/5/.pnpm/npm-check-updates@16.1.2/node_modules/npm-check-updates/build/src/index.js:57
    throw err;
    ^
```

## Expected Behavior

No errors should be thrown

Thank you in advance for the help on this matter as I am curious if my pnpm has some issues or if it's something else!

**Comment by raineorshine** [comment]
It works as expected for me:

```sh
raine[1191]% cat package.json
{
  "dependencies": {
    "ncu-test-v2": "1.0.0"
  }
}
raine[1191]% ncu --upgrade --interactive --format group
Upgrading /Users/raine/projects/ncu-issues/1191/package.json
[====================] 1/1 100%

✔ Choose which packages to update ›

 ncu-test-v2  1.0.0  →  2.0.0

✔ Run pnpm install to install new versions? … yes
```

git diff:

```diff
diff --git a/package.json b/package.json
index 84c652e..a3a9f05 100644
--- a/package.json
+++ b/package.json
@@ -9,6 +9,6 @@
   },
   "license": "ISC",
   "dependencies": {
-    "ncu-test-v2": "1.0.0"
+    "ncu-test-v2": "2.0.0"
   }
 }
diff --git a/pnpm-lock.yaml b/pnpm-lock.yaml
index 89485a7..e0ce226 100644
--- a/pnpm-lock.yaml
+++ b/pnpm-lock.yaml
@@ -1,13 +1,13 @@
 lockfileVersion: 5.4

 specifiers:
-  ncu-test-v2: 1.0.0
+  ncu-test-v2: 2.0.0

 dependencies:
-  ncu-test-v2: 1.0.0
+  ncu-test-v2: 2.0.0

 packages:

-  /ncu-test-v2/1.0.0:
-    resolution: {integrity: sha512-Oaw47teUXoN1tzTj8h+q1NiMlRRJeG9cs2EyPkITLogRcsoe3Z/QiTc7dgZdXh8Pm4TL0VhvGz0hnqsR20XFWw==}
+  /ncu-test-v2/2.0.0:
+    resolution: {integrity: sha512-Jqu6DzpKkTrUdeL+VN/X4lz4IVDxkNAqVHmyJ+3uVcszqPlU8JMNTA2qeihzMcbd4pOiagKlJno7r+EO2WLmfw==}
     dev: false
```

**Comment by andrei-zgirvaci** [comment]
@raineorshine sorry, forgot to mention.

Indeed the package.json, pnpm-lick.yaml and node_modules does get updated, but and error is thrown after.

The error doesn't screw anything up, it's just annoying to see it every time and I am curious if other people have it too...

**Comment by raineorshine** [comment]
I'm not seeing any error on my side when I run the command as described. Without being able to reproduce it there's not much I can do, but maybe somebody who can reproduce it is able to investigate.

**Comment by leosuncin** [comment]
Reproduction:
[![asciicast](https://asciinema.org/a/jSsXJGceP31r5NnBujbdvW0wF.svg)](https://asciinema.org/a/jSsXJGceP31r5NnBujbdvW0wF)

Repository: https://github.com/leosuncin/nest-api-example

**Comment by leosuncin** [comment]
And it gets worst with `--doctor`

```
npm-check-updates --upgrade --doctor
```

[![ncu -u --doctor](https://asciinema.org/a/SWYsX4RRyMrKx4QXxsfnGOc8I.svg)](https://asciinema.org/a/SWYsX4RRyMrKx4QXxsfnGOc8I)

```
npm-check-updates --upgrade --doctor --doctorTest='pnpm test' --doctorInstall='pnpm install'
```

[![ncu -u --doctor --doctorTest='pnpm test' --doctorInstall='pnpm install'](https://asciinema.org/a/OQzg1gHhOZu8KL3nKGtZaFXsJ.svg)](https://asciinema.org/a/OQzg1gHhOZu8KL3nKGtZaFXsJ)

**Comment by raineorshine** [comment]
> And it gets worst with `--doctor`

Please open a separate issue with steps to reproduce if the error with `--doctor` still occurs.
