### ISSUE TITLE
No package versions were returned when importing libs without releases from github

### ISSUE THREAD

**Issue by Wyzix33** [raineorshine/npm-check-updates#1194]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 18`

---

## Steps to Reproduce

Dependencies:

```json
{
 "name": "select",
 "version": "1.0.0",
 "main": "select.js",
 "author": "Wyzix33",
 "license": "No License",
 "private": true,
 "dependencies": {
  "utils": "Wyzix33/utils"
 }
}

```

Steps:

when importing libs without Releases from github i get this warning when running ncu -u.
`
No package versions were returned. This is likely a problem with your installed yarn, the npm registry, or your Internet connection. Make sure npx pacote packument ncu-test-v2 is working before reporting an issue.
`

## Current Behavior
Getting warning
## Expected Behavior
No warning...

Thanks

**Comment by raineorshine** [comment]
Good catch!

Fixed and published to `v16.3.1`
