### ISSUE TITLE
"RangeError: Invalid array length" on update 

### ISSUE THREAD

**Issue by bz2** [raineorshine/npm-check-updates#1200]
Running `npm-check-updates` using the latest `16.3.7` failed for me earlier with:

```
$ npx npm-check-updates -u
Need to install the following packages:
  npm-check-updates@16.3.7
Ok to proceed? (y) y
/home/martin/.npm/_npx/0a80f0fb114540fe/node_modules/npm-check-updates/build/src/index.js:56
    throw err;
    ^

RangeError: Invalid array length
    at /home/martin/.npm/_npx/0a80f0fb114540fe/node_modules/npm-check-updates/build/src/bin/cli.js:37:15
```

Rerunning with a pinned version, the command then worked fine:

```
$ npx npm-check-updates@16.3.6 -u
...
Run npm install to install new versions.
```

That was presumably due to whatever the weird versions were having been cleared out by the first run however, rather than the library change, as the failing code was introduced in `16.3.2`  https://github.com/raineorshine/npm-check-updates/commit/d4f97ee189b9e004623417d23e95195c9d504d9f specifically:

```js
    const majorVersions =
      currentMajor && latestMajor
        ? new Array(latestMajor - currentMajor).fill(0).map((x, i) => currentMajor + i + 1)
        : []
```

Has a precondition that `latestMajor >= currentMajor` which appears to have not been satisfied when I initially ran the command! I've seen that be the case in the past for installed pre-releases and similar?

So, I don't have the exact set of packages which will reproduce the issue any more, but it's pretty clear how the failure happened.

```
$ npm version
{
  ...
  npm: '8.15.0',
  node: '16.17.0',
  ...
}
```

**Comment by raineorshine** [comment]
Good catch! And thanks for the thorough bug report.

Fixed and published in `v16.3.8`.
