### ISSUE TITLE
Add support to provide build command along with --doctor flag

### ISSUE THREAD

**Issue by devblin** [raineorshine/npm-check-updates#1203]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14`

---

## Current Behavior
Currently, using this command: `ncu --doctor [-u] [options]` , allow passing install script cmd `--doctorInstall` and test script cmd `--doctorTest`

## Expected Behavior
It would be helpful if we can pass build script cmd using some flag like: `--doctorBuild`

**Comment by raineorshine** [comment]
Doctor mode only runs two scripts, install and test, and it is not intended to emulate the npm lifecycle scripts. If you need to run a build script before Doctor runs the tests, add it to a custom `--doctorTest` script. 

e.g. 

package.json:

```js
"scripts": {
  "build": "...",
  "test": "...",
  "build-and-test": "npm run build && npm run test"
}
``` 

npm-check-updates:

```sh
ncu -u --doctor --doctorTest build-and-test
```
