### ISSUE TITLE
Error when using js api after build by `unbuild`

### ISSUE THREAD

**Issue by qmhc** [raineorshine/npm-check-updates#1204]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14`

---

I using `ncu` via js api and I using `unbuild` to pack.

But after build and run, it will occur a error.

## Steps to Reproduce

Reproduction: https://github.com/qmhc/ncu-test

## Current Behavior

Get error:

```log
const contentVer = require$$10['cache-version'].content;
                                                ^

TypeError: Cannot read properties of undefined (reading 'content')     
    at file:///D:/ui-library/ncu-test/dist/index.mjs:42926:49
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)     
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12) 
```

## Expected Behavior

No error occured.

**Comment by raineorshine** [comment]
Please open an issue with unbuild. npm-check-updates works correctly as a module both in js and typescript.
