### ISSUE TITLE
Can this package detect update of package from github repository?

### ISSUE THREAD

**Issue by dimaslanjaka** [raineorshine/npm-check-updates#1211]
example package
```json
{
  "@types/through2": "git+https://github.com/dimaslanjaka/nodejs-package-types#through2"
}
```

is `npm-check-updates` can check changes from remote repository and apply them on package-lock.json ?

if possible, how to do it ?

**Comment by raineorshine** [comment]
`npm-check-updates` supports upgrading GitHub urls via tags:

``` 
"through2": "git+https://github.com/rvagg/through2#v4.0.0"
``` 

It doesn't support monorepos, but you may not even need npm-check-updates in your case. `git+https://github.com/dimaslanjaka/nodejs-package-types#through2` is effectively at version number `*` and thus `npm install` will always install the latest from the remote.

**Comment by dimaslanjaka** [comment]
so, i must manually update the package with `npm update monorepo-package-name`
