### ISSUE TITLE
ncu cache does not respect target

### ISSUE THREAD

**Issue by xiaoyu-tamu** [raineorshine/npm-check-updates#1218]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce
 
Steps:

Without cache
```js
ncu --target latest

All dependencies match the latest package versions :)

ncu --target newest
prettier                           2.7.1  →       3.0.0-alpha.4

```

With cache
```js
ncu --target latest --cache

All dependencies match the latest package versions :)

ncu --target newest --cache

Using 3 cached package versions
All dependencies match the newest package versions :)
```

## Current Behavior
cache is shared between different target

## Expected Behavior
cache should not shared between different target

**Comment by raineorshine** [comment]
Good catch!

Fixed and published in `v16.3.19`
