### ISSUE TITLE
ncu does not detect update from deprecated version

### ISSUE THREAD

**Issue by mohd-akram** [raineorshine/npm-check-updates#1222]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce

Dependencies:

```json
{ "multer": "^1.4.4" }
```

Steps:

```shell
mkdir ncu-test && cd ncu-test
npm init -y
npm install multer@1.4.4
ncu
```

## Current Behavior

```
No package versions were returned. This is likely a problem with your installed npm, the npm registry, or your Internet connection. Make sure npx pacote packument ncu-test-v2 is working before reporting an issue.
```

## Expected Behavior

A potential upgrade is shown ([1.4.5-lts.1](https://www.npmjs.com/package/multer/v/1.4.5-lts.1) currently).

**Comment by raineorshine** [comment]
To include prerelease versions, use `--pre 1`. npm-check-updates does not upgrade to prerelease versions by default.

```sh
$ ncu --pre 1

Checking /Users/raine/projects/ncu-issues/1222/package.json
[====================] 1/1 100%

 multer  ^1.4.4  →  ^1.4.5-lts.1
```

It is unconventional to publish a prerelease package to the `latest` tag, though given the security vulnerability in `1.x` I can see why they did that. From a semver perspective, what they should have done was release `1.4.5-lts.1` to `2.0.0`, and then release their next major version upgrade to `3.0.0`. Some package maintainers are squeamish about major version upgrades though.

**Comment by mohd-akram** [comment]
I think whatever's in `latest` should take priority, to match what happens when one does a plain `npm install multer`.

**Comment by raineorshine** [comment]
The prerelease filter was added to help prevent upgrades or betas that are accidentally published to `latest`. In general, npm-check-updates takes a conservative approach. We would rather avoid an update than upgrade to something that is experimental. `multer` is using an unconventional release strategy, so it feels appropriate to have an opt-in rather than default. 

There is always `--greatest`, which has `--pre 1` by default, for bleeding edge updates.

**Comment by mohd-akram** [comment]
That's fair enough. I don't understand the point of the `-lts.1` suffix that they're using really. Thanks.
