### ISSUE TITLE
Tests timeout with github assking for credentials in `valid but non-existent github urls with tags should be ignored`

### ISSUE THREAD

**Issue by doublethefish** [raineorshine/npm-check-updates#1230]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce

1. clone ncu
2. run `npm run test`
3. notice a prompt for github username and password appears when running tests
4. notice that the tests hand and eventually timeout `in valid but non-existent github urls with tags should be ignored`

## Current Behavior

Tests hang if the username & pass aren't added in, but pass if they are.

## Expected Behavior

Something like:

- No prompt mid-test for github credentials
- Documentation in CONTRIBUTING.md on how to configure github credentials for ncu use

**Comment by raineorshine** [comment]
Thanks for the suggestion! I added this to [CONTRIBUTING.md](https://github.com/raineorshine/npm-check-updates/blob/main/.github/CONTRIBUTING.md):

---

Some of the tests use the git+https protocol. If git prompts you for credentials in the middle of running the tests, you may want to enable credentials storage:

git config --global credential.helper store
When running this command, the first time you pull from the remote repository, you'll get asked for your username and password.

Afterwards, for consequent communications with the remote repository you won't have to provide the username and password.

https://stackoverflow.com/a/35943882/480608

**Comment by doublethefish** [comment]
Excellent work, thank you!

**Comment by doublethefish** [comment]
I had some more time to look at this.

The root-cause problem is that the test itself uses a _private_ repository. Git tries to use existing credentials† but, because I (and most others) do not have access to that repo, git prompts falls back to asking for valid credentials - which would be expected & desired runtime behaviour. Unfortunately, it means the test hangs.

Consequently, we probably want to remove the advice to use `git config --global credential.helper store` as it doesn't help in this case and, more importantly, causes the user's credentials to be stored using plain text on disk, which is a security risk.

The repo reference is an HTTPS one: `'ncu-test-private': 'https://github.com/ncu-test/ncu-test-private#v999.9.9',`.

To see the problem that people without repo access see, you can probably use this alpine/git docker image (which should have clean ssh keys/auth):
`docker run -ti --rm alpine/git clone https://github.com/ncu-test/ncu-test-private`

Perhaps the private repo should be removed from this specific integration-test, unless there's a nice way to give access to it in a shared but managed way(?).

† (including my ssh creds)

**Comment by raineorshine** [comment]
Ah, I see. Thanks for investigating.

I agree with simply removing the private repo from the test. It is only one test and a regression is unlikely.
