### ISSUE TITLE
[Request] Document usage of ncurc function options

### ISSUE THREAD

**Issue by CreativeTechGuy** [raineorshine/npm-check-updates#1233]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Feature Request

There's a lot of very useful advanced options which have no documentation. I was about to create a request but finally found [this issue](https://github.com/raineorshine/npm-check-updates/issues/866) showing that it was already implemented. I never knew about it since it wasn't documented anywhere. There's a lot of examples of these since many of the CLI args have advanced function options. Could there be a section of the README to show an example usage and interface for each of these options? What you posted [in this comment](https://github.com/raineorshine/npm-check-updates/issues/866#issuecomment-1097266140) is perfect if it was all in one place.

**Comment by raineorshine** [comment]
That's a great suggestion. I've added a new section to the README which documents all the [Advanced Options](https://github.com/raineorshine/npm-check-updates#advanced-options).

For what it's worth, both the README and the `--help` output said `Run "ncu --help --target" for details`, so technically it's not true that there was *no* documentation. However, if it's not easily discoverable, it might as well not exist, so I'm glad you reached out. This should make it easier for others to see the full range of functionality of npm-check-updates.

**Comment by CreativeTechGuy** [comment]
Wow that was fast! Thank you as always. Looks great.
