### ISSUE TITLE
Print Release Date with NCU versions

### ISSUE THREAD

**Issue by bsaracalign** [raineorshine/npm-check-updates#1235]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

This is simply to ask, is there a way to print release date information of packages?
For example: https://www.npmjs.com/package/react-input-mask
Let's say I have 1.2.2 and ncu says 2.0.4 is the latest version. But even this version was released 4 years ago. Even If I update to this version, I am out of date by like 4 years. Is it possible to print out along with ncu latest versions when they were released?

**Comment by raineorshine** [comment]
Yes, I think that would be useful.

I added the `--format time` option and published to `v16.5.0`. Please try it out at your convenience.

```
$ ncu --format time                                                                               ✓

 @types/lodash                  ^4.14.189  →  ^4.14.191    2022-11-30T20:34:13.537Z
 @types/mocha                     ^10.0.0  →    ^10.0.1    2022-11-28T19:32:56.644Z
 @types/node                     ^18.11.9  →  ^18.11.11    2022-12-05T20:03:15.633Z
 @types/prompts                    ^2.4.1  →     ^2.4.2    2022-12-05T20:04:25.272Z
 @typescript-eslint/parser        ^5.44.0  →    ^5.45.1    2022-12-05T17:27:30.351Z
 minimatch                         ^5.1.0  →     ^5.1.1    2022-11-29T20:33:52.832Z
 sinon                            ^14.0.2  →    ^15.0.0    2022-11-28T17:18:35.793Z
```

**Comment by bsaracalign** [comment]
Beautiful, thank you so much. This is a great tool!

**Comment by bsaracalign** [comment]
Hello, Actually i just did that but doesn't give me dates: 

```
npx ncu --format time
package.json
[====================] 62/62 100%

 @bugsnag/js                          ^7.17.0  →    ^7.18.0     
 @bugsnag/plugin-react                ^7.17.0  →    ^7.18.0     
 @types/cookie                         ^0.4.1  →     ^0.5.1     
 add-to-calendar-button               ^1.8.10  →    ^1.18.8     
 aws-sdk                            ^2.1061.0  →  ^2.1270.0     
 axios                                ^0.25.0  →     ^1.2.1     
 ...
 typescript                             4.5.5  →      4.9.3     
```

**Comment by raineorshine** [comment]
Try the full command `npx npm-check-updates --format time`.

`npx ncu` would just execute the local executable in your PATH and not check for latest.

**Comment by bsaracalign** [comment]
I still get -> 

 ```
@bugsnag/js                          ^7.17.0  →    ^7.18.0     
 @bugsnag/plugin-react                ^7.17.0  →    ^7.18.0     
 @types/cookie                         ^0.4.1  →     ^0.5.1 
```

**Comment by bsaracalign** [comment]
Okay works thank you!! : )

**Comment by bsaracalign** [comment]
Do you know why it would scan 62 packages but output only 47 ?

**Comment by bsaracalign** [comment]
@raineorshine  could you make it so if package is up to date it still shows up in the ncu list? some packages are up to date in my package json but their up to date latest version are like 5 years or so old, so it'd be great to know. if package up to date it doesnt show up in ncu list but if there was a flag to include so latest date shows it'd be awesome.

also is there way to display ncu data CSV comma delaminated format?

**Comment by raineorshine** [comment]
> @raineorshine could you make it so if package is up to date it still shows up in the ncu list? some packages are up to date in my package json but their up to date latest version are like 5 years or so old, so it'd be great to know. if package up to date it doesnt show up in ncu list but if there was a flag to include so latest date shows it'd be awesome.

This is outside the scope of npm-check-updates, which is only meant to show packages in need of upgrading.

You can get the last publish time of any package with `npm view PACKAGE_NAME time.modified`.

> also is there way to display ncu data CSV comma delaminated format?

Not currently. I recommend using `npm-check-updates` as a module and then use a JSON-to-csv module to convert it to CSV.

---

P. S. With a little bit of shell scripting, you can even output a passable display of the last publish time of all installed packages:

```sh
npm ls | tail +2 | sed '$d' | sed -e 's/^....//' | while read line; do echo $line; npm view $line time.modified; done | paste - -
```

Which gives something like this:

```
@types/chai-as-promised@7.1.5	2022-11-14T08:22:42.069Z
@types/chai-string@1.4.2	2022-11-14T08:22:51.661Z
@types/chai@4.3.4	2022-11-07T20:34:58.675Z
@types/cli-table@0.3.1	2022-11-07T08:11:32.003Z
@types/hosted-git-info@3.0.2	2022-11-14T08:27:01.071Z
@types/ini@1.3.31	2022-11-14T08:27:12.961Z
...
```

**Comment by bsaracalign** [comment]
wow this is quite nice. I did below:

I combined all packages that are used. Between visual code and excel, cleaned up duplicates. Then instead of their current versions, I hardcoded 0.0.0 for all of them. Then I run `ncu --format time` and it found all. I replaced mid section with a comma, pasted it excelsheet and formatted 2 columns, sorted by date.

**Comment by raineorshine** [comment]
Nice!
