### ISSUE TITLE
[Feature Request] upgrade the "packageManager" field of package.json

### ISSUE THREAD

**Issue by meteorlxy** [raineorshine/npm-check-updates#1252]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Context

Node.js allows a [packageManager](https://nodejs.org/api/packages.html#packagemanager) field in `package.json` file.

It would be great if ncu could help to upgrade that field to the latest version of corresponding package manager.

Also, we could print an extra notice to tell users that they should upgrade the system-installed package manager if it's not the latest version.

**Comment by raineorshine** [comment]
Hi, thanks for the suggestions. I added support and published to `v16.6.0`. Just add `packageManager` to the dep list:

```
ncu --dep dev,optional,prod,bundle,packageManager
```

Or add to your `.ncurc`:

```
{
  "dep": ["prod", "dev", "bundle", "optional", "packageManager"]
}
```

> Also, we could print an extra notice to tell users that they should upgrade the system-installed package manager if it's not the latest version.

It is currently out of scope for npm-check-updates to provide other notices besides the standard output. The recommended approach would be to run `ncu -g` or `ncu -g PACKAGE_MANAGER`.
