### ISSUE TITLE
JS `.ncurc` config file not supported in ESM projects

### ISSUE THREAD

**Issue by josh-hemphill** [raineorshine/npm-check-updates#1257]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

According to this issue: azu/rc-config-loader#22
`rc-config-loader` will not be supporting ESM for some time.
The easiest interim solution would be to allow `.cjs` config files, though in the issue above they point out [`cosmiconfig`](https://github.com/davidtheclark/cosmiconfig) supports ESM by default (also allows `.cjs`)

## Steps to Reproduce

.ncurc:

```js
export default {
   peer: true
};
```

Steps:

Run `ncu` such that it attempts to load the config file in a project with a `package.json` that has `"module":true` set.

## Current Behavior
Fails with `export default` being unexpected syntax

## Expected Behavior
JS Config file to be loaded.

**Comment by raineorshine** [comment]
Hi, thanks for the suggestion. It would be nice to allow ESM modules for config files, though that probably needs to occur in the config loader library, not in npm-check-updates. 

We could switch to cosmicconfig, depending on how much work it takes to ensure it isn't a breaking change. 

In the mean time, are you able to use a CommonJS `.ncurc.js` file?

```js
module.exports = {
  peer: true
}
```

**Comment by josh-hemphill** [comment]
Yeah, it will load if I use CommonJS syntax, though my linter complains.
That's most of the reason I suggested allowing `.cjs` extensions, so if it has to be CommonJS, it's at least explicit that that is what it's using.

**Comment by raineorshine** [comment]
Okay, thanks. 

You could use `--configFileName .ncurc.cjs`. But it would also be nice to detect it automaticaly.

**Comment by raineorshine** [comment]
> You could use `--configFileName .ncurc.cjs`. But it would also be nice to detect it automaticaly. It's pretty inconvenient since you can't store configFileName in the config file itself.

Actually, I just tested it out and it seems to be autodetecting cjs files as it is:

```
$ cat package.json
{
  "dependencies": {
    "ncu-test-v2": "^1.0.0",
    "ncu-test-tag": "1.0.0"
  }
}
$ cat .ncurc.cjs
module.exports = {
  filter: "ncu-test-v2"
}
$ ncu
Using config file /Users/raine/projects/ncu-issues/1257/.ncurc.cjs
Checking /Users/raine/projects/ncu-issues/1257/package.json
[====================] 1/1 100%

 ncu-test-v2  ^1.0.0  →  ^2.0.0

Run ncu -u to upgrade package.json
```

**Comment by josh-hemphill** [comment]
Awesome!
I was looking at the code and only saw `.js` in the `rc-config-loader` initialization so I assumed that's all it would resolve.
