### ISSUE TITLE
Prefix option doesn't work with no root package.json

### ISSUE THREAD

**Issue by paul-sachs** [raineorshine/npm-check-updates#1258]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X] I am using the latest version of `npm-check-updates`
- [X] I am using `node >= 14.14`

---

## Steps to Reproduce

Steps:

```sh
mkdir new-project
cd new-project
npm init -y
npm install react@16
cd ..
ncu -u --prefix new-project
```

## Current Behavior

Fails with output:

```sh
No package.json

Please add a package.json to the current directory, specify the --packageFile or --packageData options, or pipe a package.json to stdin.
```

## Expected Behavior

Upgrades React to newest version.

**Comment by raineorshine** [comment]
`--prefix` only changes the npm working directory, it doesn't change the directory where npm-check-updates operates. `--prefix` is mainly used when running ncu in global mode if the default npm prefix is not read properly. 

I think you want `--cwd` instead.

**Comment by paul-sachs** [comment]
Ah, totally missed `--cwd`. I guess because npm uses the questionably named `--prefix` i hadn't even looked for other options. `--cwd` was indeed what I was looking for. Thanks for the quick response!
