### ISSUE TITLE
Deno imports compatibility?

### ISSUE THREAD

**Issue by shinebayar-g** [raineorshine/npm-check-updates#1267]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [ ] I am using `node >= 14.14`

---

Hi, I'm a long time ncu user, love it. Recently I started working on a new project with [Deno](https://github.com/denoland/deno). Looks like Deno supports npm modules via imports configuration. Example `deno.json` file.
```json
{
    "imports": {
        "cdk8s": "npm:cdk8s@^2.6.43",
    },
}
```

With this defined, deno will support npm modules without any other changes. Following works as expected.
```ts
import { App, Chart, ChartProps } from 'cdk8s';
```

Would you consider making ncu compatible with Deno with above workflow?

**Comment by raineorshine** [comment]
Hi, thanks for the suggestion.

I added basic support and published to `v16.7.0`. `ncu`will autodetect `deno.json`, or you can do `ncu --packageManager deno --packageFile customDenoConfig.json` if you have a custom deno config file location.

Please try it out at your convenience and let me know how it works :).

**Comment by shinebayar-g** [comment]
Just tried it out. It worked well.

```
❯ ncu
Using deno
Checking /Users/me/cdk8s-demo/deno.json
[====================] 2/2 100%

 cdk8s  npm:cdk8s@2.6.43  →  2.6.44

Run ncu -u to upgrade deno.json
```
Couple of items.

1. Looks like deno config file is going to be either `deno.json` or `deno.jsonc`. [Doc](https://deno.land/manual@v1.30.3/getting_started/configuration_file)
> The configuration file supports .json and .jsonc extensions.

2. Not sure if `deno install` command is correct one to use.

```
❯ ncu
Using deno
Upgrading /Users/me/cdk8s-demo/deno.json
[====================] 2/2 100%

 cdk8s  npm:cdk8s@2.6.43  →  2.6.44

Run deno install to install new versions.

❯ deno install
error: The following required arguments were not provided:
    <cmd>...

USAGE:
    deno install [OPTIONS] <cmd>...

For more information try --help

❯ deno install --help
deno-install
Installs a script as an executable in the installation root's bin directory.
```

I think correct usage is maybe this.
```
❯ deno cache npm:constructs@10.1.243 # worked
❯ deno cache npm:constructs # didn't work
```

**Comment by shinebayar-g** [comment]
Just tried multiple package upgrade.

```sh
❯ ncu
Using deno
Checking /Users/me/cdk8s-demo/deno.json
[====================] 2/2 100%

 cdk8s              npm:cdk8s@2.6.43  →    2.6.44
 constructs  npm:constructs@10.1.243  →  10.1.245

Run ncu -u to upgrade deno.json
```

```sh
❯ ncu -u
Using deno
Upgrading /Users/me/cdk8s-demo/deno.json
[====================] 2/2 100%

 cdk8s              npm:cdk8s@2.6.43  →    2.6.44
 constructs  npm:constructs@10.1.243  →  10.1.245

Run deno install to install new versions.
```

Multiple package upgrade worked as expected.
```sh
deno cache npm:constructs@10.1.245 npm:cdk8s@2.6.44
```

**Comment by shinebayar-g** [comment]
> I meant npm cache X.

Oops I edited my message 😆 

Yeah I agree with you. :)

**Comment by raineorshine** [comment]
Added jsonc support in `v16.7.3`

**Comment by shinebayar-g** [comment]
Just tested out the latest release, looks like you nailed it. Thank you.
