### ISSUE TITLE
Bug? - Unsupported target "patch"

### ISSUE THREAD

**Issue by deleonio** [raineorshine/npm-check-updates#1268]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce

Dependencies:

```json
	"devDependencies": {
		"npm-check-updates": "16.6.5"
	},
```

Steps:

Execute: `npx ncu -t patch`

## Current Behavior

```bash
Error: Unsupported target "patch" for pnpm. Supported version targets are: latest, newest, greatest, minor and custom distribution tags, following "@" (example: @next)
```

## Expected Behavior

No error.

**Comment by raineorshine** [comment]
Yes! Good catch. This is a regression.

Fixed and published in `v16.7.1`.
