### ISSUE TITLE
ignore pnpm workspace local packages

### ISSUE THREAD

**Issue by TimonPeng** [raineorshine/npm-check-updates#1272]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce

Dependencies:

```json
{
  "dependencies": {
    "@timonpeng/logger": "workspace:^0.0.0",
  }
}
```

Steps:

## Current Behavior

```bash
$ pnpm ncu -p pnpm -i --packageFile 'packages/*/package.json'

No package versions were returned. This is likely a problem with your installed pnpm, the npm registry, or your Internet connection. Make sure npx pacote packument ncu-test-v2 is working before reporting an issue.
```

## Expected Behavior

ignored pnpm workspace local packages

**Comment by raineorshine** [comment]
Thanks for reporting!

Fixed and published in `v16.7.9`.
