### ISSUE TITLE
Quotes in --filter

### ISSUE THREAD

**Issue by massadm** [raineorshine/npm-check-updates#1273]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce

```sh
npx npm-check-updates --filter "@a @b @c"
```
## Current Behavior

Output: `Run npx npm-check-updates --filter @a @b @c -u to upgrade package.json`

## Expected Behavior

Output: `Run npx npm-check-updates --filter "@a @b @c" -u to upgrade package.json`

Note quotation marks.

**Comment by raineorshine** [comment]
ncu does not currently support searching by bare scope, but I think that's a great idea.

In the mean time, you can use wildcards: `npx npm-check-updates --filter "@a/* @b/* @c/*" -u`.

**Comment by massadm** [comment]
I allowed the simplification of real data, because in my example, they are not the main thing. This is output related issue. The quotes are missing where they should be. Note --filter parameters.

**Comment by raineorshine** [comment]
Ahhhh, I see. I misunderstood. Good catch! I'll address this.

**Comment by raineorshine** [comment]
Fixed and published in `v16.7.7`.
