### ISSUE TITLE
Not recognizing workspaces in pnpm-workspace.yaml

### ISSUE THREAD

**Issue by ivancuric** [raineorshine/npm-check-updates#1284]
ncu doesn't recognize workspaces which are specified inside a `pnpm-workspace.yaml`.

It only looks inside the workspaces specified inside package.json.

Would be great if it could support this format as it supports globs:
https://pnpm.io/pnpm-workspace_yaml

**Comment by raineorshine** [comment]
Fixed and published in `v16.8.1`.
