### ISSUE TITLE
Update only major versions

### ISSUE THREAD

**Issue by mslowiak** [raineorshine/npm-check-updates#1286]
Hi!
I was playing around with npm-check-updates and did not found an option to update only major versions (excluding potential updates for minor/patch libraries).

**Why I need this?**
Updating deps update is tedious task for each I have the Jenkins job.
For the minor/patch updates, I would like to deploy update dependencies automatically (automated work)
For the major updates, I want to review the changes before I deploy new application version (manual work) 

**Example:**
application package.json contains following libraries:
- a - 1.2.0
- b - 13.0.0
- c - 5.0.1

There newest versions in artifactory:
- a - 1.3.0
- b - 14.1.1
- c - 5.0.3

**Expectation:**
Only version of artifact `b` should be updated from 13.0.0 to 14.1.1 because that is the major change in the example.
Currently there is a target option, but my use case is not supported with any of options there. 

**Workaround:**
1. Execute `npx npm-check-updates --format group`
2. Parse the output from point 1 and get arfifacts names from `Major` section
3. Run `npm-check-updates` with  regex based on artifacts found in point 2

Maybe there can be added new target option called `majorOnly` that will work like I described?

**Comment by mslowiak** [comment]
> --target minor and --target patch, which appear to be closest functionally, actually match against all published versions. I assume you want to stick to the version published to the latest tag.

I am not sure if I understand correctly but for my use case I am interested only in major versions.
The `--target latest` returns majors, minors, and patches.

> FYI If you use ^ ranges, then you could use --minimal to achieve your desired behavior.
That would be an option, but taking into account multiple repository changes it's not feasible.

You mentioned the `filterResults`. Is the work regarding that thing already started?
If there is any option to help develop something in this direction, let me know 👍

**Comment by mslowiak** [comment]
That would be great if you could put some light on the code, maybe that will help to get it done faster 👍

**Comment by raineorshine** [comment]
The new `filterResults` option can be added to https://github.com/raineorshine/npm-check-updates/blob/main/src/cli-options.ts. This makes `options.filterResults` available throughout the codebase.

I would recommend the following signature for the use-provided predicate function:

```
export type FilterResultsFunction = (packageName: string, { currentVersion: VersionSpec, currentVersionSemver: SemVer[], upgradedVersion: Version }) => boolean
```

(I chose this signature to be somewhat future-proof; removing/changing arguments would require a major version change, but adding keys to the argument object would not.)

You will need to pass the appropriate arguments to the user-provided `filterResults` function:

- currentVersion - `currentDependencies[dep]` (available in scope; see below)
- currentVersionSemver - `parseRange(currentDependencies[dep])` (`parseRange` is exported from 'semver-utils')
- upgradedVersion - `result.version` (available in scope; see below)

I think the best place to filter the upgraded packages is after `queryVersions` is called, here:

https://github.com/raineorshine/npm-check-updates/blob/c5100fc93088d78110b81f93e9d8d984ab4ee0de/src/lib/upgradePackageDefinitions.ts#L27-L32

You can add `&& (!options.filterResults || options.filterResults(...))` to the `keyValueBy` and it will filter out upgrades that fail the predicate.

Let me know if you need any additional guidance!

**Comment by mslowiak** [comment]
Wow, that is amazing @raineorshine 🚀 

I will take a detailed look into code, probably on the weekend.
Thanks for the tips! I will get back to you if I spot any obstacles or have related questions!
