### ISSUE TITLE
global pnpm check 'no dependencies'

### ISSUE THREAD

**Issue by ekwoka** [raineorshine/npm-check-updates#1292]
![Screenshot 2023-04-05 at 10 56 51 AM](https://user-images.githubusercontent.com/43540491/230004356-bf2eda1e-fab1-49c7-817f-cd6f37a0a922.png)

When running `ncu -gp pnpm` it finds no dependencies. This started, as far as I can tell only in the last day or two.

Could this be related to the updates in pnpm 8? As you can see, it seems to have no found updates to even see that ncu is updated  (manually updating that one did not fix it)

`ncu -g` still works fine.

**Comment by raineorshine** [comment]
Oops! That must be a regression. Thanks for letting me know. I will look into it.

**Comment by raineorshine** [comment]
Here's what happened: Commit 09c9680 added the ability to override boolean options in the cli, e.g. `--peer false`. This was done by adding an optional variable to the commander.js option for each boolean option. Unfortunately this broke the use of combining boolean and non-boolean short flags.

I have reverted the offending commit and published a patch to `v16.10.3`.

**Comment by ekwoka** [comment]
Confirmed, works :D

**Comment by raineorshine** [comment]
@diegocr It's not related to this issue, but it is possible there was a different regression. It's going to be tough to identify without a minimum reproduction case, but if you open a new issue I can provide some troubleshooting tips.

**Comment by diegocr** [comment]
Thanks for the prompt response.

Just thought about running `ncu --verbose -g` and found where the problem is, there i do see a `options.prefix` pointing to `%APPDATA%\npm` but that path here _doesn't exists_ (because nodejs is not installed on the system drive, as pointed)

I made a symlink and got `ncu -g` working again, but... perhaps ncu should be using the `NODE_PATH` environment variable for this "prefix" value (?)

**Comment by raineorshine** [comment]
@diegocr Thanks! That's very informative.

Yes, if you could create a new ticket with that information we can track it there. I will think if there could be any regressions, but it makes sense to use `NODE_PATH` if it exists.

**Comment by diegocr** [comment]
Here you go: https://github.com/raineorshine/npm-check-updates/issues/1315

Cheers :)
