### ISSUE TITLE
Error installing from npm - "git dep preparation failed"

### ISSUE THREAD

**Issue by cwilby** [raineorshine/npm-check-updates#1296]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14` (Tested with 16, 18, 19 and 20 via `nvm`)

---

## Steps to Reproduce

.ncurc: n/a
Dependencies: n/a
Steps:

* Install node via `nvm`
* Run `npm install -g npm-check-updates`

```
➜  ~ npm install -g npm-check-updates
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm ERR! code 127
npm ERR! git dep preparation failed
npm ERR! command /home/cwilby/.nvm/versions/node/v16.20.0/bin/node /home/cwilby/.nvm/versions/node/v16.20.0/lib/node_modules/npm/bin/npm-cli.js install --force --cache=/home/cwilby/.npm --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! code 127
npm ERR! npm ERR! path /home/cwilby/.npm/_cacache/tmp/git-cloneNvgbTd
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command sh -c -- npm run compile
npm ERR! npm ERR! > cliui@8.0.1 precompile
npm ERR! npm ERR! > rimraf build
npm ERR! npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm ERR! sh: 1: rimraf: not found
```

**Comment by plumduffer** [comment]
Also having this issue. Node 18.16.0

**Comment by dearhxtan** [comment]
I got the same error on npm version 18.16.0 and 16.19.1, but when i change the npm version to 17.9.1, it success, please try this.

**Comment by 6XGate** [comment]
It seems there is a circular dependencies between `cliui` -> `rimraf` -> `glob` -> `jackspeak` -> `cliui`

I started having this issue with `npm-check-updates`

**Comment by 6XGate** [comment]
This might be related: https://github.com/isaacs/jackspeak/issues/4 ?

**Comment by isaacs** [comment]
Fixed, issue explained here: https://github.com/isaacs/jackspeak/issues/4#issuecomment-1530821526

**Comment by cwilby** [comment]
Amazed.  Thanks all.
