### ISSUE TITLE
ncu ERR_INVALID_ARG_TYPE timeout epects number, interprets as string, with timeout in .npmrc

### ISSUE THREAD

**Issue by Leif-W** [raineorshine/npm-check-updates#1303]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- Recently closed issue #1295 may be related, but fixed the ncu --timeout CLI option for ncu v16.10.9. [clarify]
- [x] I am using the latest version of `npm-check-updates`
- v16.10.12 is the latest I can pull from npm.
- [x] I am using `node >= 14.14`
- node v20.1.0 [wrote wrong number by accident, npm was v9.6.6]

---

## Steps to Reproduce

Windows 10 x64

`%USERPROFILE%\.npmrc`: [fixed unescaped dir path separator typo]

```js
timeout=2147483647
prefer-offline=true
```

Dependencies:

None

Steps:

1. Windows 10 x64 OS
2. Fresh nodejs install, meaning previous versions uninstalled, all cruft folders manually deleted, no stale files anywhere, but registry not fully scrubbed
3. Fresh ncu global install using `npm i -g npm-check-updates`
4. .npmrc as noted above
5. Run `ncu -g` under admin cmd.exe

## Current Behavior
```cmd
[19:28:57] C:\ -> ncu -g
[--------------------] 0/3 0%TypeError [ERR_INVALID_ARG_TYPE]: The "timeout" argument must be of type number. Received type string ('500')
    at new NodeError (node:internal/errors:399:5)
    at validateNumber (node:internal/validators:178:11)
    at getTimerDuration (node:internal/timers:396:3)
    at new ClientRequest (node:_http_client:198:20)
    at request (node:https:364:10)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm-registry-fetch\node_modules\minipass-fetch\lib\index.js:98:17
    at new Promise (<anonymous>)
    at fetch (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm-registry-fetch\node_modules\minipass-fetch\lib\index.js:55:10)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\npm-registry-fetch\node_modules\make-fetch-happen\lib\remote.js:51:23
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\npm-check-updates\node_modules\promise-retry\index.js:29:24 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

## Expected Behavior

Expect no errors, proper parsing of .npmrc options, specifically numbers to be parsed as numbers rather than strings.  As it's a fresh install, then `ncu -g` should have no output.  If used in an environment staged with outdated global packages, then `ncu -g` should output info about updates available.

**Comment by raineorshine** [comment]
npm-check-updates does not support INI config files. Please use yaml, json, or js.

yaml:

```yml
timeout: 2147483647
```

json:

```json
{
  "timeout": 2147483647
}
```

js:

```js
module.exports = {
  timeout: 2147483647
}
```

**Comment by Leif-W** [comment]
> npm-check-updates does not support INI config files. Please use yaml, json, or js.

Actually, I just noticed, the error message says

`Received type string ('500')`

But I have not configured 500 anywhere.  So it must come from somewhere else.  Does npm-check-updates use '500' as a hard-coded timeout somewhere?  I only assumed the timeout was somehow pulled from .npmrc, but perhaps it never even came from there.  .npmrc is the documented way to configure npm, as far as I understand.

**Comment by raineorshine** [comment]
npm-check-updates does not use a hardcoded 500 anywhere.

May be it's a default value in one of the dependencies? However, I just checked the codebase for npm-registry-fetch, make-fetch-happen, and minipass-fetch and '500' does not appear anywhere.

Just to confirm, you still get this error even after you change your config file to YAML or JSON format? Because trying to use an unsupported INI format could potentially result in unexpected decoding errors.

**Comment by Leif-W** [comment]
It's the global .npmrc.  npm does not use any other config file.  .npmrc is the only documented config file I see anywhere.

https://docs.npmjs.com/cli/v9/configuring-npm/npmrc

In this case, I'm not using any project.  It's a fresh node.js install.  No other packages installed globally, besides whatever npm-check-updates required.  I have no .ncurc.* anywhere on system, nor any timeout option explicitly set to 500, and the documented defaults are usually 60 or 300s, not 500.  So Im not sure where the number comes from, maybe hard-coded in npm somewhere?

I've discovered an error.

I think either .npmrc used to have a timeout option (now it's fetch-timeout), or npm-check-updates used to interpret the .npmrc option correctly (possibly by accident?), as this used to work.  I changed the .npmrc option from timeout to fetch-timeout, and the npm-check-updates error went away.  npm may have been emitting the error?  Rather than give an "unrecognized option" message, which would have been helpful, npm maybe silently interpreted the unknown option as a string... ?  But npm used by itself gives no errors and properly functioned (maybe silently ignored?) the unknown timeout option.  So the error message only manifests when using npm-check-updates.

I'd have to dig deeper to figure out exactly what is happening.

**Comment by raineorshine** [comment]
> It's the global .npmrc. npm does not use any other config file. .npmrc is the only documented config file I see anywhere.

My apologies, I misunderstood. I read .ncurc rather than .npmrc! .ncurc also has a timeout option. (Apparently my brain does not read every character after 9pm. Definitely a bug.)

> I think either .npmrc used to have a timeout option (now it's fetch-timeout), or npm-check-updates used to interpret the .npmrc option correctly (possibly by accident?), as this used to work. I changed the .npmrc option from timeout to fetch-timeout, and the npm-check-updates error went away. npm may have been emitting the error? Rather than give an "unrecognized option" message, which would have been helpful, npm maybe silently interpreted the unknown option as a string... ? But npm used by itself gives no errors and properly functioned (maybe silently ignored?) the unknown timeout option. So the error message only manifests when using npm-check-updates.

Thanks, that's very informative.

npm-check-updates reads the npmrc through the [libnpmconfig](https://github.com/npm/libnpmconfig) library (old but reliable) and normalizes the keys before feeding it back into the npm that is spawned. Because the npmrc values all get read in a strings initially, they need to be coerced to the correct types before being passed to npm. You can see where [fetch-timeout](https://github.com/raineorshine/npm-check-updates/blob/e66f04f47e4cde2eb02ace836c6ac410b66a8f55/src/package- managers/npm.ts#L125) is being parsed as a number. **Because `timeout` is not a known npm config key, it gets read and passed through as a string**. I am guessing that the behavior changed in a newer version of npm. Still doesn't explain where the 500 is coming from exactly, but it points towards the problem.

**Comment by pharapeti** [comment]
A temporary workaround to this issue is to specify the `--timeout` argument yourself.

```
npx npm-check-updates --timeout 60000
```

This at least allows you to use the tool, even though I agree a chance is required to better parse existing configs.

**Comment by raineorshine** [comment]
While `timeout` is not a valid npm config option, it does seem to get passed through pacote and parsed by `minipass-fetch`.

Fwiw, I made parse `timeout` as a number and published to `v16.10.14`. Hopefully that helps, but please be mindful of the [valid npm config settings](https://docs.npmjs.com/cli/v9/using-npm/config#config-settings). npm-check-updates parses but does not validate npmrc settings in order to stay flexible and future-compatible.

**Comment by Leif-W** [comment]
I can't remember precisely now.  But the issue was, I had a `timeout` setting in .npmprc (same as `--timeout` on the CLI) that previously worked in npm, and was silently either working or ignored by npm, but when using ncu, something complained about the option not being valid.  So the suggestion to use `--timeout` on the CLI, will give the same problem.  There is no `--timeout` option anymore, as far as I can see from the npm docs.  It's `--fetch-timeout`.

I changed the .npmrc option name to fetch-timeout, and things worked, or at least went back to silently working or failing.

`C:\Users\<USERNAME>\.npmrc`
```
fetch-timeout=2147483646
prefer-offline=true
```

`C:\Users\<USERNAME>\.ncurc.json`
```
{
    "timeout": 2147483646
}
```

The odd odd thing here.... The biggest positive number in JS is 2147483647 (2^31-1).  I can put 2147483647 in .npmrc and `npm` behaves properly.  But if I use ncu, I get an error that ncu's `timeout` option must be a number, not a string.  So I must specify 2147483646 in .ncurc.json, but if 2147483647 still exists in .npmrc, I get an error.  So I must set 2147483646 in both fetch-timeout in .npmrc, and timeout in .ncurc.json.  Weird, even the weirdness is weirdly weird.  But ok.  :)  It's been working like this with both configs set to 2^31-2.

**Comment by raineorshine** [comment]
@Leif-W Is that above still true with npm-check-updates `v16.10.14`?

**Comment by Leif-W** [comment]
Here is a comparison of ncu v16.10.13 and v16.10.15 in Termux.

Note: I have .npmrc with fetch-timeout=2147483647, which by itself, `ncu -g` runs without error, but (maybe?) ignores fetch timeouts.  When I set .ncurc.json with `timeout` set to `2147483647`, I got the warning below.  For some reason, 1 is added to whatever is set in timeout, turning a valid number into an invalid numbee.

**v16.10.13**

```
Using config file /data/data/com.termux/files/home/.ncurc.json
[--------------------] 0/5 0%(node:22346) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22346) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:22346) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:22346) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:22346) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:22346) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[====----------------] 1/5 20%(node:22346) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[========------------] 2/5 40%(node:22346) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[============--------] 3/5 60%(node:22346) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[================----] 4/5 80%(node:22346) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[====================] 5/5 100%

 npm-check-updates  16.10.13  →  16.10.15

ncu itself cannot upgrade global packages. Run the following to upgrade all global packages:

npm -g install npm-check-updates@16.10.15
```

Now I run the upgrade, and `ncu -g` again.

**v16.10.15**

```
[03:33:24] ~/storage/downloads -> ncu -g                          Using config file /data/data/com.termux/files/home/.ncurc.json
[--------------------] 0/5 0%(node:25198) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25198) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:25198) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:25198) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:25198) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
(node:25198) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[====----------------] 1/5 20%(node:25198) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[========------------] 2/5 40%(node:25198) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[============--------] 3/5 60%(node:25198) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[================----] 4/5 80%(node:25198) TimeoutOverflowWarning: 2147483648 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.
[====================] 5/5 100%

All global packages are up-to-date :)
```

Tried using .npmrc option `node-options=--trace-warnings` but `ncu -g` seems to ignore this.  I maybe misunderstood, but I thought ncu calls npm at some point?  At which point, npm should read .npmrc?  What is calling node here, and how do I inject the --trace-warning option?

I know this is an edge case, but it reveals something interesting in that +1 is silently added somewhere.  I realize the error may be coming from a dependency of ncu and not ncu proper.  But I am unsure how to get a finer grain of detail to identify the offending code.

npm debug log likewise doesn't show much interesting, except node is calling npm, bu there's no --trace-warning option.

```0 verbose cli /data/data/com.termux/files/usr/bin/node /data/data/com.termux/files/usr/bin/npm
1 info using npm@9.8.0
2 info using node@v20.2.0
3 timing npm:load:whichnode Completed in 5ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/data/data/com.termux/files/usr/lib/node_modules/npm/npmrc Completed in 9ms
6 timing config:load:builtin Completed in 9ms
7 timing config:load:cli Completed in 6ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 36ms
10 timing config:load:file:/data/data/com.termux/files/home/.npmrc Completed in 7ms
11 timing config:load:user Completed in 8ms
12 timing config:load:file:/data/data/com.termux/files/usr/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 1ms
14 timing config:load:setEnvs Completed in 3ms
15 timing config:load Completed in 68ms
16 timing npm:load:configload Completed in 68ms
17 timing config:load:flatten Completed in 4ms
18 timing npm:load:mkdirpcache Completed in 3ms
19 timing npm:load:mkdirplogs Completed in 4ms
20 verbose title npm ls
21 verbose argv "ls" "--depth" "0" "--location" "global" "--json"
22 timing npm:load:setTitle Completed in 1ms
23 timing npm:load:display Completed in 1ms
24 verbose logfile logs-max:10 dir:/data/data/com.termux/files/home/.npm/_logs/2023-07-08T07_40_02_476Z-
25 verbose logfile /data/data/com.termux/files/home/.npm/_logs/2023-07-08T07_40_02_476Z-debug-0.log
26 timing npm:load:logFile Completed in 15ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 120ms
30 timing config:load:flatten Completed in 0ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile done cleaning log files
33 timing command:ls Completed in 649ms
34 verbose exit 0
35 timing npm Completed in 821ms
36 info ok
```

**Comment by raineorshine** [comment]
> Tried using .npmrc option `node-options=--trace-warnings` but `ncu -g` seems to ignore this. 

It works if you invoke ncu's binary directly with node. However, the trace will show where the fetch is called, not where the HTTP agent's options object is created, which is what we need.

```
node --trace-warnings /Users/raine/projects/npm-check-updates/build/src/bin/cli.js
```

> I maybe misunderstood, but I thought ncu calls npm at some point? At which point, npm should read .npmrc? What is calling node here, and how do I inject the --trace-warning option?

ncu only spawns npm for `npm ls`. Dependency versions are fetched directly from the registry via [pacote](https://github.com/npm/pacote). The call trace of the final HTTP request looks like this:

```
npm-check-updates
└─┬ pacote
  └─┬ npm-registry-fetch
    └── make-fetch-happen
```

> I know this is an edge case, but it reveals something interesting in that +1 is silently added somewhere. I realize the error may be coming from a dependency of ncu and not ncu proper. But I am unsure how to get a finer grain of detail to identify the offending code.

Sometimes some good ol' fashioned console.logs in node_modules are needed. Looks like the `+ 1` originates in `make-fetch-happen`:

> // If opts.timeout is zero, set the agentTimeout to zero as well. A timeout
> // of zero disables the timeout behavior (OS limits still apply). Else, if
> // opts.timeout is a non-zero value, set it to timeout + 1, to ensure that
> // the node-fetch-npm timeout will always fire first, giving us more
> // consistent errors.

https://github.com/npm/make-fetch-happen/blob/ca263783e05bef2be349ee8f5096b59dab7d9116/lib/agent.js#L23-L28

**Comment by Leif-W** [comment]
Ah!  Thank you for this!  I'll redirect further questions to make-fetch-happen.  I'll just finish this with a note about the function that takes this action (the link above is a comment block below the anonymous function definition).

```
const getAgentTimeout = timeout =>
  typeof timeout !== 'number' || !timeout ? 0 : timeout + 1
```

The offending code seems problematic for a couple reasons to me.  It only checks if a number is non-zero, and assumes all non-zero numbers are positive.  A negative number will be made only slightly less negative, and I'm not sure if that will yield an error elsewhere, or undefined behavior.  A negative timeout is always timed out before the call is even made?  ;)  Or ...

And then there's modifying a number out of type limit without any checks, which causes errors if the number is already at MAX_INT.  There's further no explanation about this "always fire first" notion.  What are we competing against, and why would a timeout fire second?  And how does this relate to "consistency" of errors?

Thank you for your time, much appreciated.
