### ISSUE TITLE
No readme on npmjs.com

### ISSUE THREAD

**Issue by matthew-dean** [raineorshine/npm-check-updates#1307]
Not sure why, but the README.md is not visible when finding this package via npmjs.com:

https://www.npmjs.com/package/npm-check-updates

**Comment by srflp** [comment]
I see it
![Screenshot_20230629_173128](https://github.com/raineorshine/npm-check-updates/assets/17103865/204cbc30-67a0-4f69-9157-056cd9d12c4e)

**Comment by raineorshine** [comment]
It seems to be back now. Must have been an npm issue.
