### ISSUE TITLE
Doctor with pnpm doesn't work

### ISSUE THREAD

**Issue by ekwoka** [raineorshine/npm-check-updates#1308]
- [] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [] I am using the latest version of `npm-check-updates`
- [] I am using `node >= 14.14`

---

## Steps to Reproduce

use pnpm

have a situation where upgrading with doctor fails

see it the fails every time

Reason: `ERR_PNPM_OPTION_NOT_SUPPORTED  The "add" command currently does not support the no-save option`

Further, it doesn't seem to respect the custom install command. It always does `pnpm install --no-save` even if the command provided is `pnpm i`

Steps:

## Current Behavior

`ERR_PNPM_OPTION_NOT_SUPPORTED  The "add" command currently does not support the no-save option`

It doesn't work

## Expected Behavior

That it works.

**Comment by raineorshine** [comment]
I got doctor mode working with a basic pnpm setup. Let me know if it works for you.

Published to `v16.10.16`.

**Comment by ekwoka** [comment]
🎉 Amazing!
