### ISSUE TITLE
feat: skip install question 

### ISSUE THREAD

**Issue by EinfachHans** [raineorshine/npm-check-updates#1316]
## Feature Request

A mentioned in #1312 i would like to be able to skip the "Do you want to npm install?" question. Is there really a case where someone wants to edit the version in the package json but not run the install command? 🤔

In [npm-check](https://github.com/dylang/npm-check) what i used before, where no more work is done, this was handled differently by only install the changed / selected versions like `npm install package-a@1.0.1 package-b@2.9.3 ...`. By that you also don't have to edit the package.json files because npm would do this automatically - Maybe a better approach?

**Comment by raineorshine** [comment]
> A mentioned in #1312 i would like to be able to skip the "Do you want to npm install?" question. Is there really a case where someone wants to edit the version in the package json but not run the install command? 🤔

I can add an option to automatically install. Some people prefer to verify the package.json by hand or do other things before installing, so that will remain the default behavior.

> In [npm-check](https://github.com/dylang/npm-check) what i used before, where no more work is done, this was handled differently by only install the changed / selected versions like `npm install package-a@1.0.1 package-b@2.9.3 ...`. By that you also don't have to edit the package.json files because npm would do this automatically - Maybe a better approach?

Decoupling the package.json modification from the npm install is an important feature that gives developers more flexibility to build tools that upgrade versions and make various recommendations. Hopefully the above option will be adequate for your needs.

**Comment by raineorshine** [comment]
Added in `v16.13.0`


## install

Usage:

    ncu --install [value]

Default: prompt

Control the auto-install behavior.

<table>
  <tr><td>always</td><td>Runs your package manager's install command automatically after upgrading.</td></tr>
  <tr><td>never</td><td>Does not install and does not prompt.</td></tr>
  <tr><td>prompt</td><td>Shows a message after upgrading that recommends an install, but does not install. In interactive mode, prompts for install. (default)</td></tr>
</table>

**Comment by atheck** [comment]
That's great. Thank you very much!

**Comment by EinfachHans** [comment]
Work's great! Thanks for the quick work 😊

Only addition: I use `install: 'always'` and after the interactive selection the package prints: "All dependencies match the latest package versions :)" and waits while installing the dependency. That's not 100% correct, maybe better print something like "Installing dependencies..." instead?

**Comment by raineorshine** [comment]
@EinfachHans Good point. Added to `v16.13.1`.

**Comment by EinfachHans** [comment]
Nice one, thanks a lot!
