### ISSUE TITLE
ncu is not working with a private registry anymore

### ISSUE THREAD

**Issue by sh4nks** [raineorshine/npm-check-updates#1323]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates` --> 16.13.2
- [x] I am using `node >= 14.14` --> v18.12.1

Hi!
I have been using your tool to manage my dependencies. However it is not registering package updates from my private registry.
I am using a self signed certificate if that info helps. When I am trying to directly specify the registry I get this error (otherwise it runs fine but doesn't display the updates from the private registry):
```
ncu --registryType json --registry https://example-registry/

[--------------------] 0/73 0%FetchError: request to https://example-registry/ failed, reason: self-signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\global\path\to\npm-repository\node_modules\npm-check-updates\node_modules\minipass-fetch\lib\index.js:130:14)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:525:35)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN',
  errno: 'SELF_SIGNED_CERT_IN_CHAIN',
  type: 'system'
}
```
In my .npmrc and .yarnrc I have set ``strict-ssl`` to ``false``

---

## Steps to Reproduce

Steps:

## Current Behavior

ncu output:

```
typescript  ~5.1.6  →  ~5.2.2
```

## Expected Behavior

```
@my-namespace/my-dependency ^15.0.0   →  ^16.0.0
typescript  ~5.1.6  →  ~5.2.2
```

Thanks!

**Comment by sh4nks** [comment]
It works now. I am not exactly sure what the problem was.

**Comment by raineorshine** [comment]
Glad it's working. Let me know if you run into it again!
