### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/etc/ssl/certs/ca-certificates.crt'

### ISSUE THREAD

**Issue by andykotov** [raineorshine/npm-check-updates#1335]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce

.ncurc:

```js

```

Dependencies:

```
"dependencies": {
    "@lottiefiles/react-lottie-player": "3.5.3",
    "@primer/octicons-react": "16.3.1",
    "bootstrap": "5.3.2",
    "env-cmd": "10.1.0",
    "express": "4.18.2",
    "firebase": "9.23.0",
    "jest-canvas-mock": "2.5.2",
    "jquery": "3.7.1",
    "q2-tecton-sdk": "1.30.1",
    "react": "^17.0.2",
    "react-bootstrap": "2.9.0",
    "react-day-picker": "7.4.10",
    "react-dom": "17.0.2",
    "react-lottie": "1.2.3",
    "react-plaid-link": "3.4.0",
    "react-range-slider-input": "3.0.7",
    "react-router-dom": "5.3.4",
    "react-scripts": "4.0.3",
    "react-spring": "8.0.27",
    "react-switch": "6.1.0",
    "react-vis": "1.12.1",
    "round-slider": "1.6.1",
    "storage-factory": "0.1.1"
  },
  "devDependencies": {
    "@testing-library/jest-dom": "5.17.0",
    "@testing-library/react": "12.1.5",
    "mocha": "9.2.2"
  }
```

Steps:

Mac-mini:q2-web-app Hakoda$ npm install -g npm-check-updates
Mac-mini:q2-web-app Hakoda$ ncu

## Current Behavior

Mac-mini:q2-web-app Hakoda$ ncu
node:internal/fs/utils:352
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/etc/ssl/certs/ca-certificates.crt'
    at readFileSyncUtf8 (node:internal/fs/read/utf8:20:3)
    at Object.readFileSync (node:fs:466:12)
    at cafile (/usr/local/lib/node_modules/npm-check-updates/build/src/package-managers/npm.js:69:41)
    at /usr/local/lib/node_modules/npm-check-updates/build/src/package-managers/npm.js:179:28
    at /usr/local/lib/node_modules/npm-check-updates/build/src/lib/keyValueBy.js:14:15
    at Array.forEach (<anonymous>)
    at keyValueBy (/usr/local/lib/node_modules/npm-check-updates/build/src/lib/keyValueBy.js:11:33)
    at normalizeNpmConfig (/usr/local/lib/node_modules/npm-check-updates/build/src/package-managers/npm.js:162:48)
    at /usr/local/lib/node_modules/npm-check-updates/build/src/package-managers/npm.js:213:43
    at monadic (/usr/local/lib/node_modules/npm-check-updates/node_modules/fast-memoize/src/index.js:37:24) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/etc/ssl/certs/ca-certificates.crt'
}

Node.js v20.7.0

## Expected Behavior

Checking the package.json file

**Comment by raineorshine** [comment]
Hi, thanks for reporting. Can you post the output of `ncu --verbose`?

The issue is related to the npm config for `cafile`. It is reading the path `/etc/ssl/certs/ca-certificates.crt` from somewhere, but the file does not exist. Do you have any more information about your `cafile` setup that might help us identify the problem?

**Comment by andykotov** [comment]
```
Mac-mini:q2-web-app Hakoda$ ncu --verbose
node:internal/fs/utils:352
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/etc/ssl/certs/ca-certificates.crt'
    at readFileSyncUtf8 (node:internal/fs/read/utf8:20:3)
    at Object.readFileSync (node:fs:466:12)
    at cafile (/usr/local/lib/node_modules/npm-check-updates/build/src/package-managers/npm.js:69:41)
    at /usr/local/lib/node_modules/npm-check-updates/build/src/package-managers/npm.js:179:28
    at /usr/local/lib/node_modules/npm-check-updates/build/src/lib/keyValueBy.js:14:15
    at Array.forEach (<anonymous>)
    at keyValueBy (/usr/local/lib/node_modules/npm-check-updates/build/src/lib/keyValueBy.js:11:33)
    at normalizeNpmConfig (/usr/local/lib/node_modules/npm-check-updates/build/src/package-managers/npm.js:162:48)
    at /usr/local/lib/node_modules/npm-check-updates/build/src/package-managers/npm.js:213:43
    at monadic (/usr/local/lib/node_modules/npm-check-updates/node_modules/fast-memoize/src/index.js:37:24) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/etc/ssl/certs/ca-certificates.crt'
}

Node.js v20.7.0
Mac-mini:q2-web-app Hakoda$ npm config get cafile
/etc/ssl/certs/ca-certificates.crt
Mac-mini:q2-web-app Hakoda$ ls /etc/ssl/certs/ca-certificates.crt
ls: /etc/ssl/certs/ca-certificates.crt: No such file or directory
Mac-mini:q2-web-app Hakoda$ npm config list
; "user" config from /Users/Hakoda/.npmrc

cafile = "/etc/ssl/certs/ca-certificates.crt" 
legacy-peer-deps = false 
save-exact = true 
save-prefix = "" 

; node bin location = /usr/local/bin/node
; node version = v20.7.0
; npm local prefix = /Users/Hakoda/Documents/changed-javascript/web-apps/q2-web-app
; npm version = 10.1.0
; cwd = /Users/Hakoda/Documents/changed-javascript/web-apps/q2-web-app
; HOME = /Users/Hakoda
; Run `npm config ls -l` to show all defaults.
Mac-mini:q2-web-app Hakoda$ echo $NODE_EXTRA_CA_CERTS

Mac-mini:q2-web-app Hakoda$
```

**Comment by raineorshine** [comment]
Thanks. It looks like you can solve the problem either by adding a valid certificate at `/etc/ssl/certs/ca-certificates.crt`, or by removing the cafile entry from your npm config.

**Comment by andykotov** [comment]
Could you please tell me how to do this?

**Comment by raineorshine** [comment]
You can open `~/.npmrc` in your editor and remove the cafile line. It's not being used anyway since the file does not exist.

**Comment by andykotov** [comment]
It's working, thank you.
