### ISSUE TITLE
Inadequate documentation for rejectVersion

### ISSUE THREAD

**Issue by jeffersoneagley** [raineorshine/npm-check-updates#1336]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce

.ncurc:

```json
{
  rejectVersion: [
    "react-router-dom>=6"
  ]
}
```

Dependencies:

```json
{
  "react-router-dom": "^5.3.3"
}
```

Steps:

## Current Behavior

`ncu` updates the version of `react-router-dom` to `6.X.X`.

## Expected Behavior

`ncu` only updates the version of `react-router-dom` to a `5.X.X` version (that does not meet the `>=6` version specified in the `.ncurc` file's rejection list).

There's basically no documentation about how to actually use `rejectVersion`. A paragraph stating the expected syntax and a couple of examples would help a lot.

**Comment by jeffersoneagley** [comment]
I'm basically trying to say "here's my list of things I don't want to do large breaking upgrades on yet, upgrade those to the next minor version, and then upgrade everything else to whatever".

**Comment by raineorshine** [comment]
> There's basically no documentation about how to actually use `rejectVersion`. A paragraph stating the expected syntax and a couple of examples would help a lot.

Yes, thank you! A glaring omission. I've added the following documentation to the README.

## rejectVersion

### Usage:

    ncu --rejectVersion [p]

The inverse of `--filterVersion`. Exclude versions matching the given string, wildcard, glob, comma-or-space-delimited list, /regex/, or predicate function.

The predicate function is only available in .ncurc.js or when importing npm-check-updates as a module, not on the command line. This function is an alias for the `reject` option function.

```js
/**
  @param name             The name of the dependency.
  @param parsedVersion    A parsed Semver object of the upgraded version.
    (See: https://git.coolaj86.com/coolaj86/semver-utils.js#semverutils-parse-semverstring)
  @returns                True if the package should be excluded, false if it should be included.
*/
filterVersionFunction: (name, parsedVersion) => {
  if (name.startsWith('@myorg/') && parseInt(parsedVersion?.major) > 5) {
    return true
  }
  return false
}
```

> I'm basically trying to say "here's my list of things I don't want to do large breaking upgrades on yet, upgrade those to the next minor version, and then upgrade everything else to whatever".

For this, I recommend defining a [`target`](https://github.com/raineorshine/npm-check-updates#target) predicate function. That allows you to apply the `minor` strategy and achieve the behavior you describe.

```js
/**
  @param name The name of the dependency.
  @param parsedVersion A parsed Semver object of the upgraded version.
    (See: https://git.coolaj86.com/coolaj86/semver-utils.js#semverutils-parse-semverstring)
*/
target: name => name === 'react-router-dom' ? 'minor' : 'latest'
}
```

**Comment by jeffersoneagley** [comment]
Thank you very much for the quick answer back!

For the moment, I just went with `target: minor` across the board (and plan to instruct my team to do all major version upgrades by hand, which is probably for the best anyways). 

I haven't made the jump from `.npmrc` as a json file to `.npmrc.js` yet, but it looks more and more like I probably should.

This, plus setting up "doctor mode" is going to make our dependency update story quite a bit more smooth!

**Comment by raineorshine** [comment]
> For the moment, I just went with `target: minor` across the board (and plan to instruct my team to do all major version upgrades by hand, which is probably for the best anyways).

Great! Note there is also `target: 'semver'.

> I haven't made the jump from `.npmrc` as a json file to `.npmrc.js` yet, but it looks more and more like I probably should.

It's a very simple switch. Just rename the file, add `module.exports = { ... }` and you're good to go. The only difference is that it adds support for some of the options that allow custom functions.

> This, plus setting up "doctor mode" is going to make our dependency update story quite a bit more smooth!

Yes, `doctor` mode has been a big time-saver for me on my other projects! Enjoy.

**Comment by bombillazo** [comment]
Hey! I too am having trouble understanding `reject` and `rejectVersion` usage, specifically in our `.ncurc` file.

When we run `ncu -i` we want to see the latest version (including mayor) **except** for some dep we know we cannot upgrade to mayor version. for those, we still want to see if the latest minor version has a new version.

**Comment by bombillazo** [comment]
Nevermind after rereading the thread I got it!
```js
module.exports = {
  target: (name) => {
    if(['chalk'].includes(name)) return 'minor';
    return 'latest';
  },
};

```

**Comment by zanona** [comment]
@raineorshine Could you please add an explanation to the README of how to setup an .js config? Also, perhaps mentioning that for more custom behaviour, we shouldn't be trying to use the json config variant?
Sorry, at the moment it's quite difficult to understand this. Specially because the README starts mentioning about a json config and then proceeds with only applying js snippets for the options... :confused:

**Comment by raineorshine** [comment]
@zanona Thanks for the suggestion! I've clarified the usage of config functions in the README by adding the following warning:

<img width="461" alt="Image" src="https://github.com/user-attachments/assets/1fc889c7-ccf8-4bf3-b294-79b5cac20ed1" />

I added a section that describes how to convert a JSON config to a JS config:

<img width="475" alt="Image" src="https://github.com/user-attachments/assets/c2419636-fc26-4297-ac69-04911ce87ddf" />

https://github.com/raineorshine/npm-check-updates#config-functions

Please let me know if there is anything else that could use improvement. Thanks!

**Comment by bombillazo** [comment]
Awesome! I agree, thats one of the things that confused me as well at first, this will help avoid those same assumptions.
