### ISSUE TITLE
Feature request: Synchronous API

### ISSUE THREAD

**Issue by Zamiell** [raineorshine/npm-check-updates#1338]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

Hello, and thanks for the excellent tool. In the README, it shows that the tool has an async API with e.g.:

```ts
import ncu from 'npm-check-updates'

const upgraded = await ncu.run()
```

However, using async is inconvenient, as async usage in complex scripts forces modification of an entire call stack upwards into async functions and forces insertion of `await` everywhere. Would you please consider adding a synchronous API? So that end-users could do:

```ts
import ncu from 'npm-check-updates'

const upgraded = await ncu.runSync()
```

That way, NCU would work similar to the Node API, e.g. `fs.exists` and `fs.existsSync`. It would be very appreciated.

**Comment by raineorshine** [comment]
Hi, thanks for your suggestion.

Unfortunately this is outside the scope of this package. While I recognize the ripple effect that this creates in the code, async has become standard in the JS world and is the recommended best practice in most circumstances.

As an alternative, you could run `npm-check-updates` in a child process using [spawnSync](https://nodejs.org/api/child_process.html#child_processspawnsynccommand-args-options).

**Comment by Zamiell** [comment]
I agree that "proper" JavaScript/TypeScript code should use `await`, but I think a common use case for NCU API is in a Bash-like script, e.g. something that is just running a bunch of tools in a row, one after the other, like NCU --> ESLint. So it kind of makes sense to provide a sync API in this context. (e.g. the tools all need to be run in order and can't be run in parrallel)

On the other hand, ESLint and Prettier are both similar-ish tools to NCU, and from what I can tell, they intentionally don't offer synchronous APIs, so I can understand your position. However, maybe you will reconsider this in the future.

Thanks, I will close this issue.
