### ISSUE TITLE
Library won't install anymore

### ISSUE THREAD

**Issue by felipe-ff** [raineorshine/npm-check-updates#1339]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---

## Steps to Reproduce
run: npm i -g npm-check-updates

## Current Behavior

Throws error: 
npm ERR! code E500
npm ERR! 500 Internal Server Error - GET https://registry.npmjs.org/@nodelib%2ffs.stat - KV GET failed: 401 Unauthorized

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Felipe\AppData\Local\npm-cache\_logs\2023-10-30T20_12_23_494Z-debug-0.log

## Expected Behavior

should install the library.

**Comment by raineorshine** [comment]
If it won't install, that’s an npm problem, not npm-check-updates. 

First check your npm config and registry settings. You're getting a 401 Not Authorized error from the public registry which is strange. Then try re-installing npm, and if that doesn't work re-install NodeJS.
