### ISSUE TITLE
[feature request] add changelog ( --format repo) to "ncu -i --format group"

### ISSUE THREAD

**Issue by GorvGoyl** [raineorshine/npm-check-updates#1340]
It would be more productive if i can access changelog ( `--format repo`) in  the same command `ncu -i --format group`

**Comment by raineorshine** [comment]
You can specify multiple format options with commas:

``` 
ncu --format group,repo
```

**Comment by GorvGoyl** [comment]
Thanks, i accidentally added space when i tried.
