### ISSUE TITLE
Upgrade breaking dependencies

### ISSUE THREAD

**Issue by raineorshine** [raineorshine/npm-check-updates#1352]
Remove dependencies from the [reject list](https://github.com/raineorshine/npm-check-updates/blob/82776d5033ff9068943d2b7571de800327702f9a/.ncurc.js#L3-L28), upgrade, and fix regressions.

**Comment by ElPrudi** [comment]
- @trivago/prettier-plugin-sort-imports already updated to prettier 3 and to my understanding, `eslint-plugin-import` also has a rule to sort imports
- get-stdin is deprecated in favor of [`streamConsumers.text`](https://nodejs.org/api/webstreams.html#streamconsumerstextstream)
- [glob](https://github.com/isaacs/node-glob) is faster than globby, supports both ESM and CommonJS and works in both browser and node
