### ISSUE TITLE
Feature: Update GitHub Actions

### ISSUE THREAD

**Issue by hildjj** [raineorshine/npm-check-updates#1360]
This is completely reasonable to call out of scope, if you prefer.

I'd like ncu to check all of the files in `.github/workflows/`, looking for lines like `uses: actions/checkout@v3`, then check that `v3` is the latest version.

The part before the @ is the GitHub repo name.  You can use this URL to get release information:

```
https://api.github.com/repos/${repo}/releases?per_page={max}
```

looking at the `tag_name` key.

For instance: https://api.github.com/repos/actions/checkout/releases?per_page=50

Some python code for reference is [here](https://github.com/saadmk11/github-actions-version-updater/blob/main/src/main.py).

Use case: I want to update all of my dependencies at the same time, including my CI framework, so that when something breaks, all of those changes are in the same PR.

**Comment by raineorshine** [comment]
Hi, thanks for the suggestion. 

I do think this is out of scope, namely because it differs from npm-check-updates in both the manifest format and the registry format.
