### ISSUE TITLE
Recent upgrade breaks ncu on mac

### ISSUE THREAD

**Issue by abrahamcuenca** [raineorshine/npm-check-updates#1369]
- x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 14.14`

---
<img width="1263" alt="image" src="https://github.com/raineorshine/npm-check-updates/assets/1010661/42635eb3-e6fd-451b-a6ae-da66453a1f04">

## Steps to Reproduce

Using ncu programmatically, try to use the library on a Mac.

```js
import ncu from 'npm-check-updates';

        const outdated = await ncu({
            packageData: pkgJson,
            deprecated: true,
            upgrade: false,
        })
```

Steps:

1. Using a mac install npm-check-updates with `npm i npm-check-updates`
2. Create a `main.js` file and import ncu with `import ncu from 'npm-check-updates`
3. Attempt to run ncu 

```js
        const outdated = await ncu({
            packageData: pkgJson,
            deprecated: true,
            upgrade: false,
        })
```

Notice the error:

```
 ⨯ ./node_modules/node-gyp/lib/Find-VisualStudio.cs
Module parse failed: Unexpected token (9:6)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| // This script needs to be compatible with PowerShell v2 to run on Windows 2008R2 and Windows 7.
| 
> using System;
| using System.Text;
| using System.Runtime.InteropServices;

Import trace for requested module:
./node_modules/node-gyp/lib/Find-VisualStudio.cs
./node_modules/node-gyp/lib/ sync ^\.\/.*$
./node_modules/node-gyp/lib/node-gyp.js
./node_modules/node-gyp/bin/node-gyp.js
./node_modules/@npmcli/run-script/lib/make-spawn-args.js
./node_modules/@npmcli/run-script/lib/run-script-pkg.js
./node_modules/@npmcli/run-script/lib/run-script.js
./node_modules/pacote/lib/dir.js
./node_modules/pacote/lib/index.js
./node_modules/npm-check-updates/build/src/package-managers/npm.js
./node_modules/npm-check-updates/build/src/lib/doctor.js
./node_modules/npm-check-updates/build/src/index.js
```

## Current Behavior

It seems that the latest version of npm-check-updates is looking for visual studio as part of node-gyp. Perhaps the newer version of node-gyp is causing the issue however I did not run into this issue with the previous version of npm-check-updates (15.3.4) which had its own bug related to typescript and `version` being declared twice.

## Expected Behavior

- No Typescript errors
- No Visual Studio errors on mac

**Comment by raineorshine** [comment]
Hi, thanks for reporting.

I have followed the steps you describe, and I am not able to reproduce the issue. Other than needing to change `ncu({ ... })` to `ncu.run({ ... })` your code example works correctly for me and I'm not seeing any errors. Tested on node `v20.11.0`.

If you have a sample repo that reproduces the issue, I'm happy to test it on my machine. However it is most likely an npm install error rather than a bug in npm-check-updates. I would try recreating your node_modules and see if that fixes it.

**Comment by abrahamcuenca** [comment]
Thank you for reviewing. Perhaps it may have something to do with my environment. I'm on an M1 mac and things have been a bit buggy at times with different packages. It seems to be more of a node-gyp issue.

Appreciate the support! I'll close this out for now.

**Comment by raineorshine** [comment]
Yes, and if you get stuck, even consider a new node install. I use [fnm](https://github.com/Schniz/fnm) and love it.
