### ISSUE TITLE
[Feature] Exclude dependency from being considered for --peer checking

### ISSUE THREAD

**Issue by CreativeTechGuy** [raineorshine/npm-check-updates#1370]
I have a monorepo where all dependencies are installed by the root package.json and the sub-packages in the repo have their own package.json's with the dependencies/peerDependencies that they use which is needed for publishing those libraries. The versions are synced such that the version in the root package.json is the same as the version which appears in any sub-package in the repo.

Now several of these libraries inside the monorepo are built and installed at the root package.json.

File structure to visualize:

```
package.json (lists libraryA as a dependency)
packages/
    libraryA/
        package.json
    libraryB/
        package.json
```

The problem with this comes when using `--peer` with NCU. When trying to update the root package.json, it looks at the dependencies and will find that it depends on libraryA, then looks at what version it expects as a `peerDependency` (which will always be the same version as it appears currently in the root package.json) and then NCU determines that the dependency cannot be updated.

In reality, what we want to happen is that we can selectively exclude certain dependencies from the peer check because we know that we are going to immediately go and update those libraries' peerDependencies as soon as we update.

The best workaround currently is to delete these local packages from node_modules before running NCU, causing NCU peer to fail to find it and effectively skip it like we want. That feels really hacky.

Is it possible to get an option to specify packages which should be skipped when determining peer dependencies?

**Comment by raineorshine** [comment]
Hi, thanks for the suggestion.

Is it possible to upgrade the peerDependencies first before upgrading the root package? Is it possible to run ncu without `--peer`, or only with `--peer` on specific packages (i.e. run ncu multiple times with different options)?.

At the current time it is unlikely that I would add new options related to `--peer` unless many users agreed with this need and demonstrated that they have a similar monorepo setup. ncu can be imported as a module in order to provide more complex behavior in specific scenarios.

**Comment by CreativeTechGuy** [comment]
For posterity, here's the code change (untested) that I was thinking. (If this ever gets enough attention to be added.)


```diff
// src/lib/getPeerDependencies.ts
async function getPeerDependencies(current: Index<VersionSpec>, options: Options): Promise<Index<Index<string>>> {
  const basePath = options.cwd || './'
  const accum: Index<Index<string>> = {}

  for (const dep in current) {
+    if (options.skipPeer.includes(dep)) {
+        continue;
+    }
    const path = basePath + `node_modules/${dep}/package.json`
    let peers: Index<string> = {}
    try {
      const pkgData = await fs.readFile(path, 'utf-8')
      const pkg = jph.parse(pkgData)
      peers = getCurrentDependencies(pkg, { ...options, dep: 'peer' })
    } catch (e) {
      print(options, `Could not read peer dependencies for package ${dep}. Is this package installed?`, 'warn')
    }
    accum[dep] = peers
  }

  return accum
}
```

Basically it'd just be an array of strings which would be the new argument, and if the dependency matches, then it is skipped.

> As an alternative, ncu can be imported as a module in custom tooling in order to provide more complex behavior for specialized use cases.

Since the behavior that I want changed is internal, I don't see a way to get what I'm looking for even when using ncu as a module. Let me know if I'm missing something. I guess the way to do it would be to opt-out of NCU's peer feature entirely, get the full results of tentative packages, and then filter that output against my own crawling of peer dependencies. That seems annoying. 😅

Thank you for your reply and consideration! I'm interested to see if anyone else can relate to this problem.

**Comment by raineorshine** [comment]
Let's say you want to do something like `ncu --peer --skipPeer libraryA`. What is the difference between that and `ncu --peer --reject libraryA ; ncu libraryA`?

**Comment by CreativeTechGuy** [comment]
That actually works perfect. Just `--peer --reject libraryA` is exactly what I wanted (where `libraryA` is the library local to my monorepo).

I didn't realize that `--reject` actually removed that package from consideration for the entire NCU process. I thought it was just a filter at the end where if there was an update, you would just reject that update.

So let me know if my understanding of `--reject` is correct now. It seems like `--reject` removes the specified packages from being analyzed completely. So it actually prunes that entire section of the dependency tree because it doesn't consider peers of a rejected dependency either.

----

Now I wonder what to use for what I previously thought reject was doing. I guess `--filterResults` is doing what I thought `--reject` was doing.

Thank you for explaining that. It wasn't very clear to me what `--reject` did.

**Comment by raineorshine** [comment]
`--reject` and `--filter` remove dependencies from consideration before fetching updates. (It makes sense for performance reasons to not fetch the latest version if the package is going to be excluded anyway). Somewhat coincidentally, the filtered package list is exactly what gets passed to `getPeerDependencies`, so this works in our favor!

`--filterResults`, as you pointed out, removes dependencies _after_ the latest versions are fetched, so it does not affect `getPeerDependencies`.

**Comment by CreativeTechGuy** [comment]
Awesome! So this issue can be resolved since it actually already exists! Amazing.

Not sure if it'd make sense to clarify this in the docs, but at least I was confused. Hopefully this issue helps someone else in the future. :)

Appreciate you explaining all this!

**Comment by raineorshine** [comment]
Great, glad it worked out. I added a clarification to the README in 26b53a1.
