### ISSUE TITLE
ERR_SOCKET_TIMEOUT on node v18

### ISSUE THREAD

**Issue by hassnaseer** [raineorshine/npm-check-updates#1371]
Please open a new issue and include exact steps to reproduce.

_Originally posted by @raineorshine in https://github.com/raineorshine/npm-check-updates/issues/990#issuecomment-1961923678_

**Comment by hassnaseer** [comment]
@raineorshine Please check this.

**Comment by hassnaseer** [comment]
![image](https://github.com/raineorshine/npm-check-updates/assets/78788462/5b291c0a-a5ec-4522-9a5b-9d842a2a09ca)

**Comment by raineorshine** [comment]
Please fill out a complete issue report including exact steps to reproduce. The other issue was solved two years ago, so whatever problem you are running into is new and requires a complete issue report for me to investigate.

**Comment by raineorshine** [comment]
The screenshot appears to be a python error unrelated to npm-check-updates.

**Comment by hassnaseer** [comment]
![image](https://github.com/raineorshine/npm-check-updates/assets/78788462/c89f126d-fa38-49b3-8ed4-ff603760e7df)
i have run ncu -u then npm install

**Comment by hassnaseer** [comment]
![image](https://github.com/raineorshine/npm-check-updates/assets/78788462/1a374600-b956-47b5-a72d-b6092a76a0ff)
this is latest error that i got

**Comment by hassnaseer** [comment]
but when i revert all things and use node version of 14.0.0 then this is working fine not working on node 18

**Comment by hassnaseer** [comment]
@raineorshine is this fine for getting the issue

**Comment by hassnaseer** [comment]
@raineorshine i ave use this but still same issue

**Comment by hassnaseer** [comment]
![image](https://github.com/raineorshine/npm-check-updates/assets/78788462/38c75ff6-3725-42a5-ae30-88feac5f52d0)

**Comment by raineorshine** [comment]
I'm sorry, I don't understand. 

FWIW, the GitHub test action is passing on node v18, so it is unlikely a bug in npm-check-updates. 

You might consider reinstalling node or npm, since you are getting an error before npm-check-updates begins executing. I've had good luck with [fnm](https://github.com/Schniz/fnm).

**Comment by raineorshine** [comment]
If you're getting an error with `npm i`, as shown in your last screenshot, then it's an issue with npm or an incompatible package. npm-check-updates does not deal with installed dependencies. It only upgrades your package.json.

**Comment by hassnaseer** [comment]
I got it . But again the question is same i have reinstall aftere deleting the node modules . Only 1 thing that i have change i was using node14 now i am using node 18 . After this npm i also returns the error.

**Comment by hassnaseer** [comment]
![image](https://github.com/raineorshine/npm-check-updates/assets/78788462/244a01ee-a7c1-42a5-81e7-d83ac0e5e67e)

the node modules has installed but when i run the project it shows this error now

**Comment by hassnaseer** [comment]
@raineorshine 
it shows "glob-parent": "~5.1.2", error but its already available in package.json file

**Comment by raineorshine** [comment]
I'm not able to provide assistance on npm errors or errors in npm packages unrelated to npm-check-updates unfortunately. The fact that the issue occurs when running `npm i` after upgrading your package.json with npm-check-updates does not imply that the issue is with npm-check-updates.
