### ISSUE TITLE
How to update `package.json` with versions already installed in `package-lock.json`?

### ISSUE THREAD

**Issue by Saibamen** [raineorshine/npm-check-updates#1392]
I want to have clear view of already installed package versions in `package.json`.

I always regenerate `package-lock.json`  file by deleting it and `npm install` to refresh this file, but I also want to update `package.json` with latest installed version for specified range.

How to do this?

**Comment by raineorshine** [comment]
If your dependencies are specified as a range, such as `^1.2.0`, you don't need to update the version in your package.json. Just run `npm install` or `npm update`.

If for some reason you want to bump the lower bound of the range (e.g. upgrade `^1.2.0` to `^1.4.0` in your package.json), then try `ncu --target semver`.

> semver │ Upgrade to the highest version within the semver range specified in your package.json.

**Comment by Saibamen** [comment]
Thank you. `ncu --target semver -u` is doing this job very well :)
