### ISSUE TITLE
backup old package json

### ISSUE THREAD

**Issue by fprijate** [raineorshine/npm-check-updates#1393]
I agree with 
[isue #69](https://github.com/raineorshine/npm-check-updates/issues/69)

Git is solution, but to complicated sometimes.
I usually do ;

1. ncu -u
2. pnpm install
3. build app and test if it works.
4. if it doesn't , restore old package.json and repeat step 2.

it's much simpler to copy package.json to package.json.backup and rename it back if it doesn't work then to commit/checkout.
It is much simpler option , which you are not required to use.

**Comment by raineorshine** [comment]
Please do not post the same comment in multiple issues. You can always link to a comment in a different issue. Or add a comment to an existing issue if it already exists, as was appropriately done in #69.
