### ISSUE TITLE
Could not read peer dependencies for package when combining --cwd with --peer

### ISSUE THREAD

**Issue by daniel-horizon** [raineorshine/npm-check-updates#1398]
As the title says, I'm getting this messaging when I'm trying to ncu for another directory. With just -u I don't get any messages and the packages are actually updated.

**Comment by raineorshine** [comment]
Hi, thanks for reporting.

I suspect there is something else going on, as `--cwd` and `--peer` are used together in the [tests](https://github.com/raineorshine/npm-check-updates/blob/v16/test/peer.test.ts) which are passing. What package manager are you using? Does it install all packages in `./node_modules`? 

Right now (v16) the peer logic tries to read peerDependencies of installed packages on disk. However, the new peer logic (v17) forgoes this approach and fetches peerDependencies from npm. I recommend the v17 prerelease from `npm -g install npm-check-updates@next` and see if that works for you. 

If not, I can troubleshoot further if provided with a sample repo that reproduces the issue.

**Comment by daniel-horizon** [comment]
It does indeed install in `./node_modules`, but works fine with v17. Thanks!
