### ISSUE TITLE
VIM Keyboard Shortcuts for Navigating Update List

### ISSUE THREAD

**Issue by stdavis** [raineorshine/npm-check-updates#1460]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)

---

## Steps to Reproduce

.ncurc:

```js
n/a
```

Dependencies:

```json
n/a
```

Steps:

Run `npx npm-check-updates --color --install always --interactive --format group,repo && npm audit fix` on any project that has updates.

## Current Behavior

The keys `j` & `k` do not scroll through the options.

## Expected Behavior

`j` scrolls down and `k` scrolls up.

This used to work. I don't know at what point it stopped working. I know that this is probably not a big deal but these keys are much easier to use than the arrow keys for those of use who are used to VIM keyboard shortcuts. I'd be willing to help with a PR for this if someone would be kind enough to point me in the right direction on the implementation.

Thanks for the awesome tool!

**Comment by raineorshine** [comment]
Thanks, I support this.

The change would have to happen in https://github.com/raineorshine/prompts/tree/ncu. It's the fork of `prompts` that npm-check-updates uses.

**Comment by raineorshine** [comment]
Fixed and published in `v17.1.4`.
