### ISSUE TITLE
yarn getPeerDependencies doesnt work on private reporsitories when credentials are only set for yarn and not npm

### ISSUE THREAD

**Issue by rbnayax** [raineorshine/npm-check-updates#1470]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)

---

## Steps to Reproduce

use only yarn with private repo on your company scope and authenticate only in yarn
run upgrade with --peers that should skip an upgrade due to peer dependencies in one of your company's dependencies

## Current Behavior

the upgrade is not skipped
reason: getPeerDependencies is using npm cli, which is not authenticated

## Expected Behavior

skip the dependency upgrade, while using yarn to realize the peer dependencies information

**Comment by raineorshine** [comment]
Published in `v17.1.7`.
