### ISSUE TITLE
Add support for Bun text-based lockfile

### ISSUE THREAD

**Issue by GingerAdonis** [raineorshine/npm-check-updates#1483]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)

---

Bun v1.1.39 introduced a new text-based lockfile named `bun.lock`. In the upcoming Bun v1.2 this will be the new default.
This change means npm-check-updates no longer correctly detects Bun. As it relies on checking `bun.lockb`, which won't exist if using the text-based lockfile. 

More information about the text-based lockfile: https://bun.sh/blog/bun-lock-text-lockfile

**Comment by raineorshine** [comment]
Thank you!

Added in `v17.1.12`.
