### ISSUE TITLE
Wildcard filters

### ISSUE THREAD

**Issue by jonathanong** [raineorshine/npm-check-updates#219]
writing something like `ncu -a '/^babel-.*$/'` is weird to me. i should be able to just write `ncu -a babel-*`

**Comment by metaraine** [comment]
I agree that wildcard expressions would be a nice addition.

**Comment by metaraine** [comment]
I added support in the "wildcards" branch, but's going to have to wait till the next major version release since it is technically a breaking change. If others are interested in seeing this feature sooner rather than later, please post here.

**Comment by raineorshine** [comment]
Closing for cleanup purposes and adding the [revive-me](https://github.com/tjunnone/npm-check-updates/issues?utf8=%E2%9C%93&q=label%3Arevive-me) label. Feel free to re-open if you are interested in working on a pull request.

**Comment by AdrianoCahete** [comment]
This simplified version was merged to the main code?

**Comment by raineorshine** [comment]
No, I shouldn't have closed it. In fact, since `*` is not a valid character in a package name, it shouldn't require a breaking change.

**Comment by raineorshine** [comment]
Fixed and published to `v11.2.0`
