### ISSUE TITLE
maintain bottom bound of "X - Y" version range

### ISSUE THREAD

**Issue by bardiharborow** [raineorshine/npm-check-updates#300]
`ncu -a` changes `1.9.1 - 3` to `3`, behaviour that is not correct. It should change it to `1.9.1 - 4` in the event of a new version.

**Comment by raineorshine** [comment]
Thanks for reporting! Sounds like a bug. I'll check it out.

**Comment by raineorshine** [comment]
Can you provide a live example? The test I have that seems to cover this is passing, unless I am missing something:

```
vm.upgradeDependencyDeclaration("1.0 - 2.0", "3.1.0").should.equal("3.1");
```

https://github.com/tjunnone/npm-check-updates/blob/master/test/test-versionmanager.js#L71

**Comment by bardiharborow** [comment]
I'm suggesting that the test needs to be:

```javascript
vm.upgradeDependencyDeclaration("1.0 - 2.0", "3.1.0").should.equal("1.0 - 3.1");
```

To reproduce:

```shell
$ ncu version
2.8.9
$ git clone https://github.com/twbs/bootstrap.git
$ cd bootstrap
$ ncu -a
$ git diff
...
-    "jquery": "1.9.1 - 3",
+    "jquery": "3",
...
``

**Comment by raineorshine** [comment]
Thank you, I get it now.

If that change was made, it would also make sense to change:

```
vm.upgradeDependencyDeclaration("1 < 2", "3.0.0").should.equal("3.0.0");
```
to:
```
vm.upgradeDependencyDeclaration("1 < 2", "3.0.0").should.equal("1 < 3.0.0");
```

There is a natural tension here as ncu wants to preserve your declaration semantics (the way you specified the range) but also it wants to force a breaking change and move to the latest. 

Consider that `^3.0.0` is effectively `3.0.0 - 3.99.99`, and gets upgraded to `^3.1.0`, or `3.1.0 - 3.99.99` when the latest is `3.1.0`. Here we see the bottom of the version range bumped and the top continuing to be constrained with `^`. Your suggestion involves pinning the bottom of the range, which would be a new behavior for ncu. I am okay with it if it seems helpful and intuitive for others.

It makes sense for libraries that you'd like to support after a given point, such as after an important breaking change. The one clearly counterintuitive consequence would be for libraries that have a very large breaking change that renders all previous versions incompatible. For example, let's say jQuery 4 is completely incompatible with previous versions. With your suggestion, ncu would generate `1.9.1 - 4` where simply `^4` is likely preferable. In your use case, wouldn't you just be better off specifying `>=1.9.1` with no upper bound?

**Comment by bardiharborow** [comment]
In my particular case, I'm not very interested in the jQuery version being touched, I'm simply updating the devDependencies. ncu currently "corrupts" the jQuery version and I have to manually fix it.

> The one clearly counterintuitive consequence would be for libraries that have a very large breaking change that renders all previous versions incompatible.

In this situation, manual intervention is going to be needed to fix your library anyway.

> With your suggestion, ncu would generate `1.9.1 - 4` where simply `^4` is likely preferable. In your use case, wouldn't you just be better off specifying `>=1.9.1` with no upper bound?

The same could be said for `^1.9.1`. The reason you pin the dependency and then update periodically with ncu is so that it breaks controllably rather than a `npm publish`

**Comment by raineorshine** [comment]
Great points!

> In my particular case, I'm not very interested in the jQuery version being touched, I'm simply updating the devDependencies. ncu currently "corrupts" the jQuery version and I have to manually fix it.

What about excluding jQuery?
```sh
ncu -x jquery
```

Or just upgrading devDependencies?
```sh
ncu --dev
```

**Comment by bardiharborow** [comment]
> What about excluding jQuery?

Ah, I didn't realise that was possible.

To reiterate my point though, I think that if the user explicitly sets a bottom bound, we should try to keep that intact.

**Comment by raineorshine** [comment]
Excellent. I'll keep the issue open so others can chime in concerning lower
bounds of ranges.

**Comment by raineorshine** [comment]
Closing, as breaking the version range is generally what ncu is intended to do. Explicitly excluding the package in question is the recommended solution.
