### ISSUE TITLE
Should upgrade #tag on git urls

### ISSUE THREAD

**Issue by chopraapooja** [raineorshine/npm-check-updates#463]
I have a package specified as github as source,  in package.json  
`"some-package": "git+https://gitlab.com/username/some-package.git#2.0.7"`  
There is latest verion of package available: 2.0.8.   
But ncu is not upgrading.  

* node version: v8.11.4 
* npm version: 5.6.0
* npm-check-updates version: 2.14.3

---------------------------

**Comment by raineorshine** [comment]
Thanks for reporting! Unfortunately ncu doesn't currently support git paths. This would be a great candidate for a PR.

**Comment by raineorshine** [comment]
Some useful resources for this issue:

- Git url parser: https://github.com/IonicaBizau/git-url-parse
- Git remote tags: https://github.com/sindresorhus/remote-git-tags
- Git url resolver implementations:
  - https://github.com/bower/bower/blob/master/lib/core/resolvers/GitResolver.js#L91
  - https://github.com/npm/npm/pull/15308/files

**Comment by raineorshine** [comment]
More resources:
- **[Given a git refname, can I detect whether it's a hash, tag, or branch?](https://stackoverflow.com/a/18222877/480608)**
- https://github.com/tblobaum/git-rev
- https://github.com/tkellen/js-find-commit-ishgit
- `git rev-parse --verify --quiet COMMIT_ISH`

**Comment by raineorshine** [comment]
Added support for git urls in #716 and published to `v8.0.0-alpha.1`. If anyone is able to try it out that would be most helpful! If there are no issues, I can merge and publish to `latest`.

```sh
npm install -g npm-check-updates@8.0.0-alpha.1
```
