### ISSUE TITLE
The term  'ncu' or 'npm-check-updates'  is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by frankTadlip** [raineorshine/npm-check-updates#479]
* node version: v8.11.2
* npm version: 5.6.0
* npm-check-updates version: 2.15.0
windows 10 pro build 1809
---------------------------

 'ncu' or 'npm-check-updates'  is not recognized as the name of a cmdlet

**Comment by raineorshine** [comment]
Thanks for reporting. Are you using a special shell of some sort? I am not familiar with cmdlets. I am using normal best practices for declaring node binaries: https://github.com/tjunnone/npm-check-updates/blob/master/package.json#L36-L39

**Comment by raineorshine** [comment]
You could also try `ncu.cmd`

**Comment by fengyuanchen** [comment]
I fixed this by add `C:\Users\usename\AppData\Roaming\npm` to my system's user environment variables.

**Comment by XhmikosR** [comment]
@raineorshine I believe this is a non-issue in the sense that normally when Node.js is installed automatically adds `C:\Users\YourUserName\AppData\Roaming\npm` in `PATH`. If it's not there, then something is wrong with the user's installation, not ncu.

**Comment by hosseinGanjyar** [comment]
You should see this: https://github.com/raineorshine/npm-check-updates/issues/266#issuecomment-821788340
