### ISSUE TITLE
Implement --deep flag to update deps in monorepo

### ISSUE THREAD

**Issue by mkungla** [raineorshine/npm-check-updates#522]
Similar to  #154, but would it be idea to add `--deep` or similar flag to check updates in monorepo to update multiple packages found in repository?

use case would be doing something like bellow, but more elegantly:

```
const glob = require('glob')
const childProcess = require('child_process')

const check = (pkgJsonPath) => {
  try {
    return childProcess.execSync(`./node_modules/.bin/ncu --error-level 2 --packageFileDir --packageFile ${pkgJsonPath}`).toString()
  } catch (error) {
    console.log('exec error: ' + error.message)
    process.exit(error.status)
  }
}
glob('./packages/**/package.json', {}, (er, files) => {
  files.forEach((file) => {
    if (file.includes('node_modules')) {
      return
    }
    console.log(`command to update: ./node_modules/.bin/ncu --packageFileDir --packageFile ${file} -u -i`)
    console.log(check(file))
  })
})
```
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: *
* npm version: *
* npm-check-updates version: *

---------------------------

**Comment by revelt** [comment]
In the meantime, you can use [`update-versions`](https://www.npmjs.com/package/update-versions) from yours truly. I wrote it to help with monorepo maintenance, after I moved to Lerna.

It does two tasks: 1. updates dependencies; 2. enforces `^x.x.x` notation. The second task can be very sneaky since as you know, Lerna will not properly bootstrap dependencies marked with `latest`, `*` or whatever else. Also, `update-versions` works on normal repos, it's probably faster than `npm-check-updates` anyway because it's simpler and uses npm's native [pacote](https://www.npmjs.com/package/pacote) (instead of in-house solution that `npm-check-updates` uses).

**Comment by stoically** [comment]
> it's probably faster than npm-check-updates anyway

Testing with a rather extreme example of [~1500 dependencies](https://github.com/tjunnone/npm-check-updates/issues/488#issuecomment-471181374)

```
time ncu
real	0m10.082s

time upd
real	1m7.172s
```

**Comment by revelt** [comment]
^ interesting!

**Comment by mikestopcontinues** [comment]
No offense to @revelt or `lerna-update-wizard`, but neither option meets my needs. I would love to see this feature in `ncu`. Reason being, I use exact versions and I want to update everything at once.

**Comment by prma85** [comment]
> In the meantime, you can use [`update-versions`](https://www.npmjs.com/package/update-versions) from yours truly. I wrote it to help with monorepo maintenance, after I moved to Lerna.
> 
> It does two tasks: 1. updates dependencies; 2. enforces `^x.x.x` notation. The second task can be very sneaky since as you know, Lerna will not properly bootstrap dependencies marked with `latest`, `*` or whatever else. Also, `update-versions` works on normal repos, it's probably faster than `npm-check-updates` anyway because it's simpler and uses npm's native [pacote](https://www.npmjs.com/package/pacote) (instead of in-house solution that `npm-check-updates` uses).

@revelt It is a nice extension. However, I tried to use it today in a lerna/yarn monorepo on windows and the issue that even if I have  `^x.x.x` it is still doing a major version update. On my case, it is changing `"antd": "^3.26.9",` to "antd": "^4.1.0"` :(

**Comment by ScriptedAlchemy** [comment]
Update-versions doesn't seem to offer the same level of interactivity. Or it's docs are terrible. Will be forking ncu and publishing a --deep option that was mentioned above.

**Comment by kachkaev** [comment]
I managed to use this command as a workaround in a monorepo:

```
find . -name package.json -not -path "./node_modules/*" -exec npm-check-updates --upgrade --packageFile {} \;
```

This works but having `--deep` (or `packageFileGlob`) would be better indeed. The benefit of the new feature compared to running `find -exec` is in speed. At the moment, `ncu` needs to fetch package metadata independently for every monorepo packages, which is slow and error-prone (I’ve seen some 503s in stdout which made the results potentially incomplete).

**Comment by mkungla** [comment]
I like the @kachkaev idea of `--packageFileGlob` made rough PR.
Which allows to use `glob` pattern as `--packageFile` arg and added `-deep`  flag which is alias of enhanced  `--packageFile  '{,*[!node_modules]/**/}package.json'`

so

```
ncu --packageFile '{,*[!node_modules]/**/}package.json'
```
is same as
```
ncu --deep
```

**Comment by mkungla** [comment]
Please go ahead and test it and let me know is that behavior what you are expecting...
