### ISSUE TITLE
Detailed changelog for ncu

### ISSUE THREAD

**Issue by yvele** [raineorshine/npm-check-updates#555]
I'm confused, I'm pretty sure there where a changelog for this project 🤔 

But I cannot find it, either in [release notes](https://github.com/tjunnone/npm-check-updates/releases)  or in a `CHANGELOG.md`

Can you please add (back?) a detailed changelog? Not only for major versions.

**Comment by raineorshine** [comment]
Minor changes have not been logged since `v2.12.0`. You'll have to use the commit log.

**Comment by yvele** [comment]
For a tool like `npm-check-updates` I think keeping a detailed changelog could be a very good thing.

I was also think to ask an `npm-check-updates` (in the interactive mode) to display the changelog for each updated version, to ease user decision process 🤔

**Comment by raineorshine** [comment]
> interactive mode... display the changelog for each updated version, to ease user decision

Yes, I agree this would be a nice feature!

**Comment by yvele** [comment]
At least the changelog URL (the full changelog? 🤔 )

**Comment by raineorshine** [comment]
> At least the changelog URL (the full changelog? 🤔 )

I'm sorry, I don't understand.

**Comment by yvele** [comment]
Something like

```
$ ncu
Checking package.json
[====================] 3/3 100%

 express           4.12.x  →   4.13.x   https://github.com/expressjs/express/releases
 multer            ^0.1.8  →   ^1.0.1   https://github.com/expressjs/multer/blob/master/CHANGELOG.md
 react-bootstrap  ^0.22.6  →  ^0.24.0   https://github.com/react-bootstrap/react-bootstrap/blob/master/CHANGELOG.md

Run ncu -u to upgrade package.json
```

**Comment by jacobq** [comment]
[Looks like](https://github.com/tjunnone/npm-check-updates/commit/2d729b4ed65af9b1bc6a350c3695cfb8efd1e355) we at least got something [for v4](https://github.com/tjunnone/npm-check-updates/releases/tag/v4.0.0)

**Comment by brettz9** [comment]
So is there still a desire for a separate `CHANGELOG.md` file? Would be good to have in my book. If so, there is https://github.com/transferwise/release-to-github-with-changelog which can apparently post to `/releases` as well.

**Comment by yvele** [comment]
@raineorshine what is breaking in v5.0.0? There is no changelog https://github.com/raineorshine/npm-check-updates/releases/tag/v5.0.0 🤔

**Comment by raineorshine** [comment]
@yvele Thanks, release created: https://github.com/raineorshine/npm-check-updates/releases/tag/v5.0.0

> **Breaking\* changes:**
> ~node >= 8~ 
> node >= 10.17
> 
> Bump minimum node version to `v10.17.0` due to `move-file` #651 
> 
> *If `ncu` was working for you on `v4.x`, then `v5.0.0` will still work. Just doing a major version bump since ncu's officially supported node version is changing. `v4` should be patched to be compatible with node `v8`, but I'll hold off unless someone requests it.

**Comment by raineorshine** [comment]
Closing, as the current policy will be kept for the foreseeable future. In summary:

- Major versions are hand documented in both Releases and CHANGELOG.md.
- A conservative release policy is followed: anything that could produce a breaking change will **only** be released in a major version upgrade.
- Commits messages are meaningful and additional references are linked as appropriate

Thanks!
