### ISSUE TITLE
Option to limit upgrades to latest minor version

### ISSUE THREAD

**Issue by daveisfera** [raineorshine/npm-check-updates#573]
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 10.16.3
* npm version: 6.9.0
* npm-check-updates version: 3.1.21

---------------------------

Currently, using `--semverLevel` can be used to limit the level but not to "expand it". For example, we use `~` in our package.json to have tighter control over versions, so it would be nice to be able to do `--semverLevel=minor` to update to the latest minor release while still using `~` to only allow "automatic" updates of point releases.

**Comment by JasonEtco** [comment]
Hello! I'm dropping in to give a 👍 and describe my use-case a little differently: my project vendors our dependencies, meaning we basically bundle up our dependencies as tarballs and commit them to version control.

We do this for a few reasons (not dependent on any registry being alive, inclusion of private code without worrying about registry credentials in all envs), but it has the added effect of saving exact versions. [Here's the library we use, `my-precious`](https://www.npmjs.com/package/my-precious), if you're curious.

Because we store those tarballs, when we run `npm install` it installs from those, ignoring any `^` semver rules and acting as if we had pinned to an exact version. So even a minor/patch update requires a manual update.

Hope that helps!

**Comment by Srinath-Ganesan** [comment]
Dropping in to give a 👍 have the exact requirement as @daveisfera

**Comment by raineorshine** [comment]
The best way for this to get done would be through a PR. I would be happy to support anyone who has a good plan and wants to try to implement this feature.

**Comment by lk77** [comment]
Hello,

it would be great to be able to get only minor or major upgrades, or to sort packages and displaying major first then minor.

**Comment by raineorshine** [comment]
Upgrading this to `bug`. The behavior should be default in `--target minor`. I imagine most users would expect minor upgrades if they were available.

**Comment by foxted** [comment]
Would it be possible to modify the behaviour to ensure that when a dependency is set with `~`, `ncu` only checks for minor versions for that dependency?

For example: 

![Screen Shot 2021-02-25 at 00 08 35](https://user-images.githubusercontent.com/1385160/109122573-a6ab9c00-76fd-11eb-837f-8d8d7fdb9645.png)

I think if the specified version is `~4.2.5` in `package.json`, `ncu` should suggest to update to `v4.3.8`, not `v5.1.1`.

**Comment by lk77** [comment]
well ncu is for upgrading dependencies, i have a lot of dependencies set with `~` but when using ncu i want to upgrade to the latest major version.

just use npm update if you just want to update to the latest minor version.

**Comment by raineorshine** [comment]
@lk77 is correct. The main purpose of `npm-check-updates` is to **break** dependencies in a controlled manner. Semver and `npm update` is well-suited to upgrade non-breaking dependencies.

There is a proposal to add `--target semver` in #581 which is open for PRs.

**Comment by Litee** [comment]
Unless I miss something `--target minor` is working as expected in latest versions of ncu - it offers to upgrade to eslint v5.16.0. I would double-check that the problem is still standing.

**Comment by raineorshine** [comment]
> Unless I miss something `--target minor` is working as expected in latest versions of ncu - it offers to upgrade to eslint v5.16.0. I would double-check that the problem is still standing.

@Litee I just checked and you're right. Thanks for bringing it to my attention.
