### ISSUE TITLE
Ctrl-C does not abort interactive session

### ISSUE THREAD

**Issue by fatso83** [raineorshine/npm-check-updates#627]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 12.7.0
* npm version: 6.10
* npm-check-updates version: 3.2.0

---------------------------

I have tried several times to test the interactive option for this tool, and very often I want to abort the process and so I press Ctrl-C to send a signal to quit the ongoing operation. This is not respected by the tool, which for some reason has chosen to interpret this as a YES to the current question. This is a highly unconventional choice :smile: 

I would like to signal listener to interpret Ctrl-C as a signal to do `process.exit(1)` or at least give the user a prompt to quit.

**Comment by raineorshine** [comment]
I tend to agree. [npm-check-updates uses](https://github.com/tjunnone/npm-check-updates/blob/fb013ea9d77ea6dcad502cb75666340766752121/lib/versionmanager.js#L292) the package [prompts](https://github.com/terkelg/prompts) which [does seem to support](https://github.com/terkelg/prompts#prompts) detection of Ctrl + C.

**Comment by fatso83** [comment]
There are various ways of achieving this, though one might need to resort to hacks like this for some cases: https://github.com/terkelg/prompts/issues/252#issue-559780869 (actively avoids printing a "Y").

**Comment by Tchoupinax** [comment]
Hello,
I met this bug and i encourage its fix :)

Thank you for your work.

**Comment by raineorshine** [comment]
Fixed and published in `v11.1.11`
