### ISSUE TITLE
TypeError: Cannot read property 'undefined' of undefined with missing package version

### ISSUE THREAD

**Issue by cliveharber** [raineorshine/npm-check-updates#630]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 13.8.0
* npm version: 6.14.0
* npm-check-updates version: 4.0.2

---------------------------
I have been experience the following
```
npm-check-updates/lib/npm-check-updates.js:412
    throw err;
    ^

TypeError: Cannot read property 'undefined' of undefined
    at /Users/cliveharber/.node/lib/node_modules/npm-check-updates/lib/package-managers/npm.js:81:36
    at Array.reduce (<anonymous>)
    at /Users/cliveharber/.node/lib/node_modules/npm-check-updates/lib/package-managers/npm.js:74:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 57)
    at async getAnalysis (/Users/cliveharber/.node/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:453:30)
    at async Object.run (/Users/cliveharber/.node/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:464:12)
```
I have a fix for this - how would you like to proceed?

Cheers

**Comment by raineorshine** [comment]
Great. Can you open a PR?

**Comment by raineorshine** [comment]
@cliveharber Any update?

**Comment by cliveharber** [comment]
Fix was merged here: https://github.com/raineorshine/npm-check-updates/pull/631#issuecomment-593002299

**Comment by cliveharber** [comment]
Issue can be closed.

**Comment by raineorshine** [comment]
Ah yes! Thanks
