### ISSUE TITLE
Add support for npm package aliases

### ISSUE THREAD

**Issue by Cherry** [raineorshine/npm-check-updates#633]
[npm 6.9.0](https://github.com/npm/cli/releases/tag/v6.9.0) added support for aliasing packages in your `package.json`, so for example, you could install `postman-request`, but into the `request` folder as per the syntax below:

```
"request": "npm:postman-request@2.88.1-postman.16"
```

More references: 
- https://github.com/npm/rfcs/blob/latest/implemented/0001-package-aliases.md
- https://github.com/npm/cli/commit/b7b54f2d18e2d8d65ec67c850b21ae9f01c60e7e
- https://github.com/npm/cli/pull/3

As per the example above, I'm using `postman-request@2.88.1-postman.16` which is out of date, but not being detected by `ncu`. The latest version at time of writing as per https://www.npmjs.com/package/postman-request, is `2.88.1-postman.19`.

There's a lot of use-cases for this, but one of the more common ones is actually as I'm describing above - migrating off of an older unmaintained library to another one with an identical API, without making too many code changes. It would be great to see this syntax supported in `npm-check-updates`.

**Comment by raineorshine** [comment]
Great suggestion. I'm happy to support and provide guidance for a PR for this feature.

**Comment by raineorshine** [comment]
@Cherry @l5x I attempted a fix in #715. Could you try `npm install -g npm-check-updates@7.0.5-alpha.1` and see if it works for you?

**Comment by Cherry** [comment]
@raineorshine Awesome! From some basic testing, things seem to work as I'd expect when using a package alias! Thanks for the feature addition!

**Comment by raineorshine** [comment]
Great, thank you!

I will merge into `master` and publish to `latest` once #716 is tested more, since they both entail a major version bump.
