### ISSUE TITLE
Bird's-eye interactive mode

### ISSUE THREAD

**Issue by brettz9** [raineorshine/npm-check-updates#635]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 10.19.0
* npm version: 6.14.2
* npm-check-updates version: 4.0.4

---------------------------

As an alternative to the step-by-step interactive mode, I'd love to have an option which showed all of the available updates at once, and then allowed one to use key commands (including one to exit of course) which could check/uncheck all, update all, or update one-by-one.

This mode would also make it easy to build #570 on top such that one could, e.g., type "c" to open the change logs for the highlighted version(s).

It could even be expanded over time perhaps to allow opening of metadata-pointed license URLs, doc URLs (since `package.json` has such a URL), as well as to go to the Github `releases` page, etc.

**Comment by liby** [comment]
"npm-check-updates" checks for updates faster than  "npm-check", The scope of inspection is more comprehensive than that of "yarn".
If our interactive pages are similar to theirs, It will be more convenient to use.
![yarn upgrade-interactive](https://user-images.githubusercontent.com/38807139/77401151-5f2ed880-6de7-11ea-9bc8-04c314847e1f.png)
![npm-check-interactive](https://user-images.githubusercontent.com/38807139/77401237-8685a580-6de7-11ea-9287-7365639e086c.png)

**Comment by raineorshine** [comment]
Great suggestion! I don't personally have time to add this feature, but I would be happy to support someone who wants to do a PR.

**Comment by raineorshine** [comment]
Closing with the [revive-me](https://github.com/raineorshine/npm-check-updates/labels/revive-me) tag for interested contributors. See #484.
