### ISSUE TITLE
Problem to check certificate since npm-check-updates 4.0.2

### ISSUE THREAD

**Issue by kris2kris** [raineorshine/npm-check-updates#636]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 13.10.1
* npm version: 6.13.7
* npm-check-updates version: 4.0.2

---------------------------

After installing version 4.0.2, there is a problem to check certificate, please see the log below. It works with version 4.0.1.

```
Checking /src/main/frontend/package.json
[--------------------] 0/32 0%/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:412
    throw err;
    ^

FetchError: request to https://repo/keycloak-js failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/minipass-fetch/lib/index.js:97:14)
    at ClientRequest.emit (events.js:316:20)
    at TLSSocket.socketErrorListener (_http_client.js:432:9)
    at TLSSocket.emit (events.js:328:22)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  type: 'system'
}
```

**Comment by sted** [comment]
I get 

> Checking /Users/sted/Devel/catflow-editor/package.json
> [--------------------] 0/12 0%/usr/local/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:412
>     throw err;
>     ^
> 
> FetchError: request to https://sinopia.epress.local/catflow-prosemirror failed, reason: self signed certificate
> 
> at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/minipass-fetch/lib/index.js:97:14)
>  at ClientRequest.emit (events.js:316:20)
>     at TLSSocket.socketErrorListener (_http_client.js:432:9)
>     at TLSSocket.emit (events.js:328:22)
>     at emitErrorNT (internal/streams/destroy.js:84:8)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   code: 'DEPTH_ZERO_SELF_SIGNED_CERT',
>   errno: 'DEPTH_ZERO_SELF_SIGNED_CERT',
>   type: 'system'
> }
> 

since 4.0.2.

Rolled back to 4.0.1 and the problem disappears.

**Comment by raineorshine** [comment]
Here's the diff between 4.01 and 4.02:
https://github.com/tjunnone/npm-check-updates/compare/v4.0.1...v4.0.2

There were no functional changes, just README and dependency updates. Maybe it is due to the `pacote` major version upgrade from 10.3.2 to 11.1.0:
https://github.com/npm/pacote/compare/v10.2.0...v11.1.0

**Comment by stz184** [comment]
I have the same problem and I can confirm that downgrading to v4.0.2 did the trick.

**Comment by raineorshine** [comment]
> Rolled back to 4.0.1 [v4.0.2] and the problem disappears.

> downgrading to v4.0.2 did the trick

Since @sted and @stz184 downgraded to different versions, it suggests that either there are two different issues, or the issues are related to npm and not npm-check-updates.

**Comment by sted** [comment]
We should ask to @stz184, it could be a typo.
I do think that the problem is related to pacote.

**Comment by sanchez** [comment]
I received the issue above on v4.1.2. Rolled back to v4.0.2 and still received the issue. It was only rolling back to v4.0.1 the issue was no longer appearing

**Comment by psalchow** [comment]
I can confirm that rolling back to 4.0.1 worked

**Comment by adjenks** [comment]
I'm also getting this issue. I am behind a firewall, but I have `npm config set cafile` set and other npm operations work fine.

I rolled back to 4.0.1 and it started working.

**Comment by raineorshine** [comment]
If anybody who is able to reproduce the issue would be willing to do some troubleshooting, it would be a big help to others and the project! It could be an issue with `pacote`, but `npm-check-updates` is highly dependent on it.

**Comment by Gates111** [comment]
I only get the error for a specific NPM package (FontAwesome Pro):
[===============-----] 27/36 75%C:\Repos\npm-check-updates-master\lib\npm-check-updates.js:427
  throw err
  ^
FetchError: request to https://npm.fontawesome.com/@fortawesome%2ffontawesome-pro failed, reason: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (C:\Repos\npm-check-updates-master\node_modules\minipass-fetch\lib\index.js:97:14)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:322:22)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN',
  errno: 'SELF_SIGNED_CERT_IN_CHAIN',
  type: 'system'
}

I've found that on Master if I install my certificate for FontAwesome and FontAwesome as a devDependency and run ncu I get the error, but if I downgrade pacote to 10.3.2 (the last 10.x version of pacote ),  running ncu works just fine, but as soon as I reupgrade to 11.0 or above of pacote it's broken. I would assume it has something to do with NPM packages that require authentication and Pacote 11+, as all other packages aren't affected for me. Or that's at least part of the error anyway.

**Comment by raineorshine** [comment]
@kris2kris @sted @sanchez @adjenks @Gates111 Potential fix made in #713 and published in `v7.0.3-alpha.1`. Will you try it out and let me know if it fixes the problem for you? 

```sh
npm install -g npm-check-updates@next
```

**Comment by Gates111** [comment]
@raineorshine It works for me on latest now. Thanks!

**Comment by sted** [comment]
It works for me too. 👍

**Comment by raineorshine** [comment]
Fantastic. Major props to @Lalem001 for investigating, finding the cause, and submitting a PR.

Published on latest now in `v7.0.3`.

**Comment by kris2kris** [comment]
Hi everyone,
This problem is back since version 15.2.4

**Comment by raineorshine** [comment]
The only change in `15.2.4` is replacing `fs` with `fs.promises` (650e80e4a4b062121b9143c3c7632f2215e7dc5e).

@kris2kris Can you confirm that the problem does not occur in `15.2.3`? Or does it go back further?

**Comment by kris2kris** [comment]
I can confirm it works with `15.2.3` and with `15.2.4` I got this error 
`FetchError: request to https://myrepo/@fortawesome%2ffontawesome-free-regular failed, reason: unable to verify the first certificate
    at ClientRequest.<anonymous> (/usr/lib/node_modules/npm-check-updates/node_modules/minipass-fetch/lib/index.js:130:14)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:525:35)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  errno: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  type: 'system'
}
`

**Comment by raineorshine** [comment]
Thank you. I see that `cafile` was changed to an async function in that commit, but the call site does not await. Let me patch that and see if it fixes the issue.

**Comment by raineorshine** [comment]
Try `v16.0.2`

**Comment by kris2kris** [comment]
it works, thanks
