### ISSUE TITLE
range evaluation broken?

### ISSUE THREAD

**Issue by tomquas** [raineorshine/npm-check-updates#650]
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: 10.20.1
* npm version: 6.14.4
* npm-check-updates version: 4.1.2

---------------------------
hi,

my goal: stick with gulp 3.9.1 and not upgrade to 4.x.

i tried all these configuration in package.json: "^3.x.x", "3.9.1", "~3.9.x" but ncu kept proposing the upgrade. only "<4.x" eventually made the gulp package stick.

shouldn't the above rules apply all to make gulp sticky? 
i checked using https://semver.npmjs.com/

**Comment by stoically** [comment]
ncu's job is to upgrade to the latest available version. If you want to exclude an dependency you could use `-x gulp` or `-i`.

Since this is frequently asked, I guess it might makes sense to add it to the README at some point.

**Comment by tomquas** [comment]
> ncu's job is to upgrade to the latest available version. If you want to exclude an dependency you could use `-x gulp` or `-i`.
> 

i did not know this. thanks for the clarification

> Since this is frequently asked, I guess it might makes sense to add it additionally as FAQ section to the README at some point, even though the first sentence already says "npm-check-updates upgrades your package.json dependencies to the latest versions, ignoring specified versions."

either that or ... what goes against adding support for this scenario? IMHO, -x and -i are inconvenient for long dependency lists and selective upgrading.

**Comment by stoically** [comment]
> either that or ... what goes against adding support for this scenario? IMHO, -x and -i are inconvenient for long dependency lists and selective upgrading.

How would you see that working? I would assume that most of the time upgrading to the latest version is the wanted behavior. Like, in your case you just wanted to keep gulp in range, but everything else should upgrade to latest, right? A toggle that respects ranges would probably lead to confusion why packages aren't upgraded to the latest version.

**Comment by tomquas** [comment]
> How would you see that working? I would assume that most of the time upgrading to the latest version is the wanted behavior. 

partially agreed, but what when my package.json explicitly defines ranges or sticky versions?

> Like, in your case you just wanted to keep gulp in range, but everything else should upgrade to latest, right? A toggle that respects ranges would probably lead to confusion why packages aren't upgraded to the latest version.

right. i might be missing something, but i thought semver already has us covered with tilde and caret ranges? isn't it a matter of comparing a newly available version against the related package.json rules?

in case of gulp:
```
const s = require('semver')
s.satisfies('4.0.1', '~3.x')  // with '~3.x' taken from package.json
```

**Comment by raineorshine** [comment]
The *raison d'être* of `npm-check-updates` is to *break* semver ranges. Semver works great when you want to *preserve* version ranges. `npm` allows you to upgrade to newer installed versions within a range without changing your `package.json`. However, when many packages are out-of-date with new major versions, there is no easy way to know what version to upgrade them to. That's where `npm-check-updates` comes in.

`npm-check-updates` shows you exactly which versions can be upgraded, like `npm outdated --depth=0`, but has the ability to update your `package.json`, as well as lots of options for partial upgrades, filtering prereleases, and programmatic usage.

**Comment by tomquas** [comment]
thanks for clarifying. i was a trying too hard to replace `npm` with `ncu`.
it would be great to make `ncu`'s purpose even more obvious in the docs.

**Comment by tomquas** [comment]
sorry, one more thing:i probably got confused by the first bullet below the headline.

> maintains existing semantic versioning policies, i.e. "express": "^4.0.0" to "express": "^5.0.0"

is that so?
