### ISSUE TITLE
subdependency move-file only supports node >= 10.17

### ISSUE THREAD

**Issue by BigsonLvrocha** [raineorshine/npm-check-updates#651]
- [X] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [X] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

I can't upgrade this packages since I was using the same version of node (1.16.1) that the server uses, which is not a problem, but it just throws an error that is hard to trace.

The depedency path is npm-check-updates > pacote > cacache > move-file

if pacote is really needed, then update node engine constraint to >= 10.17

* node version: 10.16.1
* yarn version: 1.22.4
* npm-check-updates version: 4.1.2

Broken by https://github.com/sindresorhus/move-file/pull/8

**Comment by raineorshine** [comment]
Thanks for reporting! Updated and published in `v5.0.0`.
