### ISSUE TITLE
ncu 4.1.1 is still there even after upgrade to 6.0.1

### ISSUE THREAD

**Issue by Amosss** [raineorshine/npm-check-updates#667]
- [ X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [ X] I am using the latest version of `npm-check-updates`
- [ X] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
ncu -v shows 4.1.1 
package.json shows 6.0.1 and I run both npm install and npm i npm-check-updates

## Current Behavior
I got "+ npm-check-updates@6.0.1" but when running ncu -v, it still shows 4.1.1
## Expected Behavior
After running npm i npm-check-updates and npm -v, I expect to see 6.0.1

**Comment by raineorshine** [comment]
It sounds like there is an old version somehow still on your `PATH`. (I assume you meant `ncu -v` not `npm -v`.)

> After running npm i npm-check-updates and npm -v, I expect to see 6.0.1

Are you installing `npm-check-updates` globally? Your comment indicates that you may have installed it locally, which means that running `ncu` in your shell could still be running the untouched global install.

**Comment by Amosss** [comment]
Yeah, ncu instead of npm - I changed it :)

I don't remember how I installed ncu but I think it was locally. Now when I run 
`npm list npm-check-updates`
I see `-- npm-check-updates@6.0.1`
and when I run `ncu -v`, I get

>    ╭───────────────────────────────────────────╮
>    │                                           │
>    │      Update available 4.1.1 → 6.0.1       │
>    │   Run npm i npm-check-updates to update   │
>    │                                           │
>    ╰───────────────────────────────────────────╯
> 
> 4.1.1

**Comment by raineorshine** [comment]
What do you get from executing `type ncu` in your shell? That will tell you where the executable is. It seems likely that you have it installed globally. If this is the case, you have a few options:

1. Install the latest version of `npm-check-updates` globally: `npm i -g npm-check-updates`
2. Specify the full path to the local `ncu` binary: `./node_modules/.bin/ncu -v`
3. Add local npm binaries to your `PATH` in your `.bashrc`, `.bash_profile`, or equivalent shell config: `export PATH="./node_modules/.bin:$PATH"` (Note that this will prioritize local binaries when executing commands in any project with a `node_modules` folder. Personally I find this very handy.)

**Comment by XhmikosR** [comment]
`where ncu` if you are on Windows or `which ncu` if you are on nix should also show the path to the executable.

You probably just need to clear up your `PATH`.

**Comment by Amosss** [comment]
`ncu -v` gives 4.1.1
`./node_modules/.bin/ncu -v` gives 6.01

So you are right and ncu is installed both locally and globally. I will just use `./node_modules/.bin/ncu` from now on... Thanks!
