### ISSUE TITLE
problem with peerDependencies

### ISSUE THREAD

**Issue by mesqueeb** [raineorshine/npm-check-updates#668]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

When I mark a package as peerDependency, I often also have it in my devDependencies, because I want it to also actually be in the node_modules folder.

NCU seems to have a problem, it only increments the peerDependency version.

before `ncu -u`
```
"peerDependencies": {
  "@vue-sync/core": "^0.4.2"
},
"devDependencies": {
  "@vue-sync/core": "^0.4.2",
},
```

## Current Behavior

after `ncu -u`
```
"peerDependencies": {
  "@vue-sync/core": "^0.5.1"
},
"devDependencies": {
  "@vue-sync/core": "^0.4.2",
},
```

## Expected Behavior

after `ncu -u`
```
"peerDependencies": {
  "@vue-sync/core": "^0.5.1"
},
"devDependencies": {
  "@vue-sync/core": "^0.5.1",
},
```

**Comment by raineorshine** [comment]
Thanks! This is a known issue: https://github.com/raineorshine/npm-check-updates/issues/598
