### ISSUE TITLE
Allow by-package overrides for semver level and possibly other config

### ISSUE THREAD

**Issue by brettz9** [raineorshine/npm-check-updates#696]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Current Behavior

Using `reject`, I can wholly prevent updates on a particular package.

## Expected Behavior

I'd like to be able to get patch or minor fixes for a given package, while still preventing it from having major bumps (e.g., bootstrap).

I'm cool if this is passed right away to the idea heap--just would be a nice to have, thanks!

**Comment by raineorshine** [comment]
Cool! So would this basically be `--semverLevel` on a per-package basis?

**Comment by brettz9** [comment]
Yeah--I guess it would be less of a `reject` (or `filter`) and more of an "override" (as with the former, regexes and CSV could be useful here too, though not critical for my purposes).

Other flags, per a cursory review, that look of conceivable use with overriding besides `semverLevel`, might be `minimal`, `newest`, `pre`, and `greatest` and maybe `dep` too (e.g., if indicating say `eslint` devDeps. should be updated, not `eslint` peerDeps.), though as long as the default `dep`, etc. worked, I'm personally just looking for `semverLevel` at the moment.

**Comment by raineorshine** [comment]
Okay, that's fair. A json object in the `.ncurc` would be a good place to specify these more advanced options.

**Comment by IlanFrumer** [comment]
+1

**Comment by raineorshine** [comment]
Closing with the [revive-me](https://github.com/raineorshine/npm-check-updates/issues?q=label%3Arevive-me) tag for interested contributors. See #484.
