### ISSUE TITLE
[Windows] Error: The system cannot find the path specified

### ISSUE THREAD

**Issue by 9812334** [raineorshine/npm-check-updates#703]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X] I am using the latest version of `npm-check-updates`
- [X] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
$ ncu -u

C:\Users\test\AppData\Roaming\npm\node_modules\npm-check-updates\lib\npm-check-updates.js:427
  throw err
  ^
The system cannot find the path specified.
The system cannot find the path specified.

(Use `node --trace-uncaught ...` to show where the exception was thrown)

I just re-installed the latest node and I still get this error.

Any help is appreciated. Thanks

**Comment by raineorshine** [comment]
@9812334 Any update?

**Comment by mborecki** [comment]
I have this problem for a couple mounts.

Trace stack shows only this:
```
$ node --trace-uncaught /c/Users/Marek/AppData/Roaming/npm/node_modules/npm-check-updates/bin/ncu.js

C:\Users\Marek\AppData\Roaming\npm\node_modules\npm-check-updates\lib\npm-check-updates.js:427
  throw err
  ^
System nie mo�e odnale�� okre�lonej �cie�ki.
System nie mo�e odnale�� okre�lonej �cie�ki.

Thrown at:
    at C:\Users\Marek\AppData\Roaming\npm\node_modules\npm-check-updates\lib\npm-check-updates.js:427:3
    at emit (events.js:311:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

**Comment by raineorshine** [comment]
@mborecki What do you get with `ncu --loglevel verbose`?

**Comment by mborecki** [comment]
```
$ node --trace-uncaught /c/Users/Marek/AppData/Roaming/npm/node_modules/npm-che
ck-updates/bin/ncu --loglevel verbose
Initializing...

C:\Users\Marek\AppData\Roaming\npm\node_modules\npm-check-updates\lib\npm-check-updates.js:427
  throw err
  ^
System nie mo�e odnale�� okre�lonej �cie�ki.
System nie mo�e odnale�� okre�lonej �cie�ki.

Thrown at:
    at C:\Users\Marek\AppData\Roaming\npm\node_modules\npm-check-updates\lib\npm-check-updates.js:427:3
    at emit (events.js:311:20)
    at processPromiseRejections (internal/process/promises.js:209:33)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```


BUT
after some debugging and testing I pinpointed problem to this line:

`npm-check-updates\lib\npm-check-updates.js:448`
```
  if (options.packageManager === 'npm' && !options.prefix) {
    options.prefix = await packageManagers.npm.defaultPrefix(options)
  }
```

If I surround `defaultPrefix` in `try..catch` ncu works fine for me.

**Comment by raineorshine** [comment]
> BUT
> after some debugging and testing I pinpointed problem to this line:
> 
> `npm-check-updates\lib\npm-check-updates.js:448`
> 
> ```
>   if (options.packageManager === 'npm' && !options.prefix) {
>     options.prefix = await packageManagers.npm.defaultPrefix(options)
>   }
> ```
> 
> If I surround `defaultPrefix` in `try..catch` ncu works fine for me.

Brilliant! That's super helpful. Would you be willing to find what is failing in [`defaultPrefix`](https://github.com/raineorshine/npm-check-updates/blob/master/lib/package-managers/npm.js#L177-L196)? Does `cmd = 'npm'` work but not `cmd = 'npm.cmd'`? Maybe `npm.cmd` is not always correct on Windows.

This could be a regression from the fix for #146.

**Comment by mborecki** [comment]
`cmd = 'npm'` throws `spawn npm ENOENT` so this is no a fix.

**That is what I figured out:**

file: `npm-check-updates\lib\package-managers\npm.js#185`
```
return spawn(cmd, ['config', 'get', 'prefix']).then(prefix => {
```

if I add option `{shell: true}` so...
```
return spawn(cmd, ['config', 'get', 'prefix'], {shell: true}).then(prefix => {
```
it works.

Unfortunately I dont realy know consequences (especially on no Win10) of this change, so I will not making PR.

My evn:
Win10
Node: 12.16.1
npm: 6.14.2
ncu: 7.0.3

**Comment by raineorshine** [comment]
Thanks! I will add the `try-catch` to avoid any regressions and leave a note to this issue in case someone comes along with a better understanding of the implications. Thanks again for your help!

**Comment by raineorshine** [comment]
Published to `v7.0.4-alpha.1`. Will you see if this works?

```sh
npm install -g npm-check-updates@next
```

**Comment by mborecki** [comment]
@raineorshine 
Do not works for me because I don't have english OS and my error is: `System nie mo�e odnale�� okre�lonej �cie�ki.` - the same but in polish.

**Comment by raineorshine** [comment]
That makes sense. Will you try now? I removed the error text detection.
