### ISSUE TITLE
npm WARN: request has been deprecated

### ISSUE THREAD

**Issue by usb248** [raineorshine/npm-check-updates#704]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

Please fix:
`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142`

**Comment by raineorshine** [comment]
`npm-check-updates` does not use `request` directly. 

```
$ npm ls request
npm-check-updates@7.0.2 /Users/raine/projects/npm-check-updates
└─┬ pacote@11.1.10
  └─┬ @npmcli/run-script@1.3.1
    └─┬ node-gyp@6.1.0
      └── request@2.88.2
```

**Comment by usb248** [comment]
Fresh install, just see:
![image](https://user-images.githubusercontent.com/7659927/87974209-fbcd6280-cac9-11ea-8000-4b2b910c9359.png)
It doesn't seem the case.

**Comment by raineorshine** [comment]
Yes, the warning will always be displayed during installation if a deep dependency is deprecated.
