### ISSUE TITLE
Invalid package manager: yarn

### ISSUE THREAD

**Issue by MarxZhou** [raineorshine/npm-check-updates#705]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------
I saw in the source code that only one package manager "npm" is currently supported.
Are there any plans to support other package managers?

## Steps to Reproduce
Run the command: ncu -g --packageManager yarn

## Current Behavior
Error: Invalid package manager: yarn

## Expected Behavior
Hope to check the version information of the npm module installed globally by yarn.

**Comment by raineorshine** [comment]
Does yarn install global modules in the same place as npm? What do you get when you run `ncu -g`?

**Comment by MarxZhou** [comment]
My yarn global installation location has not been changed, and the default configuration is used.

After running "nuc -g", only the information of npm itself is displayed.
Similar to the information below.

---------------------------------
λ ncu -g
[====================] 1/1 100%

 npm  6.14.5  →  6.14.7

ncu itself cannot upgrade global packages. Run the following to upgrade all global packages:

npm -g install npm@6.14.7

------------------------------------

![image](https://user-images.githubusercontent.com/39861054/88462208-36753780-cedc-11ea-807e-b1b0cc3187af.png)

**Comment by raineorshine** [comment]
I see. In that case one would need to add an interface to `yarn` as described here:
https://github.com/raineorshine/npm-check-updates/tree/master/lib/package-managers

**Comment by MarxZhou** [comment]
> I see. In that case one would need to add an interface to `yarn` as described here:
> https://github.com/raineorshine/npm-check-updates/tree/master/lib/package-managers
> 
> Only `list` and `latest` would be required.

I am trying to adapt yarn these days.
If you have time, please adapt yarn.
Although I am also trying, but my ability is limited, still not successful.

**Comment by raineorshine** [comment]
I only have time for critical bugs and PR support, but I am open to a PR.
