### ISSUE TITLE
Disable Strict-SSL not working

### ISSUE THREAD

**Issue by Lalem001** [raineorshine/npm-check-updates#707]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
- Private Registry setup with self signed cert.
  - Yes I have seen other issues about this.
  - This issue is not about working with such certs, but ignoring them as follows.
- Set `strict-ssl = false` to npm's config (per [npm config docs](https://docs.npmjs.com/using-npm/config#strict-ssl) snake case is required)
- Attempt NCU

## Current Behavior
- NCU fails with `self signed certificate in certificate chain` as mentioned in other issues
- I have manually run the code listed in [npm.js#L15-24](https://github.com/raineorshine/npm-check-updates/blob/master/lib/package-managers/npm.js#L15-L24)
  - Parsed config passed to `pacote`, and subsequently `npm-registry-fetch`, has `strict-ssl: false`
  - `npm-registry-fetch` is expecting `strictSSL` not `strict-ssl`
  - Setting `strictSSL = true` in npm config, while invalid, stops the self signed error

## Expected Behavior
- NCU should correct npm config keys to match what `pacote` and `npm-registry-fetch` are expecting.
  - At least `strict-ssl` key converted to `strictSSL`

@raineorshine I can make a PR for this if you wish

**Comment by Lalem001** [comment]
Just found that this is technically a regression of #528

**Comment by raineorshine** [comment]
Thank you for identifying the problem!

> @raineorshine I can make a PR for this if you wish

This would be SO helpful! I have been unable to reproduce, and I know it is affecting many people.

**Comment by raineorshine** [comment]
Fixed and published in `v7.0.3-alpha.1`.
