### ISSUE TITLE
V 8.0.0+ Git ssh Private repository permission denied

### ISSUE THREAD

**Issue by meabed** [raineorshine/npm-check-updates#727]
- [x ] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

package json github repo with this format and private access `ssh://git@github.com/-username-/--repo-name--#master`

## Current Behavior
```
$ git ls-remote --tags ssh://github.com/-username-/--repo-name--
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

## Expected Behavior
it should work - as previous version 7.1.1 was working just fine.

**Comment by raineorshine** [comment]
Thanks for reporting! Fix published in `v8.0.2`.

**Comment by FND** [comment]
I'm afraid I'm still running into this issue with v8.0.2, @raineorshine:

*   `package.json` includes the following dependency, referencing a self-hosted GitLab instance:

    ```
    "my-lib": "git+ssh://git@git.example.org:my-org/my-lib.git#v2.3.0"
    ```

*   `ncu -u` reports:

    ```
    Error: Command failed: git ls-remote --tags git+ssh://git.example.org/:my-org/my-lib.git
    fnd@git.example.org: Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

        at ChildProcess.exithandler (child_process.js:308:12)
        at ChildProcess.emit (events.js:314:20)
        at maybeClose (internal/child_process.js:1051:16)
        at Socket.<anonymous> (internal/child_process.js:442:11)
        at Socket.emit (events.js:314:20)
        at Pipe.<anonymous> (net.js:673:12) {
      killed: false,
      code: 128,
      signal: null,
      cmd: 'git ls-remote --tags git+ssh://git.example.org/:my-org/my-lib.git',
      stdout: '',
      stderr: 'fnd@git.example.org: Permission denied (publickey).\r\n' +
        'fatal: Could not read from remote repository.\n' +
        '\n' +
        'Please make sure you have the correct access rights\n' +
        'and the repository exists.\n'
    }
    ```

    (note the `/:` in those URIs)

I'm afraid it's not obvious to me how 4b5e00cacdda047c852a7747689765ff777b4323 works exactly or how I might provide a patch.

**Comment by raineorshine** [comment]
> I'm afraid I'm still running into this issue with v8.0.2

I see, it's a different error than the one I reproduced, so it's not catching it.



> I'm afraid it's not obvious to me how [4b5e00c](https://github.com/raineorshine/npm-check-updates/commit/4b5e00cacdda047c852a7747689765ff777b4323) works exactly or how I might provide a patch.

It's [catching the error](https://github.com/raineorshine/npm-check-updates/commit/4b5e00cacdda047c852a7747689765ff777b4323#diff-9ac300b15e0564ec30e44f3c0a7c3efdR17-R26) and ignoring it if the repo is not found. I need to add a check for "Permission denied."

**Comment by raineorshine** [comment]
@FND Try `v8.0.3` please.

**Comment by FND** [comment]
Wow, that was very quick. Works as expected now, thank you very much - not just for the fix, but for all your efforts here.

**Comment by lukkirond** [comment]
Unfortunately I still have a similar issue.

As mentioned here ``https://docs.npmjs.com/files/package.json#git-urls-as-dependencies``,
I have a URL as following as dependency:

```
 git+https://example@github.com/npm/cli.git
```

Even with the latest version 8.0.3, I get an error 

```
...\lib\npm-check-updates.js:348
  throw err
  ^

Error: Command failed: git ls-remote --tags git+https://example@github.com/npm/cli.git
git: 'remote-git+https' is not a git command. See 'git --help'.

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git ls-remote --tags git+https://example@github.com/npm/cli.git',
  stdout: '',
  stderr: "git: 'remote-git+https' is not a git command. See 'git --help'.\n"
}
```

For the `git+ssh` URL format it works fine, as shown previously here in a different example.

My question is if this is a git issue, should the `git+https` URL format be supported by git, or maybe this could be fixed as an additional error check.

Thanks.

**Comment by raineorshine** [comment]
@lukkirond Thanks for reporting! It seems that there are a variety of errors from trying to run `git ls-remote` on certain git urls. gotta check em all...

Try `v8.0.4`!

**Comment by raineorshine** [comment]
> Thank you so much for fixing this. Now I can confirm on `v8.0.4` that with this special case `git+https`, it works great as it doesn't throw any error anymore.

Great

> Although the progress bar doesn't go now to 100% (as it skips the erroneous dependencies), but that's just nitpicking. :)

Thanks, good to know!
