### ISSUE TITLE
"--target newest" doesn't work in v9.0.0

### ISSUE THREAD

**Issue by Ky6uk** [raineorshine/npm-check-updates#734]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

I've used `ncu -n` to see new versions of the packages, including major/-beta/-rc releases. After updating `ncu` to `v9.0.0` the command `ncu --target newest` only shows just updated versions from the `latest` channel, like `ncu` without any additional arguments.

**Comment by raineorshine** [comment]
Thanks for reporting! Let me see what happened.

**Comment by raineorshine** [comment]
Fixed and published in `v9.0.1`
