### ISSUE TITLE
Unhandled exception when `--target` has unexpected value

### ISSUE THREAD

**Issue by Ky6uk** [raineorshine/npm-check-updates#735]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

`ncu --target woof` will throw an error with the stack trace to the output channel. I'm not sure, but it feels like something unhandled.

**Comment by raineorshine** [comment]
Yeah, we can do a nicer error message there. I'm going to wait until `commander.js` v7 when the `choices` feature is added.

https://github.com/tj/commander.js/pull/1331

**Comment by LitoMore** [comment]
I strongly recommend you to use [meow](https://github.com/sindresorhus/meow). For using meow, we don't need to wait any feature from upstream, because it's simple and powerful.

**Comment by raineorshine** [comment]
> I strongly recommend you to use [meow](https://github.com/sindresorhus/meow). 

Looks great, but I don't think it's worth switching cli frameworks just for validation, which can be easily implemented if we don't want to wait for commander. 

> For using meow, we don't need to wait any feature from upstream, because it's simple and powerful.

Actually, we're [waiting for help text generation](https://github.com/sindresorhus/meow/pull/140).

**Comment by LitoMore** [comment]
> Actually, we're [waiting for help text generation](https://github.com/sindresorhus/meow/pull/140).

I can help. :v:

**Comment by raineorshine** [comment]
This was done at some point
