### ISSUE TITLE
Private scoped dependencies ```--target minor``` problem

### ISSUE THREAD

**Issue by eventgo-admin** [raineorshine/npm-check-updates#737]
I have private scoped dependency from Github packages.

When I run ```npm info @scope/package-name```,  I get:
```
latest: 1.2.22
```

When I run ```npm outdated```, I get:
```
Package                          Current  Wanted  Latest  Location
@scope/package-name 1.2.19     1.2.22     1.2.22  @scope/project
```

When I run ```ncu --target minor``` I don`t get the change recommendation. 

But when I change the current version to 1.1.19 (update to minor version is available) I get:
```
 @scope/package-name  ^1.1.19  →   ^1.2.9
```

So it seems that for public packages, ```minor``` works, but for scoped private packages it does not work as expected.

**Comment by raineorshine** [comment]
Thanks for reporting!

Do you know why `1.2.9` is recommended when latest is `1.2.22`? 

Maybe we can get some clues from the output of:
- `ncu`
- `ncu --target newest`

**Comment by eventgo-admin** [comment]
Thank you for the quick reply

The result of ```ncu``` is:
```
@scope/package-name  ^1.2.19  →  ^1.2.22
```

The result of ```ncu --target newest``` is:
```
All dependencies match the latest package versions :)
```

The result of ``` ncu --target minor```
```
All dependencies match the minor package versions :)
```

**Comment by raineorshine** [comment]
Thanks. What about `ncu --target minor --loglevel verbose`?

Sorry for the remote troubleshooting. I'm not sure how to reproduce it on my end yet.

**Comment by eventgo-admin** [comment]
No worries at all, I am grateful for the support :)

When I run ```ncu --target minor --loglevel verbose```, I get:

```
> ncu --target minor --loglevel verbose

Initializing...
Running in local mode...
Finding package file data...
Checking D:\projects\project\package.json
Fetching minor versions...

Options (partial):
{
  registry: null,
  pre: undefined,
  packageManager: 'npm',
  json: false,
  enginesNode: undefined
}
[====================] 13/13 100%

Fetched:
{
  '@scope/package-name': '1.2.9',
  jest: '26.4.2',
  'npm-check-updates': '9.0.2',
 }

Upgraded:
{}

All dependencies match the minor package versions :)
```

When I run ``` npm outdated```, I get
```
Package                          Current  Wanted  Latest  Location
@scope/package-name 1.2.19     1.2.23     1.2.23  @scope/project
```

**Comment by eventgo-admin** [comment]
I also noticed that ```ncu``` returns ``` '@scope/package-name': '1.2.9',``` rather than ``` '@scope/package-name': '1.2.23',```

**Comment by raineorshine** [comment]
Yeah, it seems like `ncu` is fetching the wrong version (or rather filtering out the right version).

What do you get from `npm view @scope/package-name versions`? I think `--target minor` assumes the versions are sorted which could be the problem.

**Comment by eventgo-admin** [comment]
When I run ```npm view @scope/package-name versions```, I get:

```
[
  '1.1.27', '1.1.30', '1.1.31',
  '1.1.32', '1.1.33', '1.1.34',
  '1.1.36', '1.1.37', '1.2.1',
  '1.2.2',  '1.2.3',  '1.2.4',
  '1.2.5',  '1.2.6',  '1.2.7',
  '1.2.8',  '1.2.9',  '1.2.11',
  '1.2.12', '1.2.19', '1.2.22',
  '1.2.23', '1.2.24'
]
```

When I run ```npm view @scope/package-name time```, I get: 
```
{
  '1.1.27': '2020-07-07T07:56:17.000Z',
  '1.1.30': '2020-07-07T08:58:31.000Z',
  '1.1.31': '2020-07-07T09:57:29.000Z',
  '1.1.32': '2020-07-07T10:03:33.000Z',
  '1.1.33': '2020-07-07T10:06:23.000Z',
  '1.1.34': '2020-07-07T13:11:25.000Z',
  '1.1.36': '2020-07-15T18:47:26.000Z',
  '1.1.37': '2020-07-16T16:37:49.000Z',
  '1.2.1': '2020-07-16T16:41:26.000Z',
  '1.2.11': '2020-09-16T08:02:34.000Z',
  '1.2.12': '2020-09-17T07:36:07.000Z',
  '1.2.19': '2020-09-17T16:13:09.000Z',
  '1.2.2': '2020-07-16T16:59:04.000Z',
  '1.2.22': '2020-09-23T14:01:28.000Z',
  '1.2.23': '2020-09-23T17:14:35.000Z',
  '1.2.24': '2020-09-23T18:51:46.000Z',
  '1.2.3': '2020-07-16T19:30:09.000Z',
  '1.2.4': '2020-07-16T20:13:54.000Z',
  '1.2.5': '2020-07-29T19:29:58.000Z',
  '1.2.6': '2020-09-07T11:04:48.000Z',
  '1.2.7': '2020-09-09T10:36:26.000Z',
  '1.2.8': '2020-09-13T13:22:27.000Z',
  '1.2.9': '2020-09-15T08:30:33.000Z'
}
```


From what I understand it looks at the first digit of the patch version. For ex it thinks that ```1.2.9``` > ```1.2.2.9```

**Comment by raineorshine** [comment]
That's very strange. I checked the way it handles the patch and I don't see any indication that it is ignoring digits.

It certainly looks like it is using the last item in `npm view @scope/package-name time`, but `--target minor` [uses `npm view @scope/package-name versions`](https://github.com/raineorshine/npm-check-updates/blob/master/lib/package-managers/npm.js#L325).

At this point you'd have to add some console.logs to your installed `npm-check-updates` within the `minor` function indicated above to find out where it's going wrong. It could be that the wrong versions are fetched, that they are sorted incorrectly before the last is taken, or that they are being filtered incorrectly.

**Comment by eventgo-admin** [comment]
I think I fount the issue

In file ```version-util.js```, function ```findGreatestByLevel```, on line ```221```

you have this code

```
return greatestVersion[greatestVersion.length - 1]
```

and when the list looks like this 
```
[
  '1.1.27', '1.1.30', '1.1.31',
  '1.1.32', '1.1.33', '1.1.34',
  '1.1.36', '1.1.37', '1.2.1',
  '1.2.11', '1.2.12', '1.2.19',
  '1.2.2',  '1.2.22', '1.2.23',
  '1.2.24', '1.2.25', '1.2.26',
  '1.2.27', '1.2.28', '1.2.3',
  '1.2.31', '1.2.4',  '1.2.5',
  '1.2.6',  '1.2.7',  '1.2.8',
  '1.2.9'
]
```

It returns the last element of the array, rather than the latest version

**Comment by raineorshine** [comment]
Yup, that's it! I had had assumed the list would be sorted since `npm view @scope/package-name versions` is sorted, but I didn't notice that it is actually getting the version list from `pacote`, which returns then unsorted 🥴

I'll work on a fix

**Comment by raineorshine** [comment]
Published in `v9.0.3`. Can you confirm that it's fixed?

**Comment by eventgo-admin** [comment]
Yes, it works! 
Thank you a lot for the help :)

**Comment by o-alexandrov** [comment]
Same issue when updating a package from `2.0.9` to `2.0.10`.
- as the author of the issue, I have an issue w/ `private scoped dependencies`

Should I report it as a separate issue, or would you like more details here?

**Comment by o-alexandrov** [comment]
Strange, the issue appeared to be with `npm-check-updates` probably caching results internally (even though `--cache` flag wasn't passed), as after some time it successfully updated deps.

**Comment by o-alexandrov** [comment]
My issue is not related to this ticket. `npm-check-updates` incorrectly interprets `--target newest`, will report in a new issue
