### ISSUE TITLE
Feature request: Headers?

### ISSUE THREAD

**Issue by rodrigograca31** [raineorshine/npm-check-updates#738]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Feature request:
Headers

I was showing someone the following output of ncu:
![image](https://user-images.githubusercontent.com/1134310/94139975-79af4080-fe62-11ea-81fc-21a89c7a792b.png)

and noticed I would have to explain to the person that the left column is the packages needing updates, the middle is the current version and the right is the latest version if they were not familiar with ncu.

with that said I think some headers like this would be really nice:
![image](https://user-images.githubusercontent.com/1134310/94140385-140f8400-fe63-11ea-8013-48b17dd7dd3d.png)
![image](https://user-images.githubusercontent.com/1134310/94140570-53d66b80-fe63-11ea-99db-4e959867a778.png)

Thanks to whoever implements it! ❤

**Comment by raineorshine** [comment]
I feel like `^4.1.0 → ^4.2.0` is pretty self explanatory. I know it's easy to overestimate how intuitive or easy something is to understand when you are familiar with it yourself, but this is an extremely simple representation of two numbers. Presumably people who are using `npm-check-updates` installed it for a reason, which probably provides enough context for them to understand the output. 

I do think there could be a fuller output like that of [npm-check](https://github.com/dylang/npm-check) as an option.

I'm going to close this as it is not alignment with the current design direction (extreme minimalism) but thank you for the suggestion.
