### ISSUE TITLE
Problems while using ncu with newest versions and my package json...

### ISSUE THREAD

**Issue by JanWeskamp** [raineorshine/npm-check-updates#744]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X ] I am using the latest version of `npm-check-updates`
- [X ] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
use this package.json content:

`
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {},
    "dependencies": {
        "@fortawesome/fontawesome-free": "^5.15.0",
        "@fortawesome/fontawesome-pro": "^5.15.0",
        "@fullcalendar/bootstrap": "^5.3.1",
        "@fullcalendar/core": "^5.3.1",
        "@fullcalendar/daygrid": "^5.3.2",
        "@fullcalendar/interaction": "^5.3.1",
        "@fullcalendar/list": "^5.3.1",
        "@fullcalendar/moment": "^5.3.1",
        "@fullcalendar/moment-timezone": "^5.3.1",
        "@fullcalendar/timegrid": "^5.3.1",
        "@fullcalendar/vue": "^5.3.1",
        "@lgaitan/pace-progress": "^1.0.7",
        "admin-lte": "https://github.com/ColorlibHQ/AdminLTE.git#v3.0.0",
        "ajv": "^6.12.5",
        "axios": "^0.20",
        "bootstrap": "^4.5.2",
        "bootstrap-colorpicker": "^3.2.0",
        "bootstrap-datepicker": "^1.9.0",
        "bootstrap-slider": "^11.0.2",
        "bootstrap-switch": "^3.4.0",
        "bootstrap-wysiwyg": "^2.0.1",
        "bootstrap4-duallistbox": "^4.0.2",
        "bootstrap4-toggle": "^3.6.1",
        "chart.js": "^2.9.3",
        "cross-env": "^7.0",
        "datatables.net": "^1.10.22",
        "datatables.net-bs4": "^1.10.22",
        "datatables.net-dt": "^1.10.22",
        "daterangepicker": "^3.1.0",
        "dropzone": "5.7.2",
        "fastclick": "^1.0.6",
        "flag-icon-css": "^3.5.0",
        "flot": "^4.2.1",
        "highlight.js": "^10.2.1",
        "html2canvas": "^1.0.0-rc.7",
        "humanize-duration": "^3.24.0",
        "i": "^0.3.6",
        "icheck-bootstrap": "^3.0.1",
        "inputmask": "^5.0.5",
        "ion-rangeslider": "^2.3.1",
        "ionicons": "^5.1.2",
        "jquery": "^3.5.1",
        "jquery-knob-chif": "^1.2.13",
        "jquery-mapael": "^2.2.0",
        "jquery-mousewheel": "^3.1.13",
        "jquery-ui": "^1.12.1",
        "jquery-ui-dist": "^1.12.1",
        "jquery.easing": "^1.4.1",
        "jqvmap": "github:bbmumford/jqvmap",
        "jsgrid": "^1.5.3",
        "jspdf": "^2.1.1",
        "jspdf-autotable": "^3.5.13",
        "laravel-echo": "^1.8.1",
        "laravel-mix": "^5.0.5",
        "lodash": "^4.17.20",
        "masonry-layout": "^4.2.2",
        "md5": "^2.3.0",
        "moment": "^2.29.0",
        "morris.js": "^0.5.0",
        "nenasith-v-components": "^1.1.3",
        "overlayscrollbars": "^1.13.0",
        "packery": "^2.1.2",
        "popper.js": "^1.16",
        "pusher-js": "^7.0.0",
        "raphael": "^2.3.0",
        "resolve-url-loader": "3.1.1",
        "sass": "^1.26.11",
        "sass-loader": "^8.0.2",
        "select2": "^4.0.13",
        "slimscroll": "^0.9.1",
        "socket.io": "^2.3.0",
        "socket.io-client": "^2.3.1",
        "sparklines": "^1.2.0",
        "summernote": "^0.8.18",
        "sweetalert2": "^10.3.5",
        "tempusdominus-bootstrap-4": "^5.1.2",
        "tinymce": "^5.2.2",
        "toastr": "^2.1.4",
        "vue": "^2.6.12",
        "vue-easy-lightbox": "^0.14.0",
        "vue-echo": "^1.0.2",
        "vue-fullcalendar": "^1.0.9",
        "vue-route-laravel": "^1.0.4",
        "vue-template-compiler": "^2.6.12",
        "vue-typeahead": "^2.3.2"
    }
}

`
## Current Behavior
[=======-------------] 30/85 35%/Users/janweskamp/.nvm/versions/node/v14.13.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:353
  throw err
  ^

TypeError: Invalid Version: 1.0
    at new SemVer (/Users/janweskamp/.nvm/versions/node/v14.13.0/lib/node_modules/npm-check-updates/node_modules/semver/classes/semver.js:41:13)
    at compare (/Users/janweskamp/.nvm/versions/node/v14.13.0/lib/node_modules/npm-check-updates/node_modules/semver/functions/compare.js:3:3)
    at Object.gt (/Users/janweskamp/.nvm/versions/node/v14.13.0/lib/node_modules/npm-check-updates/node_modules/semver/functions/gt.js:2:29)
    at compareVersions (/Users/janweskamp/.nvm/versions/node/v14.13.0/lib/node_modules/npm-check-updates/lib/version-util.js:221:17)
    at Array.sort (<anonymous>)
    at Object.greatest (/Users/janweskamp/.nvm/versions/node/v14.13.0/lib/node_modules/npm-check-updates/lib/package-managers/gitTags.js:30:41)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getPackageVersionProtected (/Users/janweskamp/.nvm/versions/node/v14.13.0/lib/node_modules/npm-check-updates/lib/versionmanager.js:474:14)
    at async /Users/janweskamp/.nvm/versions/node/v14.13.0/lib/node_modules/npm-check-updates/node_modules/p-map/index.js:57:22

## Expected Behavior
run trough ^^?

**Comment by raineorshine** [comment]
Indeed! This appears to be a bug in the git tag detection. I will investigate.

**Comment by JanWeskamp** [comment]
That was pretty fast <3
