### ISSUE TITLE
--minimal option not working

### ISSUE THREAD

**Issue by stonebat** [raineorshine/npm-check-updates#746]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
ncu --minimal

## Current Behavior
 graphql      ~14.3.0  →   ~15.3.0
 react       ~16.13.0  →  ~16.14.0
 react-dom   ~16.13.0  →  ~16.14.0
 typescript    ~3.9.0  →    ~4.0.3

## Expected Behavior
 graphql      ~14.3.0  →   ~14.3.1
 react       ~16.13.0  →  ~16.13.1
 react-dom   ~16.13.0  →  ~16.13.1
 typescript    ~3.9.0  →    ~3.9.7

**Comment by raineorshine** [comment]
`--minimal` is intended to ignore upgrades that are already satisfied by the specified version range. graphql `15.3.0` is not satisfied by your specified version: `14.3.0`, so the upgrade is suggested.

Are you looking for `--target minor`? That will exclude major version upgrades.

**Comment by stonebat** [comment]
@raineorshine Thank you!  ncu --target patch did the job for me.

**Comment by thw0rted** [comment]
Does `target` respect the common convention of special handling of `0.x.y` versions?  I see some debate on the `semver` tracker about whether a "magic zero" makes sense but I think it's pretty common to basically treat `0.x.y` as `0.major.minor` (with no patch), in terms of compatibility.

**Comment by raineorshine** [comment]
@thw0rted The current implementation does not have special handling for `0.x.y`, although I can see your point. I'm not sure if it's worth making a breaking change, but I'm definitely open to a PR for a new option `--pre-1` that enables the behavior you are suggesting.
