### ISSUE TITLE
Fails if some NPM dependencies start with `git+https://`

### ISSUE THREAD

**Issue by prantlf** [raineorshine/npm-check-updates#747]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

1. Add a dependency on a branch on GitHub or GitLab using its URL instead of the NPM version number, for example:

```
"csui-dependency-installer": "git+https://gitlab.otxlab.net/prantlf/csui-dependency-installer.git#v2.x",
```

2. Attempt updating all NPM dependencies:

```
LANG=de ncu -u
```

## Current Behavior

Attempting to update all NPM dependencies fails with the German locale:

```
$ LANG=de ncu -u
Upgrading /Users/prantlf/Sources/gitlab/greetings/package.json
[=-------------------] 2/61 3%/Users/prantlf/.nvm/versions/node/v12.19.0/pnpm-global/4/node_modules/.pnpm/npm-check-updates@9.1.0/node_modules/npm-check-updates/lib/npm-check-updates.js:353
  throw err
  ^

Error: Command failed: git ls-remote --tags git+https://gitlab.otxlab.net/prantlf/csui-dependency-installer.git
fatal: Konnte Remote-Helper für 'git+https' nicht finden.

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 128,
  signal: null,
  cmd: 'git ls-remote --tags git+https://gitlab.otxlab.net/prantlf/csui-dependency-installer.git',
  stdout: '',
  stderr: "fatal: Konnte Remote-Helper für 'git+https' nicht finden.\n"
}
```

While using the English locale, it succeeds:

```
$ LANG=en ncu -u
Upgrading /Users/prantlf/Sources/gitlab/greetings/package.json
[===================-] 58/61 95%
 karma   5.1.1  →  5.2.3
 printf  0.5.3  →  0.6.0

Run npm install to install new versions.
```

## Expected Behavior

Dependencies starting with `git+https://` should be silently ignored. The behavior should be independent on the chosen locale.

Thank you!

**Comment by raineorshine** [comment]
> The behavior should be independent on the chosen locale.

Thanks for reporting! Fixed and published in `v9.1.1`.

> Dependencies starting with `git+https://` should be silently ignored.

Actually, support for `git` urls were [added in v8](https://github.com/raineorshine/npm-check-updates/releases?after=v8.0.5). However, I see that urls with the `git+https` protocol were breaking. I fixed this and published it in `v9.1.2`.

**Comment by prantlf** [comment]
Thanks a lot for the quick fix!

**Comment by drmrbrewer** [comment]
@raineorshine I am using `v9.1.2` and have a dependency starting with `git+https://`... now I am finding that `ncu -u` is pausing and asking me for my bibucket login... this didn't happen before??  Presumably this is to check for the latest version of the dependency.  And even if I do enter my login details, I then just get the following error:

	/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:353
	  throw err
	  ^

	TypeError: Invalid Version: undefined
		at new SemVer (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/semver/classes/semver.js:41:13)
		at outside (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/semver/ranges/outside.js:12:13)
		at Object.ltr (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/semver/ranges/ltr.js:3:42)
		at isUpgradeable (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/lib/versionmanager.js:211:17)
		at /root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/lib/versionmanager.js:160:67
		at /root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:13616:16
		at basePickBy (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:3783:13)
		at Function.pickBy (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:13615:14)
		at /root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:4388:28
		at arrayReduce (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:683:21)

Perhaps I haven't defined the version number in my repo properly (not sure how), but in any case:

(a) ncu shouldn't throw a horrible error but should give a nice and friendly message instead
(b) ncu should remember my bitbucket login details somehow... I really don't want to have to enter them every time... or I'd rather just switch this feature off

**Comment by drmrbrewer** [comment]
In fact, having looked at what I'm doing with versions, I am actually just applying a `tag` to each commit, with the `tag` incrementing each time.  This allows me to target a particular "version" (or tag) in my package.json like so:

    "myrepo": "git+https://myrepo:kjsdn9sdfknf@bitbucket.org/myaccount/myrepo.git#v423"

Perhaps this isn't conventional, not sure if it is or isn't, but it works for me... just letting you know in case it helps avoid throwing an error in this situation.

**Comment by raineorshine** [comment]
> am using `v9.1.2` and have a dependency starting with `git+https://`... now I am finding that `ncu -u` is pausing and asking me for my bitbucket login... this didn't happen before??

That's correct. There was a bug that was causing ncu to ignore the `git+https` protocol. 

> Perhaps I haven't defined the version number in my repo properly (not sure how),

~Can you post how this dependency is specified? That would help me troubleshoot. I will need to find a way to reproduce the issue on my side to find a solution.~

> (a) ncu shouldn't throw a horrible error but should give a nice and friendly message instead

Agreed.

> (b) ncu should remember my bitbucket login details somehow... I really don't want to have to enter them every time... or I'd rather just switch this feature off

Yeah, it must be npm prompting you for your credentials, as it's not directly part of ncu. Maybe there is a saved token that can be passed to npm to avoid this? More investigation needed, although I don't have time to pursue this myself unfortunately. You can disable dependencies by adding an `ncurc.json` file with the value `{  "reject": ["NAME"]. }`

**Comment by drmrbrewer** [comment]
Update... and this is how I commit with the tag:

	git add -A .
	git commit -m "misc"
	git tag -a "123" -m "version 123"
	git push --follow-tags origin master

**Comment by raineorshine** [comment]
> In fact, having looked at what I'm doing with versions, I am actually just applying a `tag` to each commit, with the `tag` incrementing each time. This allows me to target a particular "version" (or tag) in my package.json like so:
> 
> ```
> "myrepo": "git+https://myrepo:kjsdn9sdfknf@bitbucket.org/myaccount/myrepo.git#v423"
> ```
> 
> Perhaps this isn't conventional, not sure if it is or isn't, but it works for me... just letting you know in case it helps avoid throwing an error in this situation.

Thanks, that's helpful! I should be able to procure a test case. `#v423` is not valid semver, but it seems pretty unambiguous, so I don't see a reason we can't support it.

**Comment by raineorshine** [comment]
> Update... and this is how I commit with the tag:
> 
> ```
> git add -A .
> git commit -m "misc"
> git tag -a "123" -m "version 123"
> git push --follow-tags origin master
> ```

Do you do `git tag -a "123"` or `git tag -a "v123"`, and does it vary?

**Comment by drmrbrewer** [comment]
Ah you are correct to ask... it is actually "v123"... here are all my secrets laid bare... this is the script I use, where `version_file` is just a text file holding the version number:

	version_file="./version"
	current_version="$(cat ${version_file})"
	new_version=$((current_version+1))
	printf ${new_version} > ${version_file}
	tag="v${new_version}"

	COMMIT_MESSAGE="miscellaneous changes"
	if [[ $# -eq 1 ]] ; then
		COMMIT_MESSAGE="${1}"
	fi

	git add -A .
	git commit -m "${COMMIT_MESSAGE}"
	git tag -a "${tag}" -m "version ${tag}"
	git push --follow-tags origin master

Perhaps I can modify the versioning to make it fit with what ncu is expecting, rather than vice versa?

**Comment by drmrbrewer** [comment]
So is the point of this feature of ncu that it can check and update the latest version in the package.json, even for these dependencies... assuming it knows the credentials to access the remote repo of course?

**Comment by drmrbrewer** [comment]
And this is how the commits look in bitbucket (forgive the lazy commit messages):

![image](https://user-images.githubusercontent.com/9009792/97039139-da19c680-1563-11eb-96f2-bd931da2d73f.png)

**Comment by raineorshine** [comment]
> So is the point of this feature of ncu that it can check and update the latest version in the package.json, even for these dependencies... assuming it knows the credentials to access the remote repo of course?

Yup. It uses [remote-git-tags](https://github.com/sindresorhus/remote-git-tags) to check for newer tags when it detects a tag in semver format.

See: https://github.com/raineorshine/npm-check-updates/blob/master/test/test-versionmanager.js#L490-L498

I still need to consider how conservative to be with parsing non-semver tags. For example, someone might have a dependency pointing to `#123` where `123` is a branch name referring to an issue rather than a version. Semver only is the best bet, but `v123` seems unproblematic.

**Comment by drmrbrewer** [comment]
> `v123` seems unproblematic

that would be good... for me a full semver tag is slightly overkill because this repo is only ever seen by me so a one-part incrementing version number is all I need.

**Comment by raineorshine** [comment]
@drmrbrewer Will you try out `v9.2.0`? I did a first pass on adding support for tags in the format "v1".

Note that I didn't get the same error as you. Mine added `undefined` to the version string rather than throwing an error. If you're still getting the error when might have to do some more digging.

**Comment by drmrbrewer** [comment]
Same error I think :-(

	/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:353
	  throw err
	  ^

	TypeError: Invalid Version: v493
		at new SemVer (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/semver/classes/semver.js:41:13)
		at outside (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/semver/ranges/outside.js:12:13)
		at Object.ltr (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/semver/ranges/ltr.js:3:42)
		at isUpgradeable (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/lib/versionmanager.js:211:17)
		at /root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/lib/versionmanager.js:160:67
		at /root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:13616:16
		at basePickBy (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:3783:13)
		at Function.pickBy (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:13615:14)
		at /root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:4388:28
		at arrayReduce (/root/.nvm/versions/node/v12.19.0/lib/node_modules/npm-check-updates/node_modules/lodash/lodash.js:683:21)


version check:

    ncu --version
    9.2.0

relevant part of package.json:

	"dependencies": {
		"aaaaaaaaa": "git+https://xxxxx:khakjhasd8yusda@bitbucket.org/yyyyyy/aaaaaaaaa.git#v493",
		"express": "^4.17.1"
	},

**Comment by raineorshine** [comment]
Okay, the stack trace should give me enough to make another attempt!

**Comment by raineorshine** [comment]
Please try `v9.2.2`

**Comment by drmrbrewer** [comment]
It works!  However, I still have to enter my bitbucket credentials every time, which amounts to the same as just ignoring any `git+https` dependency because I'm not going to enter them each time I run `ncu -u`... or nearly amounts to the same because the update process stalls every time waiting for the credentials which is irritating... at least you can just Enter/Enter to supply null information and the process completes but it's a shame that the credentials aren't just remembered.

**Comment by prantlf** [comment]
@drmrbrewer, I do not have to enter the credentials every time. Did add your machine key as an SSH key to Bitbucket profile?

**Comment by drmrbrewer** [comment]
@prantlf yep I have.  I am pushing commits to this bitbucket repo all the time from the same machine, without prompting.

**Comment by raineorshine** [comment]
> It works!

Great!

> However, I still have to enter my bitbucket credentials every time, which amounts to the same as just ignoring any `git+https` dependency

I'm not sure how to reproduce that unfortunately. If you'd like to open another issue we can at least track it.

**Comment by drmrbrewer** [comment]
>  If you'd like to open another issue we can at least track it.

Done [here](https://github.com/raineorshine/npm-check-updates/issues/748)... thanks!

**Comment by lamuertepeluda** [comment]
I have an issue that might be related to this one or #774. ncu version `9.2.3` (latest) and Node 14.15.0 LTS

```bash
Checking /home/vito/Development/my-project/package.json
[========------------] 44/112 39%/home/vito/.nvm/versions/node/v14.15.0/lib/node_modules/npm-check-updates/lib/npm-check-updates.js:353
  throw err
  ^

TypeError: Invalid Version: v0.1.3a
    at new SemVer (/home/vito/.nvm/versions/node/v14.15.0/lib/node_modules/npm-check-updates/node_modules/semver/classes/semver.js:41:13)
    at compare (/home/vito/.nvm/versions/node/v14.15.0/lib/node_modules/npm-check-updates/node_modules/semver/functions/compare.js:3:3)
    at Object.gt (/home/vito/.nvm/versions/node/v14.15.0/lib/node_modules/npm-check-updates/node_modules/semver/functions/gt.js:2:29)
    at compareVersions (/home/vito/.nvm/versions/node/v14.15.0/lib/node_modules/npm-check-updates/lib/version-util.js:221:17)
    at Array.sort (<anonymous>)
    at Object.greatest (/home/vito/.nvm/versions/node/v14.15.0/lib/node_modules/npm-check-updates/lib/package-managers/gitTags.js:29:6)
    at async getPackageVersionProtected (/home/vito/.nvm/versions/node/v14.15.0/lib/node_modules/npm-check-updates/lib/versionmanager.js:480:20)
    at async /home/vito/.nvm/versions/node/v14.15.0/lib/node_modules/npm-check-updates/node_modules/p-map/index.js:57:22
```

* I have a legacy project ported from bower to npm, with some old libraries that might not follow semver accurately
* I searched in the node_modules and no package contains a version similar to `v0.1.3a`
* **reverting to ncu@8** solved this issue

But I still wonder what can be causing this.

Would it be possibile to catch this kind of exception and write a warning instead of crashing?

**Comment by raineorshine** [comment]
@lamuertepeluda Let's open a new issue, since I think something else is causing this error.

Please narrow it down to a specific dependency in your package.json that causes the error. This should just be a matter of deleting dependencies from your package.json and running ncu until the error goes away. I tried running ncu on a package with an invalid version of `v0.1.3a` but it skipped it without erroring for me. I can see it is a git url dependency, not an npm module, since `gitTags.js` is in the stack trace.

Please include the result of `git ls-remote --tags https://github.com/...`. Thanks!

**Comment by lamuertepeluda** [comment]
@raineorshine thank you for the advice. The culprit is https://github.com/gcareri/angular-toasty.git#1.0.7, a forked legacy package that was available on bower 🤦 

I opened #758
