### ISSUE TITLE
Always prompts for bitbucket credentials when running ncu -u

### ISSUE THREAD

**Issue by drmrbrewer** [raineorshine/npm-check-updates#748]
I have a dependency that links to a bitbucket repo like so:

	"dependencies": {
		"myamazingthing": "git+https://xxxxx:khakjhasd8yusda@bitbucket.org/yyyyyy/myamazingthing.git#v493"
	}

When I run:

    ncu -u

the process pauses to ask for bitbucket credentials:

    # ncu -u
    Upgrading /root/workspace/test/package.json
    [============--------] 6/10 60%Username for 'https://bitbucket.org': 

For starters, the prompt should ideally be separated from the progress indicator... currently there is no gap.  Sometimes the "username" prompt appears briefly then disappears completely (seems to be overwritten again by the progress bar?).

But mainly, the problem is that after entering my bitbucket username and password, although it works (accesses bitbucket and updates the version number in package.json if appropriate)... it prompts for the credentials each and every time I run `ncu -u`.

I do have the server's ssh key stored in bitbucket, in the Security section of Personal Settings:

![image](https://user-images.githubusercontent.com/9009792/97087027-e31b9e00-161e-11eb-82aa-080e6f845bc7.png)

I am able to push commits to this same repo from the same server, without issue and without prompts.

Any ideas how I get the credentials to be remembered when using ncu?

**Comment by raineorshine** [comment]
It might be related to passing through the npm config and certificates  to pacote:
https://github.com/raineorshine/npm-check-updates/blob/master/lib/package-managers/npm.js#L15-L53

It would be helpful to narrow down whether it's coming from npm or pacote.

**Comment by drmrbrewer** [comment]
How would you suggest we narrow it down?

**Comment by raineorshine** [comment]
Actually I realize it's using remote git tags, not pacote, so it's probably trigged by `remote-git-tags`. I would start by adding a `console.log` statement on either side of the [call to `remoteGitTags`](https://github.com/raineorshine/npm-check-updates/blob/master/lib/package-managers/gitTags.js#L17) and confirm that the prompt is appearing in between.

You should also run `git ls-remote` directly since that is all that `remote-git-tags` [is doing](https://github.com/sindresorhus/remote-git-tags/blob/master/index.js#L8) and see if the same prompt occurs.

```sh
git ls-remote --tags https://xxxxx:khakjhasd8yusda@bitbucket.org/yyyyyy/myamazingthing.git
```

**Comment by drmrbrewer** [comment]
With `git ls-remote --tags https://xxxxx:khakjhasd8yusda@bitbucket.org/yyyyyy/myamazingthing.git` I just get:

    fatal: unable to find remote helper for 'git+https'

**Comment by raineorshine** [comment]
> With `git ls-remote --tags https://xxxxx:khakjhasd8yusda@bitbucket.org/yyyyyy/myamazingthing.git` I just get:
> 
> ```
> fatal: unable to find remote helper for 'git+https'
> ```

I wouldn't expect that error from `git ls-remote --tags https://...`. Are you sure you didn't accidentally enter `git ls-remote --tags git+https://...`?

It should return a list of tags. Once you get that working, I'd be curious to know if it prompts you for your bitbucket credentials, and furthermore if running it multiple times prompts you each time.

**Comment by drmrbrewer** [comment]
Dang, you're right... I was using `git+` when I shouldn't.  Without that, running `git ls-remote --tags https://xxxxx:khakjhasd8yusda@bitbucket.org/yyyyyy/myamazingthing.git` I get something like:

	439de0007256f07ad68607e3e7d42ef313203f89        refs/tags/v95
	737e68a6feba3d0016b8c4ada18e3168608eead6        refs/tags/v95^{}
	47b4ccc8d5647d93526ec684ce4d1992b0228a8e        refs/tags/v96
	3224d5962bcf0ad2b1debf9620b43745db31cf16        refs/tags/v96^{}
	d2500c2f6cdba4acbc2a1668724aa868dd354de1        refs/tags/v97
	13347526adeae9a346754d0779d09dc0443c6a34        refs/tags/v97^{}
	cfc0002b19df53d05610824d8c0e16a9159c9d12        refs/tags/v98
	0955647924b09fc833a3cefd539e91a87a8b97fe        refs/tags/v98^{}
	2fd09289cff53305caa77d1dc92c4432c6c9b717        refs/tags/v99
	02f0ef10eb05a526396549bc0d36139b6912883c        refs/tags/v99^{}

(without being asked for credentials)

**Comment by raineorshine** [comment]
I created a private bitbucket repo and tested this out myself. When running `ncu` I only had to enter my credentials once. I'm not sure why it's prompting you every time unfortunately.

**Comment by drmrbrewer** [comment]
I tried using `remote-git-tags` in a test node app, using the same repo path, and it works fine, without any prompt or error:

    const remoteGitTags = require('remote-git-tags')
    const tags = await remoteGitTags('https://xxxxx:khakjhasd8yusda@bitbucket.org/yyyyyy/myamazingthing.git');
    console.log('tags', tags);

    tags Map {
      'v10' => '104c9666dcb7ad9bb3901657e2688da9ac435297',
      ...
      'v100' => '661f8acc2759301640d58ea947471c18c2e2ddf7',
      'v101' => '6ec8e0e2669300213a3c822b37ef1f59c89a80b4',
    }

Where does the prompt `Username for 'https://bitbucket.org'` in `npm-check-updates` actually come from?  I can't see anything in the npm code with that wording.  Just wondering where/how it is actually triggered.

**Comment by raineorshine** [comment]
I think I may have found it! The auth was being parsed out of the dependency and not added to the url passed to `git ls-remote`: 4e0eba8. 

Can you try `npm install -g npm-check-updates@9.2.3-alpha.0`?

> And thinking about it further, the username and password are actually specified in the dependency itself... I am specifying it in the form:
> 
> ```
> git+https://username:password@bitbucket.org/username/myrepo.git#v493
> ```

Wouldn't that mean your password is in plaintext in your repo?

**Comment by drmrbrewer** [comment]
> Can you try `npm install -g npm-check-updates@9.2.3-alpha.0`?

With this version, `ncu -u` runs without asking for credentials... but also has no effect on the (out of date) dependency... almost as if the dependency is ignored.

> Wouldn't that mean your password is in plaintext in your repo?

Yes, but in order to get to the plaintext password you need to know the password :)  Plus, I wouldn't be too distraught if someone would be interested enough to get into this repo... might even be flattered :)

**Comment by raineorshine** [comment]
> > Can you try `npm install -g npm-check-updates@9.2.3-alpha.0`?
> 
> With this version, `ncu -u` runs without asking for credentials... but also has no effect on the (out of date) dependency... almost as if the dependency is ignored.

That probably solved the credential issue. I'll open a new issue to troubleshoot the unexpected output
