### ISSUE TITLE
The "Update available" notification does not display correctly

### ISSUE THREAD

**Issue by rmuchall** [raineorshine/npm-check-updates#751]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X] I am using the latest version of `npm-check-updates`
- [X] I am using `node >= 10.17`

---------------------------

The "update available" notification appears to be broken.

## Steps to Reproduce
Wait for the "update available" notification to display.

## Current Behavior
![ncu-error](https://user-images.githubusercontent.com/9222511/97299234-91f0f180-184c-11eb-8d5a-986551062a1a.png)

## Expected Behavior
Should display correctly.

**Comment by raineorshine** [comment]
Please file an issue at [update-notifier](https://github.com/yeoman/update-notifier). Thanks!
