### ISSUE TITLE
--target semver major and --semverLevel major broken

### ISSUE THREAD

**Issue by OzBob** [raineorshine/npm-check-updates#765]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates` (v10.0.0)
- [x] I am using node v12.4.0

---------------------------
Reading #652 (https://github.com/raineorshine/npm-check-updates/issues/652#issuecomment-628950448) referring to "major" being available from version 6, I assumed [major](https://github.com/raineorshine/npm-check-updates/blob/28e61f5394fdec9269d8e9a6bed069dfed61940f/lib/npm-check-updates.js#L248) would work.

```ncu -u --target major```

I am attempting to upgrade to the next Angular major version, e.g. from 7.0.0 to 8.2.14 (and then on up to 9.1.12 and 10.2.3). Below I have used a simpler example to demonstrate the error.

## Steps to Reproduce
npm -install cake@1.0.0
ncu
ncu -u --target major
ncu -u --target semver major
ncu -u --semverLevel major

## Current Behavior
λ ncu
Checking ...\package.json
[====================] 1/1 100%
 chalk  ^1.0.0  →  ^4.1.0

Run ncu -u to upgrade package.json

```
λ ncu -u --target major
Error: Unsupported target: major. Supported version targets are: latest, newest, greatest, minor, patch
    at queryVersions (...\AppData\Roaming\npm\node_modules\npm-check-updates\lib\versionmanager.js:461:27)
    at Object.upgradePackageDefinitions (...\AppData\Roaming\npm\node_modules\npm-check-updates\lib\versionmanager.js:308:32)
    at analyzeProjectDependencies (...\AppData\Roaming\npm\node_modules\npm-check-updates\lib\npm-check-updates.js:141:39)
    at getAnalysis (...\AppData\Roaming\npm\node_modules\npm-check-updates\lib\npm-check-updates.js:414:30)
```

## Expected Behavior
Package(s) upgraded to the next semver major version above the current version
E.g. https://www.npmjs.com/package/chalk
has the following versions:
1.0.0
2.4.2
3.0.0
4.1.0

Expected upgraded version would be from 1.0.0 to 2.4.2

**Comment by raineorshine** [comment]
`npm-check-updates` does not support upgrading a single major version. It will always upgrade to the latest major version. I would recommend running `npm install --save angular@7`, `npm install --save angular@8`, `npm install --save angular@9`, etc.

FYI `--target major` was changed to `--target minor` in [v8](https://github.com/raineorshine/npm-check-updates/blob/master/CHANGELOG.md#800---2020-08-29) to better match user expectations.
