### ISSUE TITLE
after upgrading to node 14 - if (cb) cb.apply(this, arguments)

### ISSUE THREAD

**Issue by theskillwithin** [raineorshine/npm-check-updates#766]
after upgrading to node 14 (before was using node 12), i get error

` if (cb) cb.apply(this, arguments)`

whats interesting here as well is in the path error i see yarn for some reason

```
➜  scout git:(master) npm i -g npm-check-updates
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/Users/Austin/.nvm/versions/node/v14.15.0/bin/npm-check-updates -> /Users/Austin/.nvm/versions/node/v14.15.0/lib/node_modules/npm-check-updates/bin/cli.js
/Users/Austin/.nvm/versions/node/v14.15.0/bin/ncu -> /Users/Austin/.nvm/versions/node/v14.15.0/lib/node_modules/npm-check-updates/bin/cli.js
+ npm-check-updates@10.0.0
added 285 packages from 146 contributors in 8.54s
➜  scout git:(master) ncu
Using /Users/Austin/Projects/CEGE/policy-scout/package.json
/Users/Austin/.config/yarn/global/node_modules/npm/node_modules/graceful-fs/polyfills.js:267
      if (cb) cb.apply(this, arguments)
                 ^

TypeError: cb.apply is not a function
    at /Users/Austin/.config/yarn/global/node_modules/npm/node_modules/graceful-fs/polyfills.js:267:18
    at FSReqCallback.oncomplete (fs.js:184:5)
➜  scout git:(master) npm install -g yarn
```

which ncu gives `/usr/local/bin/ncu`

**Comment by raineorshine** [comment]
What about `which npm`? `ncu` will use the `npm` that is on your `PATH`. `/Users/Austin/.config/yarn/global/node_modules/npm/` suggests that it is using a version globally installed with `yarn` rather than the expected `/Users/Austin/.nvm/versions/node/v14.15.0/bin/npm`.

I don't currently have a way to reproduce this and the tests are passing for node v14, so I'm guessing it's not a problem with `ncu`.

**Comment by theskillwithin** [comment]
which npm: `/Users/Austin/.nvm/versions/node/v14.15.0/bin/npm`
which ncu: `/usr/local/bin/ncu`

**Comment by theskillwithin** [comment]
i run `ll -a /usr/local/bin/ncu`.  looks like its symlinked.

how on earth that happened idk, i think yarn won't even let you install the package.
any why it's only on node 14 also escapes me.



```
ll -a /usr/local/bin/ncu
lrwxr-xr-x  1 Austin  admin    63B Nov 27  2018 /usr/local/bin/ncu -> ../../../Users/Austin/.config/yarn/global/node_modules/.bin/ncu
``

switching back and forth again seem to have magically fixed it

```
➜  ~ nvm use 12
Now using node v12.19.0 (npm v6.14.8)
➜  ~ which npm
/Users/Austin/.nvm/versions/node/v12.19.0/bin/npm
➜  ~ which ncu
/Users/Austin/.nvm/versions/node/v12.19.0/bin/ncu
➜  ~ nvm use 14
Now using node v14.15.0 (npm v6.14.8)
➜  ~ which npm
/Users/Austin/.nvm/versions/node/v14.15.0/bin/npm
➜  ~ which ncu
/Users/Austin/.nvm/versions/node/v14.15.0/bin/ncu
```
