### ISSUE TITLE
No updates for global installed npm package

### ISSUE THREAD

**Issue by nesc58** [raineorshine/npm-check-updates#767]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] am using the latest version of `npm-check-updates`
- [x] am using `node >= 10.17`

---------------------------

## Steps to Reproduce
Installed versions
```
npm list -g
C:\Program Files\nodejs
+-- npm-check-updates@10.0.0
`-- npm@7.0.8
```

```
node -v
v15.2.0
```
Execute `ncu -g`

## Current Behavior
```
ncu -g
[====================] 2/2 100%

All global packages are up-to-date :)
```

## Expected Behavior
Should show npm updates.
Current npm version is 7.0.10

In earlier versions npm updates are listed when executing `ncu -g`.

**Comment by raineorshine** [comment]
This is due to a bug in npm `v7`-`v7.0.10`. See https://github.com/npm/cli/pull/2155.

As soon as that PR is merged and published, it should work. In the mean time, you can use npm `v6`.

**Comment by XhmikosR** [comment]
@raineorshine this should be fixed upstream AFAICT.

**Comment by raineorshine** [comment]
Great!

@nesc58 Let us know if it's still an issue for you.
