### ISSUE TITLE
Incorrect message is shown to install packages when using yarn

### ISSUE THREAD

**Issue by PieterBoeren** [raineorshine/npm-check-updates#773]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

- Use yarn as package manager
- Run an 'ncu -u' on your project (making sure there are some updates required)

## Current Behavior
Message is shown to run '**npm** install'

## Expected Behavior
Message is shown to run '**yarn** install'

I have created a PR to address this issue: #772

**Comment by raineorshine** [comment]
Thanks!
