### ISSUE TITLE
[Suggestion] Attach link comparing from and to releases for dependencies with new versions

### ISSUE THREAD

**Issue by Belco90** [raineorshine/npm-check-updates#775]
Hi there! This is not an issue to report a bug but to suggest a new simple feature.

I'm a huge fan of this package, I use it quite often for both professional and personal projects. My usual workflow is: after running `ncu` and see the list of current --> latest packages versions, I compare all the releases changelogs within this tool I built for doing so: https://octoclairvoyant.vercel.app/

I released recently the ability to share by url some repo with from and to versions fixed to be compared. So for example I ran `ncu` today and I got my `lint-staged` version was v10.3.0 but latest is v10.5.3. So I went this this app I built, searched for lint-staged, then picked those 2 versions and compared the changes (specially breaking ones). Everything seemed fine to me, so I told `ncu` to upgrade the version. As I mentioned, octoclairvoyant comparisons are shareable, so this is the one I used to check lint-staged changes: https://octoclairvoyant.vercel.app/?repo=okonet%2Flint-staged&from=v10.3.0&to=latest

As you can see, the url is built just using repo owner and name, desired from version and desired to version. So I was thinking if this package could build the url to display it next to each repo version:

![image](https://user-images.githubusercontent.com/2677072/102375486-db46fd00-3fc2-11eb-914b-6b857c29e60b.png)

What do you think about this? I'd be happy to help implementing this but I'd like to get some feedback first.

Thanks!

**Comment by raineorshine** [comment]
Hey, thanks for the suggestion!

octoclairvoyant looks like a great tool, but npm-check-updates has no plans for 3rd party integrations.

This would be a great case for [programmatic usage](https://github.com/raineorshine/npm-check-updates/#moduleprogrammatic-usage) of npm-check-updates. You could wrap the results, perform your own processing on them, and render them in a custom format.

**Comment by Belco90** [comment]
Ok, I see. Thanks for the programmatic usage doc, I missed that one. I'll try to wrap the results around that + my app.
