### ISSUE TITLE
Doctor Should Use Custom Script

### ISSUE THREAD

**Issue by einfallstoll** [raineorshine/npm-check-updates#777]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

Using `--doctor` should allow to use a different script than `test`. I use `npm ci` to spin up a test server and run end-to-end integration tests whereas `test` only runs the tests itself.

Also, it would be nice to run multiple steps (e.g. running `build` beforehand).

**Comment by raineorshine** [comment]
Good suggestions. How about a `--doctor-x` option that allows you to specify a custom test command? Or do you need a hook for the install command as well?

**Comment by einfallstoll** [comment]
Sounds good. Something like `--doctor-script`.

How to solve the `build` before testing? I see ncu as an external addon which should not influence the module, therefore it would be a bit ugly to add a `build-then-test` script to `package.json`. Maybe it could look like `--doctor-scripts build,do-things,other-things,test`?

For the install hook: What scenario comes to your mind? I immediately thought about some `clean` script, but you could add this to the `--doctor-scripts` as the first parameter?

**Comment by raineorshine** [comment]
> How to solve the `build` before testing? I see ncu as an external addon which should not influence the module, therefore it would be a bit ugly to add a `build-then-test` script to `package.json`. Maybe it could look like `--doctor-scripts build,do-things,other-things,test`?

I was thinking `--doctor-x` could solve this by allowing you to specify any shell command, not just an npm script. Would that work?

```
ncu -u --doctor --doctor-x "npm run build && npm run ci"
```

> For the install hook: What scenario comes to your mind? I immediately thought about some `clean` script, but you could add this to the `--doctor-scripts` as the first parameter?

I'm just unsure how you're using `npm ci`. It just installs dependencies, not run tests, as far as I know, but you mentioned that you are using it to spin up a server and run integration tests?

Doctor mainly needs to know when and what to run for the install and test steps.

**Comment by einfallstoll** [comment]
> > How to solve the `build` before testing? I see ncu as an external addon which should not influence the module, therefore it would be a bit ugly to add a `build-then-test` script to `package.json`. Maybe it could look like `--doctor-scripts build,do-things,other-things,test`?
> 
> I was thinking `--doctor-x` could solve this by allowing you to specify any shell command, not just an npm script. Would that work?
> 
> ```
> ncu -u --doctor --doctor-x "npm run build && npm run ci"
> ```

I think this is the most versatile way to accomplish this. However, _if I was you_ I'd stick to the scripts section instead of dealing with child processes and shell commands. Either way: Both ways give some additional flexibility.

> > For the install hook: What scenario comes to your mind? I immediately thought about some `clean` script, but you could add this to the `--doctor-scripts` as the first parameter?
> 
> I'm just unsure how you're using `npm ci`. It just installs dependencies, not run tests, as far as I know, but you mentioned that you are using it to spin up a server and run integration tests?
> 
> Doctor mainly needs to know when and what to run for the install and test steps.

The `ci` script in my specific case spins up an instance of the app, waits for it to become available and then calls the `test` script. I need to run end-to-end tests, so it's crucial to have an up and running instance in a real browser but I see overwriting the plain `install` step might cover some edge cases as well (e.g. install-level arguments).

**Comment by einfallstoll** [comment]
How about `--doctor-install` which defaults to `[package manager] install` and `--doctor-test` which defaults to `[package manager] test`?

**Comment by raineorshine** [comment]
> I think this is the most versatile way to accomplish this. However, _if I was you_ I'd stick to the scripts section instead of dealing with child processes and shell commands. Either way: Both ways give some additional flexibility.

Cool. I'm okay with spawning a shell; it's done a few times in the codebase already.

> How about `--doctor-install` which defaults to `[package manager] install` and `--doctor-test` which defaults to `[package manager] test`?

I like this! Perfect.

I have a deadline for another project right now so I can't work on it at the moment, but I'll put it on my list.

**Comment by raineorshine** [comment]
@einfallstoll @pdemarino I made an initial implementation. Can you try `npm install -g npm-check-updates@next` and run with `--doctorTest "CUSTOM COMMAND"`, and let me know if it works?

**Comment by raineorshine** [comment]
Added and published in `v12.1.0`
