### ISSUE TITLE
Doctor seems to just give up after first steps

### ISSUE THREAD

**Issue by Pezmc** [raineorshine/npm-check-updates#782]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`

```bash
$ ncu --version
10.2.5
```

- [x] I am using `node >= 10.17`

```bash
node --version
v14.15.4
```

---------------------------

## Steps to Reproduce

I'm not entirely sure, I appreciate that's not very helpful, are there any log files I can check that might shed some light?

I'm running `ncu --target patch --doctor -u -p yarn` on a large package.json file which includes a babel/core upgrade that causes test failures.

## Current Behavior

```bash
ncu --target patch --doctor -u -p yarn
yarn install
yarn run test
ncu --target patch -u -p yarn
yarn install
yarn run test
Failing tests found:
✖ ｢wdm｣:

...TESTS FAIL HERE...

error Command failed with exit code 1.

Now let's identify the culprit, shall we?
Restoring package.json
Restoring lock file
yarn install
yarn add @babel/core@^7.11.6
yarn run test
  ✗ @babel/core ^7.11.5 → ^7.11.6
```

## Expected Behavior

The script continues to run and saves a partially updated `package.json`, rather than stopping on the first test failure.

**Comment by raineorshine** [comment]
Doctor is currently designed to stop on the first failure, but perhaps that should not be the default behavior. It does however upgrade any packages that were successfully installed and passed the tests up until that point, so you can easily resume.

If don't wish to fix the broken dependency immediately, I recommend adding it to the `--reject` and resuming Doctor.

I would be open to a cli option `--doctor-bail` to control whether it stops on the first failure or not.

**Comment by Pezmc** [comment]
Aah, that's my misunderstanding then, I thought it would update packages one by one running the tests inbetween, and if there was an error, skip to the next one, then report the ones that caused test failures! I'll use `--reject` manually for now, but do agree that an option for it to continue and skip updating that particular dependency would be of value!

**Comment by raineorshine** [comment]
Actually, I think the expected behavior was implemented back in November (I don't know what I was thinking when I responded before):

083a1108178b954834f9c819ec555793a39ec1cc

Is the problem still happening for you? It's working well for me. If I could get the `dependencies` section of your `package.json` to reproduce I could troubleshoot it.

**Comment by Pezmc** [comment]
Hi again @raineorshine, on `11.5.9`, it seems slightly better, but still isn't working great:

```bash
ncu --version
11.5.9
❰pezcuckow❙~/gitrepo(git:master)❱✔≻ ncu --target patch --doctor -u -p yarn
Running tests before upgrading
Upgrading all dependencies and re-running tests
ncu --target patch -u -p yarn
Tests failed
Identifying broken dependencies
yarn add @rails/ujs@^6.1.3
✓ @rails/ujs ^6.1.1 → ^6.1.3
yarn add esbuild@0.11.18
...tests fail here...
✗ esbuild 0.11.6 → 0.11.18
...tests fail here...
yarn add handlebars@^4.7.7
✗ handlebars ^4.7.6 → ^4.7.7
...tests fail here...
yarn add react@^17.0.2
✗ react ^17.0.1 → ^17.0.2
...tests fail here...
yarn add react-dom@^17.0.2
✗ react-dom ^17.0.1 → ^17.0.2
...tests fail here...
yarn add sass@1.32.12
yarn run test
✗ sass 1.32.8 → 1.32.12
...tests fail here...

error Command failed with exit code 1.
Saving partially upgraded package.json
```

It looks like it's not rolling back changes that cause test failures, and just trying to run all upgrades that follow the first failure. 
In the above example the esbuild upgrade breaks the tests, so none of the other upgrades happen.

Manually running `yarn add handlebars@^4.7.7 && yarn test`, passes, for example.

Full dependencies list in case that's useful, but I think the above might be the core of the problem?

```json
"devDependencies": {
    "eslint": "^7.24.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-import-resolver-node": "^0.3.4",
    "eslint-plugin-ban": "^1.5.2",
    "eslint-plugin-eslint-comments": "^3.2.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-no-jquery": "^2.6.0",
    "eslint-plugin-react": "^7.23.2",
    "eslint-plugin-react-hooks": "^4.2.0",
    "husky": "^6.0.0",
    "jasmine-core": "^3.7.1",
    "karma": "6.3.2",
    "karma-chrome-launcher": "^3.1.0",
    "karma-esbuild": "2.1.3",
    "karma-firefox-launcher": "^2.1.0",
    "karma-jasmine": "^4.0.1",
    "lint-staged": ">=10",
    "prettier": "^2.2.1"
  },
  "dependencies": {
    "@bugsnag/js": "^7.5.6",
    "@harvesthq/porchlight": "0.61.1",
    "@rails/ujs": "^6.1.3",
    "@svgr/core": "5.5.0",
    "autosize": "4.0.2",
    "backbone": "1.2.3",
    "big.js": "2.2.0",
    "bootstrap": "^4.5.3",
    "chart.js": "2.9.4",
    "chosen-js": "1.8.7",
    "classnames": "2.2.6",
    "d3": "3.5.17",
    "d3-array": "1.2.4",
    "d3-scale": "2.2.2",
    "d3-shape": "1.3.7",
    "daterangepicker": "2.1.27",
    "esbuild": "0.11.6",
    "escape-string-regexp": "1.0.5",
    "glob": "7.1.6",
    "handlebars": "^4.7.7",
    "highlight.js": "10.5.0",
    "jquery": "1.12.4",
    "jquery-ujs": "1.2.2",
    "kalendae": "0.6.1",
    "moment": "^2.21.0",
    "ms": "2.1.3",
    "popper.js": "^1.15.0",
    "puppeteer": "^5.5.0",
    "react": "^17.0.1",
    "react-addons-css-transition-group": "15.6.2",
    "react-dom": "^17.0.1",
    "sass": "1.32.8",
    "tablesorter": "2.31.3",
    "underscore": "1.8.3",
    "uuid": "3.4.0"
  },```

**Comment by raineorshine** [comment]
Thanks for the additional info! I'm guessing that there is a difference with `yarn` that I didn't account for. All of my testing was done with `npm`. It uses `--no-save` to install individual upgrades without affecting the lockfile and allow for a clean rollback. 

I will add `yarn` to the doctor tests to confirm.

**Comment by raineorshine** [comment]
I was able to reproduce the issue and write a test. Will you try ncu `v11.5.10`?

**Comment by Pezmc** [comment]
Yes, using the ncu from `main` @ v11.5.10 seems to be working well, thank you!
