### ISSUE TITLE
Deprecated packages used by npm-check-update

### ISSUE THREAD

**Issue by crystalfp** [raineorshine/npm-check-updates#783]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
Moved to node version 15.5.1 on Linux.
`ncu -u` Said an update is available for `npm-check-updates` from 7.0.1 to 10.2.5 so I upgraded:
`npm i -g npm-check-updates` This shows two deprecations warnings (see below). These warnings were present also in old versions of ncu.

## Current Behavior
The above upgrade command shows two deprecation warnings:
```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 294 packages, and audited 295 packages in 10s

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
## Expected Behavior
It is not a blocking bug, but I expect no warning after a major version upgrade.
Thanks for looking!
mario

**Comment by raineorshine** [comment]
Hi! The outdated dependency belongs to `node-gyp` and can be tracked in https://github.com/nodejs/node-gyp/issues/2047. Considering the widespread use of `node-gyp` across the node ecosystem, I imagine this is affecting many projects.

Here's the relevant dependency tree in `npm-check-updates`:

```
$ npm ls request
npm-check-updates@10.2.5 /Users/raine/projects/npm-check-updates
└─┬ pacote@11.1.13
  └─┬ @npmcli/run-script@1.7.5
    └─┬ node-gyp@7.1.2
      └── request@2.88.2
```

`har-validator` is a dependency of `request`

I'm going to mark this a dependency bug and close. Thanks!

**Comment by crystalfp** [comment]
OK, raised again the issue in [nodejs/node-gyp/2047](https://github.com/nodejs/node-gyp/issues/2047)
