### ISSUE TITLE
Should there be option to remove node_modules dir if `-u` changes `package.json`

### ISSUE THREAD

**Issue by mkungla** [raineorshine/npm-check-updates#786]
When `-u` flag is used then would it be handy to remove existing `node_modules` dir and perhaps `package-lock.json` if `package.json` is updated to ensure that `npm install` is executed.

That would be specially handy in mono repos (ref #522, # 785)

**Comment by raineorshine** [comment]
Thanks for the suggestion. That's not a bad idea. However `npm-check-updates` has a simple design policy that *only* your package.json is updated. There has been zero confusion about this, while there used to be confusion when it interacted with `node_modules`. I think keeping `npm-check-updates` dead simple to reason about in this way is important.
