### ISSUE TITLE
Document --target options (with a documentation proposal included)

### ISSUE THREAD

**Issue by garybernhardt** [raineorshine/npm-check-updates#787]
- [X] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [X] I am using the latest version of `npm-check-updates`
- [X] I am using `node >= 10.17`

---------------------------

First, thanks for making this tool, @raineorshine. It fills a huge hole in the npm ecosystem and we use it regularly to update all of our dependencies.

(I'm not bothering to include Node version etc. here because this is a documentation issue.)

## Steps to Reproduce

Run `npm-check-updates --help`.

## Current Behavior

The `--target` option is documented as:

>   -t, --target <value>         Target version to upgrade to: latest, newest, greatest, minor, patch. (default: "latest")

I didn't know what these options meant and I couldn't find any further documentation for them. "latest" vs. "newest" vs. "greatest" were especially opaque to me.

## Expected Behavior

Ideally, `--help` would explain what all of the target options do. Or, if that would take up too much space, it could point the user towards a separate help option like `--help-targets`. Or, as a last resort, a URL that explains what the targets do.

## Proposed Solution

I've read some of the source code, the changelog, and the issues here, as well as some issues and SO answers for npm and np. From all of that, I've cobbled together the following understanding:

* "newest" means most recently released in terms of release date, even if there are other version numbers that are higher. It includes prereleases.
* "greatest" means highest version number, regardless of release date. It includes prereleases.
* "latest" is whatever the project's "latest" git tag points to. It's usually the non-prerelease version with the highest version number, but is ultimately decided by each project's maintainers.
* "minor" means highest minor version without incrementing the current major.
* "patch" means highest patch version without incrementing the current major or minor.

Is that correct? If so, I'm happy to try to wrangle that into the CLI's usage in a PR. Or, if it would be easier for you, I'm also happy for you to adapt my description into whatever form you think would be best.

**Comment by raineorshine** [comment]
Great catch! It seems the help documentation for the individual options disappeared when they were consolidated into `--target`.

> I've read some of the source code, the changelog, and the issues here, as well as some issues and SO answers for npm and np. From all of that, I've cobbled together the following understanding:
> 
> * "newest" means most recently released in terms of release date, even if there are other version numbers that are higher. It includes prereleases.
> * "greatest" means highest version number, regardless of release date. It includes prereleases.
> * "latest" is whatever the project's "latest" git tag points to. It's usually the non-prerelease version with the highest version number, but is ultimately decided by each project's maintainers.
> * "minor" means highest minor version without incrementing the current major.
> * "patch" means highest patch version without incrementing the current major or minor.

That's exactly right. Sorry you had to dig for it :).

> Ideally, `--help` would explain what all of the target options do. Or, if that would take up too much space, it could point the user towards a separate help option like `--help-targets`. Or, as a last resort, a URL that explains what the targets do.

I like this idea. I was thinking it would be nice to have a general solution for any option that has additional help documentation, like `ncu --target --help`. Commander has support for subcommand-specific help but not option-specific help from what I can tell. However we could simply check the arguments manually and print a custom help for these specific cases. Extended help can be stored in a `help` field in [cli-options](https://github.com/raineorshine/npm-check-updates/blob/master/lib/cli-options.js). Thoughts?

**Comment by garybernhardt** [comment]
Agreed that a general solution for extended help is a good idea. `--target --help` seems like it would be a great solution, but my worry there is that I probably wouldn't think to try it, only because I haven't seen it before. (But now that you've mentioned it, I do kind of wish that complex tools without subcommands used this convention.)

My vote would be to either:

1. Add these details to the main usage and accept that it'll be longer. It's already 77 lines long, so I think people are more likely to search it than to read the whole thing carefully. Once people are searching, more text isn't a huge problem. This is also the simplest to implement/maintain. No extra options or logic required; just more usage text. Or,
2. Add a `--help-target`, and maybe other similar `--help-somefeature` options as needed. As long as the main usage for `--target` says something like "see --help-target for details on targets", users can still search the usage for "target" and find a path to the answer.

With that said, I think the main thing is that it's written down somewhere discoverable, and the exact details of where are less important. When I didn't find my answer in the usage, my next stop was the README, so even a note in the README would've answered my question in just a few seconds.

**Comment by raineorshine** [comment]
> Agreed that a general solution for extended help is a good idea. `--target --help` seems like it would be a great solution, but my worry there is that I probably wouldn't think to try it, only because I haven't seen it before. (But now that you've mentioned it, I do kind of wish that complex tools without subcommands used this convention.)

Yup. I have in mind an explicit message, not relying on the user to guess at a non-standard feature.

> 1. Add these details to the main usage and accept that it'll be longer. It's already 77 lines long, so I think people are more likely to search it than to read the whole thing carefully. Once people are searching, more text isn't a huge problem. This is also the simplest to implement/maintain. No extra options or logic required; just more usage text. Or,

For me, that's not the place for detailed, command-specific help. 77 lines fit on a single screen and is scannable. The challenge as I see it is in attempting to make the help both 1) human-readable, and 2) definitive. We're right about at that point of departure, where adding more content keeps them definitive but renders that harder to read/scan for basic usage. Splitting off the help into command-specific help seems like a good solution to maintain both readability and definitiveness, with an appropriate hint of where to find more information. 

I've struggled through enough `man` pages so this one's personal 😂

> 2\. Add a `--help-target`, and maybe other similar `--help-somefeature` options as needed. As long as the main usage for `--target` says something like "see --help-target for details on targets", users can still search the usage for "target" and find a path to the answer.

We can do exactly this, just with `--help --target` (or `--target --help`; both should work).

> With that said, I think the main thing is that it's written down somewhere discoverable, and the exact details of where are less important. When I didn't find my answer in the usage, my next stop was the README, so even a note in the README would've answered my question in just a few seconds.

Since the `README` contains the full output of the `--help` command, as long as we have `see "--help --target" for details` in there then it'll be in two places where people can find it.

Thanks for the discussion!

**Comment by garybernhardt** [comment]
This all sounds good to me!

**Comment by raineorshine** [comment]
Published in `v10.3.0`

**Comment by garybernhardt** [comment]
I upgraded to take a look. This is great; I think it will help a lot of people. Thanks!

**Comment by raineorshine** [comment]
Great for the `--target` option and great to have a structure in place for other options. Thanks for the thoughtful suggestion!
