### ISSUE TITLE
[Feature Request]: [Documented] way to force color in output

### ISSUE THREAD

**Issue by cinderblock** [raineorshine/npm-check-updates#804]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

If I run `npx npm-check-updates` in a non-interactive/color disabled terminal, such as GitHub Actions, no colors are produced, as expected.

But I want to force outputting of color codes.

`npm` has https://docs.npmjs.com/cli/v6/using-npm/config#color

Could a `--color` option be added to `npm-check-updates`?

Maybe it would make sense to load and respect Npm's color config in case an `.npmrc` file exists?

**Comment by raineorshine** [comment]
Thanks for the suggestion, I hadn't run into this before. Does `FORCE_COLOR=1 npm-check-updates` work?

https://github.com/chalk/chalk#chalksupportscolor

**Comment by cinderblock** [comment]
Yes, `FORCE_COLOR=1` env works.

I would still request a cli arg to control this behavior as setting env on Windows is... troublesome.

**Comment by raineorshine** [comment]
Added `--color` in `v11.1.0`.
