### ISSUE TITLE
Include npx usage in documentation

### ISSUE THREAD

**Issue by MkMan** [raineorshine/npm-check-updates#807]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

Installing packages globally can be annoying and often unnecessary for utility packages. `npx` can be used to run this package when needed instead of installing it globally

**Comment by raineorshine** [comment]
That's fair, but I'll leave that up to users. For users who know about `npx`, they'll know that they can use it with `npm-check-updates`.
