### ISSUE TITLE
Problems connecting to Verdaccio 

### ISSUE THREAD

**Issue by DaveCole** [raineorshine/npm-check-updates#809]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------
After updating to most recent version of npm-check-updates from v4.0.1, running ncu fails when attempting to interrogate our local verdaccio repo.

## Steps to Reproduce
1. Set up a local verdaccio repo, add yourself as a user, and add at least one package from it to your package.json
2. Install ncu 4.0.1 - run it and see that everything works fine.
3. Update to latest version of ncu and you'll get the error message below:

## Current Behavior

Checking {redacted...}package.json
[==================--] 46/51 90%/usr/local/lib/node_modules/npm-check-updates/lib/index.js:375
  throw err
  ^
FetchError: request to https://verdacciodev.{...redacted..}.com/@my-verdaccio-repo%2fmy-special-local-package failed, reason: connect ENETUNREACH {IP redacted}:443
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm-check-updates/node_modules/minipass-fetch/lib/index.js:97:14)
    at ClientRequest.emit (events.js:210:5)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:215:7)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ENETUNREACH',
  errno: 'ENETUNREACH',
  syscall: 'connect',
  address: '{IP redacted}',
  port: 443,
  type: 'system'
}

## Expected Behavior

When using 4.0.1 everything runs fine and available package updates are shown.

**Comment by raineorshine** [comment]
Thanks for reporting. I followed your steps with a new Verdaccio registry and a new repo and it worked fine for me. `ENETUNREACH` is an early network error, usually when not connected to the internet. The error is most likely originating from `pacote` (which uses `minipass-fetch`). I've seen a variety of errors related to `pacote` not (or mis-)reading one's npm config.

Does this command work for you? That will tell us if the problem is in `pacote`:

`npx pacote packument YOUR_REPO`

**Comment by DaveCole** [comment]
Thank you for going the length for me!

Turns out it was a network configuration issue on our end; closing the issue.  Thanks again!
