### ISSUE TITLE
Running ncu through scripts showing "No dependencies."

### ISSUE THREAD

**Issue by Primajin** [raineorshine/npm-check-updates#811]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

```
npm-check-updates --version 11.1.1
npm --version 6.14.10
node --version v14.15.4
WINDOWS 🙈 
```

have a `package.json` like

```json
  "dependencies": {
    "@material-ui/core": "^4.11.2"
  },
  "scripts": {
    "check-updates": "ncu --filterVersion '/^[~^]/' -t minor"
  }
```

and have npm-check-updates installed globally

## Current Behavior
Using `ncu`, `npm-check-updates` or `npx` with any of the before in scripts yields "No dependencies."

## Expected Behavior

Using `ncu`, `npm-check-updates` or `npx` with any of the before in scripts yields

```
@material-ui/core                         ^4.11.2  →                 ^4.11.3
```

the same way as if I entered the command directly into the shell.

![Screenshot 2021-01-29 114023](https://user-images.githubusercontent.com/1742115/106266422-b0d69980-6228-11eb-9236-b23303959678.png)

**Comment by raineorshine** [comment]
This is related to the Windows shell. Try the regex with double quotes:

```
  "scripts": {
    "check-updates": "ncu --filterVersion \"/^[~^]/\" -t minor"
  }
```

**Comment by Primajin** [comment]
perfect that works! thanks.

Curious to know why it won't work with
```
  "scripts": {
    "check-updates": "ncu --filterVersion \"/^[~^]/\" -t minor"
  }
```

though 🤔 That way my colleagues wouldn't need to have it installed on  their machines...

**Comment by raineorshine** [comment]
> perfect that works! thanks.

Great

> Curious to know why it won't work with
> 
> ```
>   "scripts": {
>     "check-updates": "npx npm-check-updates --filterVersion \"/^[~^]/\" -t minor"
>   }
> ```
> 
> though 🤔 That way my colleagues wouldn't need to have it installed on their machines...

Not a bad idea. I'm not sure how `npx` interact with npm scripts. I suggest testing a simple `npx`, then `npx npm-check-updates` with no arguments.
