### ISSUE TITLE
ncu -g upgrades major version

### ISSUE THREAD

**Issue by zhangchenglin** [raineorshine/npm-check-updates#819]
- [ ] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [ ] I am using the latest version of `npm-check-updates=11.1.1`
- [ ] I am using `node >= 12.20.1`

---------------------------

## Steps to Reproduce
ncu -g`

## Current Behavior
`
ncu -g
[====================] 8/8 100%

 npm  6.14.11  →  7.5.2

ncu itself cannot upgrade global packages. Run the following to upgrade all global packages:

npm -g install npm@7.5.2

## Expected Behavior

ncu -g
[====================] 8/8 100%

 npm  6.14.11  →  `6.*.*`

ncu itself cannot upgrade global packages. Run the following to upgrade all global packages:

npm -g install npm@`6.*.*`

**Comment by raineorshine** [comment]
> npm-check-updates upgrades your package.json dependencies to the latest versions, ignoring specified versions.

The main point of `npm-check-updates` is to upgrade *beyond* major versions. If you would like to limit to minor and patch updates only, you can add `--target minor`.

**Comment by zhangchenglin** [comment]
> > npm-check-updates upgrades your package.json dependencies to the latest versions, ignoring specified versions.
> 
> The main point of `npm-check-updates` is to upgrade *beyond* major versions. ~If you would like to limit to minor and patch updates only, you can add `--target minor`.~ Global version-constrained updates are not currently supported.


I did this before, and I won’t be prompted to upgrade to 7.*.*

**Comment by raineorshine** [comment]
I don't believe `npm-check-updates` has ever limited the major version by default. If you have a specific version number I could comment on it.

I think the behavior you are looking for should ideally be provided by `--target minor`, but this needs to be made in a PR.

**Comment by tw0517tw** [comment]
https://github.blog/2021-02-02-npm-7-is-now-generally-available/
I guess that's because `npm` marked version 7 as `latest` only days ago. Since then `npm-check-updates` started to prompt upgrading `npm`.

**Comment by zhangchenglin** [comment]
One is the solution and the other is the cause. well
