### ISSUE TITLE
Optional global cache support for bulk upgrades (--cache=/path/to/my-cache.json)

### ISSUE THREAD

**Issue by art-ws** [raineorshine/npm-check-updates#825]
- [ x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x ] I am using the latest version of `npm-check-updates`
- [x ] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
* Create workspace with many different similar projects with a lot of identical dependencies ([rush](https://rushjs.io/) guarantee that all versions are the same)
* Run `ncu -u` for each project in workspace in a cycle (via script for bulk upgrade).

## Current Behavior
Tool works perfect but again and again performs the same networks requests to resolve the latest package versions for different projects with a lot of identical dependencies.
**Problem**: Overall time is too long and many network timeouts happens if run commands in parallel. 

## Expected Behavior
Whould be nice to specify via command line argument the path to a kind of global cache json file, where `ncu` can persist the latest version resolution result between different calls. As result such improvement _significally decrease the network usage and speedup the bulk upgrades_.

**Comment by art-ws** [comment]
BTW: If you have a lack of time and don't mind for this feature, then we can implement it and create a pull request.

**Comment by raineorshine** [comment]
Hi! Would specifying a glob for `--packageFile` meet your requirements? When multiple package files match, identical dependencies are cached within the run. e.g. `ncu --packageFile '**/package.json'` (aliased to `ncu --deep`) runs `ncu` on all package files under the current working directory.

**Comment by art-ws** [comment]
Hi! Workspace contains a lot of temporary packages managed by `rush`, so `ncu` tring to upgrade them by default also, which is not an option.

Helped `ncu --packageFile "$(pwd)/*/!(temp|deploy)/**/package.json`

Thank you for assistance!!
