### ISSUE TITLE
`ncu --deep` ignore .ncurc.yml settings

### ISSUE THREAD

**Issue by art-ws** [raineorshine/npm-check-updates#826]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Abstract

Follow up on [closed issue](https://github.com/raineorshine/npm-check-updates/issues/825)

## Steps to Reproduce
* Create [or clone](https://github.com/art-ws/temp) workspace with nested packages 
* Define `.ncurc.yml` for some projects
* Run `ncu -u --deep` for root

## Current Behavior
Tool update all package versions and ignore `.ncurc.yml` settings.

## Expected Behavior
Would be nice if tool can recognize existing `.ncurc.yml` settings file and follow it rules.

**Comment by raineorshine** [comment]
Yes, good catch!

**Comment by art-ws** [comment]
Fixed in v11.4.1
