### ISSUE TITLE
"@popperjs/core": "^2.6.0" not updating

### ISSUE THREAD

**Issue by brettz9** [raineorshine/npm-check-updates#829]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

1. Add this dependency:

```json
"@popperjs/core": "^2.6.0",
```
2. Run `ncu -u`
 
## Current Behavior

Says "All dependencies match the latest package versions" or, if there are no other dependencies, it will say "No dependencies." .

## Expected Behavior

Will update to 2.8.2, the latest version

**Comment by brettz9** [comment]
Sorry, forgot I had blocked this!

**Comment by raineorshine** [comment]
I’ve done the same thing! 😊
