### ISSUE TITLE
globalThis reference error in dependency on Node 11

### ISSUE THREAD

**Issue by cinderblock** [raineorshine/npm-check-updates#834]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
1. Install latest Node 11 _(`11.15.0`)_
2. Run `npx npm-check-updates`

## Current Behavior
Error reference to `globalThis`:
```txt
  ? queueMicrotask.bind(globalThis)
                        ^

ReferenceError: globalThis is not defined
    at Object.<anonymous> (C:\Users\camer\Desktop\ncu temp\node_modules\queue-microtask\index.js:5:25)
    ...
```

## Expected Behavior
No error on supported versions (>= 10.7)

### Other Node versions

This does not happen if Node 10 is installed or if Node 12 is installed.

### CI logs

This change happened between:
- 2021-02-08 9:17PM PST - Last working CI build
- 2021-02-09 9:17PM PST - First CI error

### `globalThis` added to Node in ~`12.4`

https://node.green/#ES2020-features-globalThis

**Comment by raineorshine** [comment]
Unfortunately, this appears to be an issue with `npm`, not `npm-check-updates`. `queue-microtask` (where `globalThis` is accessed) is not a dependency of `npm-check-updates` nor any of its dependencies. I recommend opening an issue with [npm](https://github.com/npm/cli/issues/).

However I can give you some information that might help.

Here's the dependency tree of `queue-microtask` when installing on node `v11.15.0`:

```sh
npm-check-updates@11.1.9 /Users/raine/.nvm/versions/node/v11.15.0/lib/node_modules/npm-check-updates
└─┬ globby@11.0.2
  └─┬ fast-glob@3.2.5
    └─┬ @nodelib/fs.walk@1.2.6
      └─┬ @nodelib/fs.scandir@2.1.4
        └─┬ run-parallel@1.2.0
          └── queue-microtask@1.2.2
```

Here's the closest dependency tree when installing on node `v14`. Notice `queue-microtask` is no longer installed:

```sh
npm-check-updates@11.1.9 /Users/raine/projects/npm-check-updates
└─┬ globby@11.0.2
  └─┬ fast-glob@3.2.5
    └─┬ @nodelib/fs.walk@1.2.6
      └─┬ @nodelib/fs.scandir@2.1.4
        └── run-parallel@1.1.10
```

Why does `@nodelib/fs.scandir@2.1.4` install run-parallel `1.2.0` on node `v11.15.0`, but `1.1.10` on node `v14`?

**Comment by XhmikosR** [comment]
@raineorshine I'd close this issue since non-LTS releases shouldn't be used in production as per the Node.js support matrix.
