### ISSUE TITLE
Regexp rejects are not working from configuration file

### ISSUE THREAD

**Issue by Litee** [raineorshine/npm-check-updates#847]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

Using ncu v11.1.10, node v15.3.0

* Create a new npm project
* Run `npm i @aws-cdk/aws-cloudwatch@1.45.0` (not the latest version)
* Create `.ncurc.json` file with this content:
```json
{
    "upgrade": true,
    "reject": [
      "/@aws-cdk/.*/"
    ]
  }
```
* Run `npx ncu`

## Current Behavior

Package `@aws-cdk/aws-cloudwatch` is not ignored, upgrade is recommended.

## Expected Behavior

Package should be ignored. Note that regexp works when specified via --reject parameter in command-line.

P.S. Nice tool, by the way, I use it regularly. Thank you!

**Comment by raineorshine** [comment]
Thanks for the detailed report! Can you share the result of `npx ncu --loglevel verbose`? I wonder if your config file is not being read in, because it works as expected for me.

**Comment by Litee** [comment]
Here it is. Note that I had to enable verbose logging in the config file itself - if I used command line parameter as you recommended then ncu was saying that it sees no upgrades, which is also weird.

```
$ npx ncu
Using config file C:\Users\Andrey\Documents\Projects\Experiments\npm-check-updates-playground\.ncurc.json
Initializing
Running in local mode
Finding package file data
Checking C:\Users\Andrey\Documents\Projects\Experiments\npm-check-updates-playground\package.json
Fetching latest versions

Options:
{
  args: [],
  bundle: true,
  cli: true,
  concurrency: 8,
  deep: false,
  dev: true,
  errorLevel: 1,
  format: [],
  json: false,
  loglevel: 'verbose',
  minimal: false,
  optional: true,
  packageManager: 'npm',
  peer: true,
  prefix: null,
  prod: true,
  rcConfigPath: 'C:\\Users\\Andrey\\Documents\\Projects\\Experiments\\npm-check-updates-playground\\.ncurc.json',
  reject: [ '/@aws-cdk/.*/', 'change-case' ],
  target: 'latest',
  version: '11.1.10'
}

Fetched:
{
  '@aws-cdk/aws-cloudwatch': '1.92.0',
  eslint: '7.21.0',
  'npm-check-updates': '11.2.0'
}

Upgraded:
{
  '@aws-cdk/aws-cloudwatch': '^1.92.0',
  eslint: '~7.21.0',
  'npm-check-updates': '^11.2.0'
}

 @aws-cdk/aws-cloudwatch   ^1.45.0  →  ^1.92.0
 eslint                     ~6.8.0  →  ~7.21.0
 npm-check-updates        ^11.1.10  →  ^11.2.0

Run ncu -u to upgrade package.json
```

**Comment by raineorshine** [comment]
Okay, I think I figured it out! `npm-check-updates` supported arrays of strings, but not arrays of regexes, or heterogeneous arrays of regexes and strings.

Will you try out `v11.2.1`? I added support for arrays of any of the supported top level filter types.

**Comment by Litee** [comment]
It works now. Thanks.
