### ISSUE TITLE
Use .ncurc only with ncu -u

### ISSUE THREAD

**Issue by sysmat** [raineorshine/npm-check-updates#848]
- [x ] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x ] I am using the latest version of `npm-check-updates`
- [x ] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
Is it possible to check for update packages but ignore when update?

## Current Behavior
- .ncurc.yml:
```yaml
reject:
  - typescript
  - angular2-multiselect-dropdown 
```

- with` ncu --configFilePath  ..` I cant achieve this, but is there any config options to achieve this without using a switch to not existing config

**Comment by raineorshine** [comment]
> Is it possible to check for update packages but ignore when update?

I'm not sure I understand. Are you asking if there is a way to ignore a package when running `ncu -u` but not ignore it when running `ncu`?

**Comment by sysmat** [comment]
yes, exactly

**Comment by raineorshine** [comment]
Okay, I see. `npm-check-updates` does not support this level of customizability. You can use `configFilePath` as described, or override `reject` on the command line when you run `ncu`:

```sh
ncu -u          # ignores packages rejected in ncurc
ncu --reject _  # overrides rejected packages so none are ignored
```

**Comment by raineorshine** [comment]
Closing, as this level of customizability between command line options and config file is unlikely to be added.
