### ISSUE TITLE
Doesn't detect deprecated package mkdirp-promise@5.0.1 in swarm-js@0.1.40

### ISSUE THREAD

**Issue by wzup** [raineorshine/npm-check-updates#853]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
Install `web3.js`:
```
$ npm i -P web3
npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated multicodec@0.5.7: stable api reached
```

## Current Behavior
Doesn't show the package is deprecated neither suggest other versions.

Look up who uses the package `mkdirp-promise@5.0.1`
```
$ npm ls mkdirp-promise@5.0.1
web3-app@0.0.1 /sbox/ts/app
└─┬ web3@1.3.4
  └─┬ web3-bzz@1.3.4
    └─┬ swarm-js@0.1.40
      └── mkdirp-promise@5.0.1
```

Call `ncu`
```
$ cd node_modules/swarm-js/

$ /node_modules/swarm-js$ ncu
(node:72983) ExperimentalWarning: queueMicrotask() is experimental.
(node:72983) ExperimentalWarning: The fs.promises API is experimental
Checking /app/node_modules/swarm-js/package.json
[====================] 16/16 100%

 bluebird            ^3.5.0  →    ^3.7.2     
 buffer              ^5.0.5  →    ^6.0.3     
 eth-lib            ^0.1.26  →   ^0.1.29     
 fs-extra            ^4.0.2  →    ^9.1.0     
 got                 ^7.1.0  →   ^11.8.2     
 mime-types         ^2.1.16  →   ^2.1.29     
 mock-fs             ^4.1.0  →   ^4.13.0     
 tar                 ^4.0.2  →    ^6.1.0     
 xhr-request         ^1.0.1  →    ^1.1.0     
 @babel/cli          ^7.0.0  →  ^7.13.10     
 @babel/core         ^7.0.0  →  ^7.13.10     
 @babel/preset-env   ^7.0.0  →  ^7.13.10     
 decompress          ^4.0.0  →    ^4.2.1     
 xml2js             ^0.4.19  →   ^0.4.23     

Run ncu -u to upgrade package.json
```

## Expected Behavior
Probably should display `mkdirp-promise@5.0.1` as deprecated.

**Comment by raineorshine** [comment]
I could see that being useful, though `ncu` takes a minimal approach and does not currently display warnings of any kind, so it would be somewhat of a design deviation. Thank you for the suggestion.

Some additional information:

`ncu` excludes deprecated versions by default. For consistency, `ncu` only ever returns the `latest` tag unless you specify a different `--target`. Since `mkdirp-promise@5.0.1` is published to the latest tag, this is the only valid version for `ncu` to suggest by default. (`--deprecated` can be added to include deprecated versions.)
