### ISSUE TITLE
The published version on npmjs.com should be managed

### ISSUE THREAD

**Issue by zhangchenglin** [raineorshine/npm-check-updates#855]
https://www.npmjs.com/package/npm-check-updates?activeTab=versions

https://docs.npmjs.com/deprecating-and-undeprecating-packages-or-package-versions

Because in the 7-day download information provided by npmjs.com, there are many active users who are using the older version.
Please maintain and manage the older npm-check-updates version according to the specific nodejs version.
So that you can clearly understand the specific version of npm-check-updates that should be used in some cases.
If the use of some older versions is wrong, please directly notify those people through the deprecation function of npm and let them know.
It is also conducive to the development of npm-check-updates.

![FireShot Capture 005 - npm-check-updates - npm - www npmjs com](https://user-images.githubusercontent.com/30773389/112767084-4e8eef00-9047-11eb-8b66-f42571499e2f.png)

**Comment by raineorshine** [comment]
I'm not sure I understand what you are requesting. What do you mean by "maintain and manage"? I don't see the point of deprecating each older version. Most people understand that there are no guarantees with outdated versions. It's recommended to just use the latest published version, which supports all node versions in LTS (currently `node` >= v10).

**Comment by zhangchenglin** [comment]
> I'm not sure I understand what you are requesting. Could you explain? What do you mean by "maintain and manage"? I don't see the point of deprecating each older version. Most people understand that there are no guarantees with outdated versions. It's recommended to just use the latest published version, which supports all node versions in LTS (currently `node` >= v10). But if an older version worked for you before, it will keep working, so you don't have to upgrade unless you want new features/patches.


Looking at the law of usage, in each major major version, the one with the most users is the last version in the major version.
For example, in the following version, most of the users are the most in its major version number.

```
10.3.1
9.2.4 
8.1.1 
7.1.1 
6.0.1 
5.0.0 
4.1.2 
3.2.2
2.1.5
```

---


Authors and maintainers should be the ones who know the difference between npm-check-updates version best. Those who stay in the last version of the old version, are they sure they know that there is a new version of npm-check-updates?
Why are more people staying in those versions? Are they voluntarily choosing?
In those older versions of npm-check-updates, will they prompt them that there is a newer version of npm-check-updates?

It's just to raise this matter, you can consider it for yourself and pay attention to it.

**Comment by raineorshine** [comment]
> Looking at the law of usage, in each major major version, the one with the most users is the last version in the major version.

That makes sense. They want the highest minor/patch version without risking changing the major version.

> Why are more people staying in those versions? Are they voluntarily choosing?

I guess I'm not seeing the value in knowing the answers to these questions. Sorry if I'm being dense!

> In those older versions of npm-check-updates, will they prompt them that there is a newer version of npm-check-updates?

[update-notifier](https://github.com/yeoman/update-notifier) has been used since v2.2.4 (b18f0823afd68c9c62fce2772d9737ced2e24a8d), so almost every user will see that there is a newer version available.

**Comment by zhangchenglin** [comment]
OK
