### ISSUE TITLE
error: ECONNRESET while trying to update: @typescript-eslint/parser

### ISSUE THREAD

**Issue by watjurk** [raineorshine/npm-check-updates#870]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

1. Create empty directory
2. Create package.json with following contents:
```json
{
  "devDependencies": {
    "@typescript-eslint/parser": "4.20.0"
  }
}
```
3. Try running `ncu`

## Current Behavior
In my enviromnet I'm getting an error:
```
Checking /test/package.json
[--------------------] 0/1 0%global/node_modules/npm-check-updates/lib/index.js:377
  throw err
  ^

FetchError: request to https://registry.npmjs.org/@typescript-eslint%2fparser failed, reason: socket hang up
    at ClientRequest.<anonymous> (global/node_modules/minipass-fetch/lib/index.js:97:14)
    at ClientRequest.emit (node:events:379:20)
    at TLSSocket.socketOnEnd (node:_http_client:486:9)
    at TLSSocket.emit (node:events:391:22)
    at endReadableNT (node:internal/streams/readable:1307:12)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  type: 'system'
}
```
This is very weird because when I'm going to `https://registry.npmjs.org/@typescript-eslint%2fparser` in browser everything works fine.

## Expected Behavior
No error

**Comment by raineorshine** [comment]
Thanks for reporting!

If you're getting an `ECONNRESET` error, it's almost surely a network issue and not a bug in `npm-check-updates`. I am curious though why you're able to open the manifest file from the registry in the browser but not via the command line.

Does `npx pacote packument @typescript-eslint/parser` work?

**Comment by watjurk** [comment]
Yes `npx pacote packument @typescript-eslint/parser ` works, but now I've tried `npm-check-updates. ` and it worked as well. This is very weird because I haven't change anything related to networking, sometimes good old restart works just file i guess.

Thank for help!

**Comment by raineorshine** [comment]
Must have been a temporary network issue. Thanks for closing!
