### ISSUE TITLE
TypeError: alias.match is not a function at Object.parseNpmAlias

### ISSUE THREAD

**Issue by VsevolodGolovanov** [raineorshine/npm-check-updates#879]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
Run `npx npm-check-updates`
My package.json and package-lock.json: [packagejson.zip](https://github.com/raineorshine/npm-check-updates/files/6400952/packagejson.zip)

## Current Behavior
Fails with an error. Full output:
```
>npx npm-check-updates
npx: installed 313 in 12.101s
Checking C:\work\argus\rep\TechService-3.22\workspace\server-app\inf-modules\system-inf-ui\src\main\resources\META-INF\resources\views\system\inf\page\showcase\react\package.json
[--------------------] 0/33 0%C:\Users\argus\AppData\Roaming\npm-cache\_npx\5684\node_modules\npm-check-updates\lib\index.js:416
  throw err
  ^

TypeError: alias.match is not a function
    at Object.parseNpmAlias (C:\Users\argus\AppData\Roaming\npm-cache\_npx\5684\node_modules\npm-check-updates\lib\version-util.js:264:32)
    at getPackageVersionProtected (C:\Users\argus\AppData\Roaming\npm-cache\_npx\5684\node_modules\npm-check-updates\lib\versionmanager.js:412:34)
    at C:\Users\argus\AppData\Roaming\npm-cache\_npx\5684\node_modules\npm-check-updates\node_modules\p-map\index.js:57:28
```

## Expected Behavior
Does its thing without errors.

I'm using latest Node.js LTS:
```
>npx --version
6.14.12
```

**Comment by raineorshine** [comment]
Thanks for reporting! Turns out it was crashing on the comment dependency. They're not officially supported but it was easy to fix.

Published in `v11.5.7`.

**Comment by VsevolodGolovanov** [comment]
Thanks.
It's ming-boggling to me that the single most important configuration file in the project is in the format that doesn't support proper comments.

**Comment by raineorshine** [comment]
Blame Douglas Crockford! 😅

> I removed comments from JSON because I saw people were using them to hold parsing directives, a practice which would have destroyed interoperability.
