### ISSUE TITLE
`ncu -g` incorrectly uses Yarn when inside a Yarn-based project directory

### ISSUE THREAD

**Issue by davidbailey00** [raineorshine/npm-check-updates#884]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

1. Install `ncu` with the command `npm install -g npm-check-updates`
2. `cd` into a directory containing a Yarn-based project
3. Run `ncu -g` inside that directory

## Current Behavior

Yarn is used to check for global updates, even though `ncu` was installed using NPM.

## Expected Behavior

`ncu -g` should not consider local projects to determine which package manager to check for *global* updates.

**Comment by raineorshine** [comment]
Thanks! Fixed and published in `v11.5.8`.

**Comment by davidbailey00** [comment]
Thank you!
