### ISSUE TITLE
Setting --global breaks --errorLevel

### ISSUE THREAD

**Issue by jryom** [raineorshine/npm-check-updates#891]
## Steps to Reproduce

Have outdated global dependencies, run `ncu --global --errorLevel 2`.

## Current Behavior

Passing `global` and `errorLevel 2` always returns exit code 0, even when there are outdated packages.

## Expected Behavior

`global` and `errorLevel` flags do not affect one another.

**Comment by raineorshine** [comment]
Thanks for reporting!

Fixed and published in `v11.5.11`.

**Comment by jryom** [comment]
Thanks for the quick fix!
