### ISSUE TITLE
dependency not updated when there is an up-to-date devDependency

### ISSUE THREAD

**Issue by mikestaub** [raineorshine/npm-check-updates#892]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

1. create a package.json with lodash@4.17.21 as a dependency and 4.17.4 as a devDependecy
2. run `ncu` see that lodash is not listed
3. run `npm outdated` and see lodash is listed

## Current Behavior

output does not match output of `npm outdated`

## Expected Behavior

output should match that of `npm outdated` command

**Comment by raineorshine** [comment]
Thanks for reporting! It looks like npm-check-updates does not handle the same dependency in `dependencies` as `devDependencies` very well.

FYI I was only able to reproduce this with `4.17.21` as a devDependency and `4.17.4` as a dependency, not the other way around.

**Comment by raineorshine** [comment]
Fixed and published in `v11.5.12`.
