### ISSUE TITLE
doesn't work with `npm exec --workspaces npx ncu`

### ISSUE THREAD

**Issue by mesqueeb** [raineorshine/npm-check-updates#896]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

`npm exec --workspaces npx ncu --target minor -u`

## Current Behavior

Here you can see:
- it does execute in all my NPM 7 workspace packages, but it doesn't seem to work.
- underneath the execution via the npm script, using lerna does work as expected.

<img width="761" alt="Screenshot 2021-05-26 at 10 28 23" src="https://user-images.githubusercontent.com/3253920/119589196-47991880-be0d-11eb-95f0-ac971905d64c.png">

## Expected Behavior

To work with NPM 7 `--workspaces` flag. I'd love to stop using lerna since there's 0 merit over just native NPM 7 workspaces.

Let me know if I can help with anything else for further clarification : )

**Comment by raineorshine** [comment]
Could you try:

``` 
npm exec --workspaces -- npx ncu --target minor -u
``` 

Based on npx vs npm exec arg parsing:
https://docs.npmjs.com/cli/v7/commands/npm-exec#npx-vs-npm-exec

If that doesn’t work, try installing `npm-check-updates` globally and removing npx from the equation for better isolation of the problem. 

``` 
npm install -g npm-check-updates
npm exec --workspaces -- ncu --target minor -u
``` 

If it is still an issue I can try to reproduce it on my side, but npm-check-updates shouldn’t require anything special for `--workspaces` to work if it works correctly on its own.

**Comment by mesqueeb** [comment]
@raineorshine thanks!
- `npm exec --workspaces -- npx ncu --target minor -u`
- `npm exec --workspaces -- ncu --target minor`

these two worked! I have `ncu` in the root devDependencies so went with the latter one!

**Comment by kai-dorschner-twinsity** [comment]
You could also use the `--deep` flag instead.

**Comment by leojh** [comment]
be on the lookout that `npx ncu` will run a weather app

**Comment by raineorshine** [comment]
Native workspace support added in prerelease `v16.2.0-0`. Open for feedback :). Your help is much appreciated in finding unidentified edge cases.

```
npx npm-check-updates@v16.2.0-0 --workspaces
```

## How it works

Upgrade all workspaces:

```
ncu --workspaces
ncu -ws
```

Upgrade a single workspace:

```
ncu --workspace a
ncu -w a
```

Upgrade more than one workspace:

```
ncu --workspace a --workspace b
ncu -w a -w b
```

Upgrade all workspaces AND the root project:

```
ncu --withWorkspaces
ncu -wws
```

Upgrade a single workspace AND the root project:

```
ncu --withWorkspace a
ncu -ww a
```

## Notes

- If run in `--interactive` mode, ncu will prompt to `npm install` once in the root project rather than separately in each workspace (#1182). 
- Running `--deep` will not trigger workspace support.

**Comment by mesqueeb** [comment]
@raineorshine thanks for this great feature!

I would love to give some feedback on the syntax.

I believe it's easier to understand the command later, instead of `--withWorkspaces`, to keep the `--workspaces` command, but adding an extra one for the root.

### current
```
ncu --withWorkspaces
```
### suggested
```
ncu --workspaces --withRoot
```
or
```
ncu --workspaces --root
```



It's just my personal opinion but I think reading this makes it easier to understand.

**Comment by raineorshine** [comment]
I do like how that looks. Thanks for the suggestion!

I was also thinking of utilizing an existing option:

```
ncu --workspaces --packageFile ./package.json
```

But I feel like this will be a common and deserves to have a shorter syntax.

**Comment by raineorshine** [comment]
Published to `latest` on `v16.3.0`. 

I changed `--withWorkspaces` to `--workspaces --root` (and `--withWorkspace` to `--workspace X --root`). Thanks for the suggestion!

**Comment by mesqueeb** [comment]
@raineorshine 

thanks for this update.

It seems like with this new command NCU gets confused about what packages local workspace packages are and which ones aren't:

![image](https://user-images.githubusercontent.com/3253920/192097166-6238c806-976d-4326-b381-89e13df00d0f.jpeg)

it seems to be looking for my workspace packages like `@cc/auth` etc, on NPM, while instead it should ignore those.

with `npm exec --workspaces -- ncu --target minor` I don't think I had this issue

should I open a new ticket for this?

**Comment by raineorshine** [comment]
Yes, please open a new ticket. Make sure to include:

1. Your dependencies list
2. The value of `workspaces` from your package.json
3. Why you believe `@cc/auth` should be ignored.
