### ISSUE TITLE
[FR] - show a changelog if possible

### ISSUE THREAD

**Issue by web2033** [raineorshine/npm-check-updates#898]
Hello!
Any quick ways to see a changelog before updating?

![2021-05-26_193811](https://user-images.githubusercontent.com/11320080/119698681-24e12100-be5a-11eb-95c9-d30f41916ab7.png)

**Comment by raineorshine** [comment]
Unfortunately there is no standard changelog format that would allow for consistent parsing.  You can use `--format repo` to at least get a link to each package's repository where you can look for a changelog.
