### ISSUE TITLE
Packages not upgraded with patch version

### ISSUE THREAD

**Issue by kranthikumar-kvs-by** [raineorshine/npm-check-updates#905]
Packages not upgraded when using the patch expression like this -
**npm-check-updates \"/^@by/catman-.*$/\" --target patch -u**

![image](https://user-images.githubusercontent.com/60686473/121215150-6384cb80-c89d-11eb-838e-3c5aa6f8e5eb.png)

The above packages have higher patch versions but it is not updating in package.json file.
I am using the latest version - 11.6.0

It was earlier working with version - 9.0.4

**Comment by raineorshine** [comment]
Hi, thanks for reporting. I'm not able to troubleshoot a private repo or registry, but I can confirm that the regexp and `--target patch` are working as expected on public repos:

```sh
raine[905]% cat package.json
{
  "dependencies": {
    "@sinonjs/fake-timers": "^7.0.0"
  }
}
raine[905]% ncu "/^@sinonjs/fake-.*$/" --target patch
Checking /Users/raine/projects/ncu-issues/905/package.json
[====================] 1/1 100%

 @sinonjs/fake-timers  ^7.0.0  →  ^7.0.5

Run ncu -u to upgrade package.json
```

**Comment by kranthikumar-kvs-by** [comment]
Please let me know if I can add a trace and share it with you, so you get more details.

**Comment by raineorshine** [comment]
Some questions may help narrow it down. 

- Do you have an active eslintrc?
- Do you get upgrades when omitting the regexp?
- Do you get upgrades when omitting `target`?
- What is the latest version of the relevant packages?
-
Are they private packages or on a private registry?

**Comment by kranthikumar-kvs-by** [comment]
Please find my comments below -

- Do you have an active eslintrc?
  Yes, we have eslintConfig in package.json file
    "eslintConfig": {
    "extends": "react-app",
    "rules": {
      "no-unused-vars": 0,
      "@typescript-eslint/no-unused-vars": 0
    }
  },
- Do you get upgrades when omitting the regexp?
  No, I don't get upgrades when omitting the regexp
- Do you get upgrades when omitting target?
  No, I don't get upgrades when omitting target
- What is the latest version of the relevant packages?
  
   ![image](https://user-images.githubusercontent.com/60686473/121344272-325dd700-c941-11eb-96c4-ddc8ef5cb4e0.png)

- Are they private packages or on a private registry?
  These are private packages in a private registry (JFrog)

Today I verified that even _npm-check-updates -u_ also not working.
node version - v14.17.0
npm version - v7.16.0
npm-check-updates version - v11.6.0

**Comment by raineorshine** [comment]
Thanks. Sounds like it is an authentication issue.

What do you get when you run this:

```sh
npx pacote packument @by/catman-react-grid
```

**Comment by kranthikumar-kvs-by** [comment]
![image](https://user-images.githubusercontent.com/60686473/121378108-862be880-c960-11eb-978e-8f6bbf7368f6.png)

**Comment by raineorshine** [comment]
Try adding a scoped registry to your `.npmrc`:

```
registry = http://myregistry/npm
@by:registry = http://myregistry/npm
```

**Comment by kranthikumar-kvs-by** [comment]
It is already present.

**Comment by raineorshine** [comment]
Well, I'm stumped 🤷‍♀️

**Comment by raineorshine** [comment]
Closing, but feel free to reopen if you have more info that would help me troubleshoot.
