### ISSUE TITLE
`--target minor` includes deprecated versions when using yarn

### ISSUE THREAD

**Issue by midgleyc** [raineorshine/npm-check-updates#906]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

From a new directory:
1. `npm init -y`
2. `npm install @progress/kendo-drawing`
4. `ncu -p yarn --target minor`

## Current Behavior
```
Using yarn
Checking /tmp/test-a/package.json
[====================] 1/1 100%

 @progress/kendo-drawing  ^1.10.1  →  ^1.13.7
```

## Expected Behavior
```
Using yarn
Checking /tmp/test-a/package.json
[====================] 1/1 100%

All dependencies match the latest package versions :)
```
This is the behaviour without targeting only minor versions, or without using yarn.

**Comment by raineorshine** [comment]
Thanks for reporting! yarn support in npm-check-updates is more experimental, and it looks like it is missing the deprecation check that exists in the npm code. Open to PR's.

**Comment by midgleyc** [comment]
I'll wait for the TypeScript support to come in (not too sure what's going on in that area); I can just force the `npm` package manager as a workaround (it's auto-yarning).

**Comment by raineorshine** [comment]
Sure!

Typescript support is pretty close to being done. It's just fairly low on my list of professional commitments given that I solo maintain this project for fun. Thanks for your patience 🙂.

**Comment by midgleyc** [comment]
Oh, sorry, by "not too sure what's going on in that area" I meant the package manager -- yarn section, not the TypeScript thing, and I thought it'd be easier to tell once the types were in. There's no need to rush.

**Comment by raineorshine** [comment]
@midgleyc FYI Typescript support is merged into main.

**Comment by midgleyc** [comment]
Sweet, thanks!

I've managed to write a test in `test/package-managers/yarn/index.ts`, which I think is the right area:
```
  it('avoids deprecated', async () => {
    const testDir = path.join(__dirname, 'default')
    const version = await yarn.minor('popper.js', '1.15.0', { cwd: testDir, pre: true })
    version!.should.equal('1.16.1-lts')
  })
```

I'll see about getting a fix in this weekend.
