### ISSUE TITLE
Error when running ncu right after clean install

### ISSUE THREAD

**Issue by AndrewBogdanovTSS** [raineorshine/npm-check-updates#910]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------
Platform: Windows 10
Node: 16.3.0

## Steps to Reproduce
npm install -g npm-check-updates (@next give same error)

## Current Behavior
```
Error: Cannot find module 'C:\Users\...\AppData\Roaming\npm\node_modules\npm-check-updates\bin\cli.js'
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:774:27)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
```
## Expected Behavior
should run without issues

## Additional notes
I checked `AppData\Roaming\npm\node_modules` and indeed there is no `npm-check-updates` in there. I'm not using nvm, and run PwerShell with admin rights when installing globally. Install process itself is finished without errors, but no folder is created. Local install works without issues, though

**Comment by raineorshine** [comment]
This seems like an npm issue. Sometimes it doesn't link binaries correctly, but I'm not sure the cause. It could be a permissions issues. Some people have had to re-install npm.

**Comment by AndrewBogdanovTSS** [comment]
@raineorshine I tried to install the latest version of npm which is 7.18.1 and also run it with admin permissions, but still wasn't able to install it, also tried installing with yarn but got same failed result

**Comment by raineorshine** [comment]
I wish I could help, but it doesn't seem related to `npm-check-updates`. All the tests pass on Windows and nobody else has reported problems installing.

**Comment by AndrewBogdanovTSS** [comment]
The only thing that "helped" me is installing LTS version of Node + NPM (Before that I was using v.16) via NVM. Closing the issue
