### ISSUE TITLE
ncu not showing the package differences

### ISSUE THREAD

**Issue by kranthikumar-kvs-by** [raineorshine/npm-check-updates#937]
ncu not showing the package differences on my system -

Version on my system -->

OS - Windows 10
node - v14.17.0
npm - v7.16.0
npm-check-updates - v11.8.3

I just got the latest Create React APP using this command -
npx create-react-app my-app --template typescript

When executed ncu on this folder I get -

![image](https://user-images.githubusercontent.com/60686473/129322025-fa1e6b5f-1ad7-4458-ba97-c15778dd0622.png)

Expected to show these differences when run on another machine -

![image](https://user-images.githubusercontent.com/60686473/129322397-966ea89f-77fd-4bb1-a6ae-aeb1a3d6754e.png)

Please let me know if you need any more details or required to execute any commands to get more details.

**Comment by fabd** [comment]
Hi,

not sure if related but today oddly enough `ncu` in Terminal (Mac Mini M1, Big Sur), didn't show me the `vue` package update.

`ncu` command showed upgrades for most packages, including esbuild and npm-check-updates , but not vue... which got me investigating a [version mismatch error in Vite](https://github.com/vitejs/vite/issues/4573) until finally I noticed in my package.json that `vue` was still on 3.0.5.

I had this section in my package.json (above "devDependencies"):

```js
"dependencies": {
    "esbuild": "^0.12.1",
    "npm-check-updates": "^11.5.13",
    "vue": "^3.0.5"
  },
```

I tried reordering the `vue` line in package.json, move it up one line, or move it into the "devDependencies" below just to see what happens... but `ncu` still doesn't show it. Or did I miss something silly?

After manually editing `vue` to `"^3.2.x"` and `npm install`...  it did upgrade to vue@3.2.2.

First time I had an issue, ncu is really useful!

**Comment by kranthikumar-kvs-by** [comment]
In my case we are using react and I don't see any issues with package.json file.

**Comment by raineorshine** [comment]
@kranthikumar-kvs-by Sorry it's not working for you. I wonder what is different on that machine. I ran `npx create-react-app my-app --template typescript && cd my-app && ncu` and it correctly reports upgrades for me:

```sh
raine[my-app]% ncu                                                                                                  ✓
Using yarn
Checking /private/tmp/temp/my-app/package.json
[====================] 12/12 100%

 @testing-library/jest-dom     ^5.11.4  →   ^5.14.1
 @testing-library/react        ^11.1.0  →   ^12.0.0
 @testing-library/user-event  ^12.1.10  →   ^13.2.1
 @types/jest                  ^26.0.15  →   ^27.0.1
 @types/node                   ^12.0.0  →   ^16.6.1
 @types/react                  ^17.0.0  →  ^17.0.18
 @types/react-dom              ^17.0.0  →   ^17.0.9
 typescript                     ^4.1.2  →    ^4.3.5
 web-vitals                     ^1.0.1  →    ^2.1.0

Run ncu -u to upgrade package.json
```

Can you post the output from `ncu --loglevel verbose`?

**Comment by raineorshine** [comment]
@fabd I'll respond to yours in a new issue, as it is a different problem.

**Comment by kranthikumar-kvs-by** [comment]
@raineorshine, as requested here is the output after running "ncu --loglevel verbose" -

![image](https://user-images.githubusercontent.com/60686473/129840690-800f2547-1c84-4a83-8aa4-3db407568156.png)

**Comment by raineorshine** [comment]
It seems like it's not getting any results back from yarn for some reason. You can try:

1. Make sure you are using the latest version of `yarn`
2. Force npm-check-updates to use npm: `ncu -p npm`
3. Check if `pacote`, the package downloader that npm-check-updates uses, is working: `npx pacote packument ncu-test-v2`

**Comment by raineorshine** [comment]
The output message should definitely be improved though.

**Comment by kranthikumar-kvs-by** [comment]
Still same results with "ncu -p npm" -

![image](https://user-images.githubusercontent.com/60686473/129937529-1ccaf4e5-552f-4abb-a8ee-d289abd29a6c.png)

This is the result with "npx pacote packument ncu-test-v2" and then executing "ncu -p npm" again -

![image](https://user-images.githubusercontent.com/60686473/129937909-775032ad-e468-4cb4-8e96-b32760c8d87f.png)

**Comment by raineorshine** [comment]
Everything seems to be working. Can you confirm that the dependencies in that package.json are actually out of date when you manually inspect it? i.e. Make sure they haven't already been upgraded somehow.

**Comment by kranthikumar-kvs-by** [comment]
Dependencies are out of date in package.json -

"dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1"
  },

**Comment by raineorshine** [comment]
Okay, thanks. I can't think of what else to try besides going to the source code and adding `console.log` to determine why no results are coming back. If you find a way to reproduce it on other machines let me know and I'd be happy to troubleshoot it myself.

I would be curious what would happen if you cloned the repo and ran the tests on that machine. Maybe the failing tests would give us some indication of where the problem might be.

As a brute force approach, you could try re-installing npm-check-updates and if that doesn't work re-installing node and npm.

**Comment by kranthikumar-kvs-by** [comment]
@raineorshine, as mentioned by you I have run the tets locally, and here is the test report.
[TestResults.txt](https://github.com/raineorshine/npm-check-updates/files/7047239/TestResults.txt)

Let see if you can find any issues with this result.

**Comment by raineorshine** [comment]
Thank you. The test results appear to suffer the same problem. None of the upgrades are returning from the registry.

My best guess it that the registry is returning a 404 for some reason. npm-check-updates is designed to ignore 404 errors, although better warnings will be provided in the future. Are you behind a Firewall or corporate intranet? 

You could try a different registry and see if that works:

```
ncu --registry https://registry.npm.taobao.org
```

**Comment by kranthikumar-kvs-by** [comment]
Thank you.
Yes, I am behind corporate intranet.

I tried with registry directly and it worked!

![image](https://user-images.githubusercontent.com/60686473/130827668-d365948d-6df7-41b0-95b2-a7bb2d8e1812.png)
