### ISSUE TITLE
Does not show vue upgrades

### ISSUE THREAD

**Issue by raineorshine** [raineorshine/npm-check-updates#938]
@fabd 

> EDIT: in my case, not seeing `vue` upgrade is likely not issue with ncu (cf. [response below mine in vitejs/vite issue related to vue version mismatch](https://github.com/vitejs/vite/issues/4573#issuecomment-898505274)), sorry for the trouble!
> 
> Hi,
> 
> not sure if related but today oddly enough `ncu` in Terminal (Mac Mini M1, Big Sur), didn't show me the `vue` package update.
> 
> `ncu` command showed upgrades for most packages, including esbuild and npm-check-updates , but not vue... which got me investigating a [version mismatch error in Vite](https://github.com/vitejs/vite/issues/4573) until finally I noticed in my package.json that `vue` was still on 3.0.5.
> 
> I had this section in my package.json (above "devDependencies"):
> 
> ```js
> "dependencies": {
>     "esbuild": "^0.12.1",
>     "npm-check-updates": "^11.5.13",
>     "vue": "^3.0.5"
>   },
> ```
> 
> I tried reordering the `vue` line in package.json, move it up one line, or move it into the "devDependencies" below just to see what happens... but `ncu` still doesn't show it. Or did I miss something silly?
> 
> I am pretty darn sure I was on an older version of vue, this was part of output of `npm ls`:
> 
> ```
> +-- vue@3.0.11
> | +-- @vue/compiler-dom@3.0.11
> | | +-- @vue/compiler-core@3.0.11
> ```
> 
> After manually editing `vue` to `"^3.2.x"` and `npm install`... it did upgrade to vue@3.2.2.
> 
> First time I had an issue, ncu is really useful! 👍

`ncu` upgrades to whatever version is published at the `latest` tag in the npm registry. `vue` latest is still `v2`:

```
% npm view vue dist-tags                                                                                 ✗
{
  latest: '2.6.14',
  csp: '1.0.28-csp',
  next: '3.2.4',
  beta: '3.2.0-beta.8'
}
```

To upgrade all dependencies to the highest available version, use `ncu --target greatest`.

To upgrade only `vue` to the highest available version, run `ncu` twice: `ncu ; ncu --target greatest vue`

**Comment by fabd** [comment]
> ncu upgrades to whatever version is published at the latest tag in the npm registry. vue latest is still v2:

Indeed, thank you 👍
