### ISSUE TITLE
Incorrectly updates "> 0.0.0" to "> 0.0.5" when 0.0.5 is latest 

### ISSUE THREAD

**Issue by henrik** [raineorshine/npm-check-updates#957]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

My package.json includes in its `devDependencies`:

```
"@barsoom/prettier-config": "> 0.0.0",
```

## Current Behavior

Running `npx npm-check-updates --upgrade --peer` changes this constraint to `> 0.0.5`.

But since the latest version of the package is 0.0.5, there is no greater version, so `npm install` fails.

Same issue if the old version is `> 0.0.1`.

## Expected Behavior

Either leaving the constraint as-is, or changing it to `>= 0.0.5`, or `0.0.5`, or `^0.0.5`, or similar.

## Workaround

Changing `> 0.0.0` to `>= 0.0.0` fixes it. It becomes `>= 0.0.5`.

**Comment by raineorshine** [comment]
Fixed and published in [v12.0.0](https://github.com/raineorshine/npm-check-updates/releases/tag/v12.0.0).
