### ISSUE TITLE
Add request failed retry

### ISSUE THREAD

**Issue by lyswhut** [raineorshine/npm-check-updates#959]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce

1. Disconnect from the network
2. Run `ncu`

## Current Behavior

Throw an error directly

## Expected Behavior

Retry a few times before throwing an error, hope that the number of retries is configurable

**Comment by lyswhut** [comment]
Any news? I can provide a PR to add it :)

**Comment by raineorshine** [comment]
Always open to a PR! Thanks!

**Comment by raineorshine** [comment]
Fixed and published in `v12.2.0`
