### ISSUE TITLE
hacked package mitigation - minimum package age

### ISSUE THREAD

**Issue by rafipiccolo** [raineorshine/npm-check-updates#962]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

** problem **
latest version of packages may sometimes be buggous / hacked.
Usually the hacked version are blocked some hours after. same goes for bugs. A new/safer version is released some hours/days after.
Here is an exemple of hack, a few days ago : https://portswigger.net/daily-swig/popular-npm-package-ua-parser-js-poisoned-with-cryptomining-password-stealing-malware
the hacked packages were deleted in ~5hours.

** solution **
to handle bugs, everyone need to test his own codebase with unit tests. (i'm trying to do this)
To handle hacks, i would like a way to install latest package version but ignoring packages that are less than 1 day old.
maybe a new option on the cli, like --min-age NUMBER_OF_DAYS to ignore package version that are too young.

Maybe you have a better solution ? Or is it too hard to implement ?

**Comment by rafipiccolo** [comment]
> Do you wish to include betas, and pre-releases, or only stable versions?
I dont really care as long as the package is old enough to be considered for update and my mocha passes.
tbh i didnt notice what exatly target minor / major or semver in general does regarding betas

**Comment by raineorshine** [comment]
Still an open issue, but closing in favor of #833.
