### ISSUE TITLE
FetchError: Request Timeout

### ISSUE THREAD

**Issue by alveshelio** [raineorshine/npm-check-updates#963]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

## Steps to Reproduce
ncu
## Current Behavior
When `ncu` it throws an error
FetchError: Request Timeout. npm-registry-fetch defaults to 30000 (30 seconds). Try setting the --timeout option (in milliseconds) to override this.
/Users/xxxx/.npm-global/lib/node_modules/npm-check-updates/lib/index.js:428
  throw err
  ^
FetchError: Response timeout while trying to fetch https://registry.npmjs.org/@graphql-codegen%2fcli (over 30000ms)
    at Timeout._onTimeout (/Users/helio/.npm-global/lib/node_modules/npm-check-updates/node_modules/minipass-fetch/lib/body.js:128:28)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'FETCH_ERROR',
  errno: 'FETCH_ERROR',
  type: 'body-timeout'
}
## Expected Behavior
Expected to have a list of outdated packages

**Comment by raineorshine** [comment]
This is a network error and I believe the error message is appropriate. You can increase the timeout as instructed if you are on a slow internet connection. Is this a request to increase the default timeout?

**Comment by cehenriques** [comment]
I'm having the same issue when I'm connected to the company VPN, using the Cisco AnyConnect VPN client.
I don't think it is a slow internet connection, because while connected to the VPN I still have a connection of 518 Mbps / 120 Mbps (without VPN it's a 1 Gbps connection).
When I disconnect the VPN ncu works without any issues.

**Comment by alveshelio** [comment]
> This is a network error and I believe the error message is appropriate. You can increase the timeout as instructed if you are on a slow internet connection. Is this a request to increase the default timeout?

It was indeed an issue with my network and not npm-check-updates, my bad.
