### ISSUE TITLE
Error when checking global `Yarn` modules on `12.0.0`

### ISSUE THREAD

**Issue by jmopel** [raineorshine/npm-check-updates#978]
- [x] I have searched for [similar issues](https://github.com/raineorshine/npm-check-updates/issues)
- [x] I am using the latest version of `npm-check-updates`
- [x] I am using `node >= 10.17`

---------------------------

This bug appeared on the latest version, `12.0.0`. All good on `11.8.5`.

## Steps to Reproduce
```ps1
ncu -g -p yarn
```
## Current Behavior
```log
C:\Users\<USER>\AppData\Local\Yarn\Data\global\node_modules\npm-check-updates\build\src\index.js:27
    throw err;
    ^
error Couldn't find a package.json file in "C:\\Users\\<USER>"
```
## Expected Behavior
Successful check as on version `11.8.5`

**Comment by raineorshine** [comment]
Thanks for reporting! Is that the correct path where your package.json is at?

**Comment by Jmopel** [comment]
Sorry for the late reply.

The current working directory was:
```ps1
C:\Users\<USER>
```

My `global` Yarn `package.json` is located here (by default):
```
C:\Users\<USER>\AppData\Local\Yarn\Data\global
```

Thank you!

**Comment by xorander00** [comment]
Seeing the same issue/error across multiple machines. Haven't looked into the exact reason yet, just let me know if any more info would be helpful. 
  
### ncu -g
```
/usr/home/myuser/config/yarn/global/node_modules/npm-check-updates/build/src/index.js:27
    throw err;
    ^
warning package.json: No license field
error Command "g" not found.

(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

---

### Apple M1, 2020 MacBook Pro

ncu --version
**12.0.0**

yarn --version
**1.22.17**

node --version
**v16.13.0**

uname -a
**Darwin applem1 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:20 PDT 2021; root:xnu-7195.141.6~3/RELEASE_ARM64_T8101 arm64**

---

### Lenovo, 2013 ThinkPad W530

ncu --version
**12.0.0**

yarn --version
**1.22.15**

node --version
**v16.13.0**

uname -a
**FreeBSD freebsd13 13.0-STABLE FreeBSD 13.0-STABLE #1 stable/13-n247427-65f22ccf824: Sat Sep 25 17:22:26 EDT 2021     root@poudriere:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64**
