### ISSUE TITLE
Updating package.json without -u option

### ISSUE THREAD

**Issue by patricjansson** [raineorshine/npm-check-updates#995]
ncu: 12.0.2
node: v14.16.0

---------------------------

"ncu" updates package.json, previously it only updated versions when otion -u was passed "ncu -u". A "ncu" only displayed differences.

New behavior in v12?

**Comment by rafipiccolo** [comment]
Similarly, if i pass a packageData directly, ncu is looking for "../../package.json" and cant find it.
It used to work.

```
ncu --target minor --packageData {"dependencies":{"......"}}
node:internal/modules/cjs/loader:936
throw err;
^

Error: Cannot find module '../../package.json'
Require stack:
- /usr/local/lib/node_modules/npm-check-updates/build/src/bin/cli.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:999:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object. (/usr/local/lib/node_modules/npm-check-updates/build/src/bin/cli.js:11:40)
at Module._compile (node:internal/modules/cjs/loader:1097:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
at Module.load (node:internal/modules/cjs/loader:975:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/usr/local/lib/node_modules/npm-check-updates/build/src/bin/cli.js'
]
}

Node.js v17.1.0
```

**Comment by gladevise** [comment]
`ncu -g` causes same issue.
Node.js v16.13.0
ncu v12.0.1

**Comment by raineorshine** [comment]
> "ncu" updates package.json, previously it only updated versions when otion -u was passed "ncu -u". A "ncu" only displayed differences.

I'm not able to reproduce this. When I run `ncu` it does not modify the package.json. Is there any chance you have `upgrade: true` set in a `.ncurc` file? If not, I will need steps to reproduce. Thanks!

**Comment by raineorshine** [comment]
@rafipiccolo Please create a separate issue and include all information requested in the template. Thank you!

**Comment by patricjansson** [comment]
@raineorshine Ooh crap there was a .ncurc with `upgrade: true` set. Sorry for missing that 😞
npm-check-updates is an awesome thing! If you end up in Stockholm, Sweden I will buy you a coffee as thanks! Keep up the great work!

**Comment by patricjansson** [comment]
@rafipiccolo Have you tried upgrading to the last version? I hade the same problem in 12.0.0 or maybe 12.0.1 which was fixed in 12.0.2

**Comment by rafipiccolo** [comment]
yes, solved. thx

**Comment by MartinX3** [comment]
12.0.0 was fine
12.0.1 is broken
Can't wait to test 12.0.2 (on arch linux it's a system package which is still on 12.0.1)
